### ISSUE TITLE
Can't run in Yosemite

### ISSUE THREAD

**Issue by arusahni** [paralect/robomongo#1000]
I get the error message;

'You can't use this version of the application "Robomongo.app" with this version of OS X. You have OS X 10.10.5. The application requires OS X 10.11 or later"

`robomongo-0.9.0-RC1-darwin-fb796ce.dmg`

**Comment by anorsich** [comment]
@arusahni 
[Here is](https://github.com/paralect/robomongo/files/98169/robomongo-0.9.0-RC1-darwin-fb796ce.dmg.zip) the version of robomongo built on Yosemite. Please, give it a try and let me know if it worked for you, so we can adjust robomongo build process.

**Comment by arusahni** [comment]
@anorsich that works for me! I'm able to install and launch it.  Thanks for the speedy response!

**Comment by DavidBabel** [comment]
should be the way it works for the main version.

A lot of dev don't enjoy El Capitan, and still work on Yosemite

**Comment by anorsich** [comment]
@DavidBabel Official package (which resides on [dropbox](https://www.dropbox.com/s/o72l64px3kcocfz/robomongo-0.9.0-RC1-darwin-852c704.dmg?dl=0)) now supports OSX Yosemite
