### ISSUE TITLE
Can't save document in 0.9rc on OSX

### ISSUE THREAD

**Issue by mikaoelitiana** [paralect/robomongo#1001]
I am trying the OSX RC with mongo 3 support but I can't save document when editing one of them. I fact, nothing happen when I click the save button nor the validate button

**Comment by schetnikovich** [comment]
@mikaoelitiana, this issue will be addressed before release of the final 0.9.0. Is it possible for you to share document for which update doesn't work? In particular, I'm interesting in list of BSON types that are used in your BSON document. 

In any way, please do not use RC version on production database.

**Comment by mikaoelitiana** [comment]
Hello @schenikovich, 
In fact update won't work for any document and I have tried multiple servers. I will try to compile it by myself to check if I have the same behaviour.

**Comment by anorsich** [comment]
@schetnikovich It looks like it is unpossible to save a document when it has date, all other bson types seems to be working fine.

**Comment by mikaoelitiana** [comment]
@anorsich, you are right, I didn't noticed this! On document withour date I can do update.

**Comment by piotrekkmt** [comment]
Same issue here. I have a couple of nested arrays of objects in other nested arrays all of which have a timestamp associated with them. This is quite a big deal.

**Comment by alexpts** [comment]
0.9RC1 not work save.
0.9RC2 work save! :+1:

**Comment by anorsich** [comment]
@alexpts Awesome! Thanks for help with testing!

**Comment by mikaoelitiana** [comment]
We can close this now as it is fixed in RC2
