### ISSUE TITLE
SSL/SSH support

### ISSUE THREAD

**Issue by matthiasdg** [paralect/robomongo#1002]
It seems it's no longer possible to provide a .pem file to robomongo? I have a database which uses a certificate for authentication. With the old version this worked fine, now there is no such option :disappointed: 
Robomongo was the only tool I found that supported this...

**Comment by derEremit** [comment]
There's a release announcement, which you should have seen, otherwise why would you upgrade to RC1
http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/

List of known limitations of current version:

    SSH support was disabled
    SSL support was disabled
    Log messages are not printed in Logs panel at the bottom
    Validation of JSON/BSON records doesn't work in JSON Editor

If you are using SSH or SSL in Robomongo 0.8.5, we recommend to backup your existing ~/.config/robomongo/robomongo.json, because configuration settings for SSH and SSL will be removed.

**Comment by matthiasdg** [comment]
My bad, didn't see this. Another project I'm working on uses mongo 3.2.1 (luckily without SSL) and the previous version didn't list the collections, so I just looked for an upgrade (I guess the "full support for mongodb 3" in the page title convinced me it was OK). Sorry!

**Comment by fguillen** [comment]
Is it here where to ask for SSH tunnel support in Robomongo? :+1:

**Comment by moshest** [comment]
Why you removed the SSH tunnel support from version 9?
Can you add it back please?

**Comment by zoonman** [comment]
Ребята, верните пожалуйста SSH туннель.

**Comment by stegzilla** [comment]
Any word on when this is coming back?

**Comment by vakkalagadda** [comment]
Do we've any date when we can expect it in the latest robomongo version?

**Comment by MetalCar** [comment]
Why did you remove SSH tunnel?
Now I can't connect to my mongo servers.... so i have to downgrade to version 0.8.4.
Is it possible to add it again?

**Comment by schetnikovich** [comment]
Support for SSH and SSL are our current priority. We are working on SSH feature right now. Hope that very soon we will release Robomongo that will support SSH. Stay tuned :)

**Comment by sbias** [comment]
Missing SSH support prevents me from upgrading too ... very happy to hear that it comes back soon :)

**Comment by MetalCar** [comment]
@schetnikovich Very nice :) I wait for it :)

**Comment by moshest** [comment]
You can use tunneling instead:
`ssh -L 27018:localhost:27017 user@server.mongodb.com`

Then login to port 27018 on your local machine.

**Comment by lucaskatayama** [comment]
+1 pleaase

**Comment by h0rn3t** [comment]
+1

**Comment by abdonrd** [comment]
+1

**Comment by Bodenhaltung** [comment]
SSL is necessary for me (SSL require), so at the moment i can't use robomongo.

Is there a ETA for ssl?

**Comment by anorsich** [comment]
@Bodenhaltung SSH support is on the way, I assume we will have it ready in a couple of weeks. SSL would be a priority right after.

**Comment by anorsich** [comment]
@Bodenhaltung @abdonrd @h0rn3t @lucaskatayama 

Happy to announce, that Robomongo RC8, which was released just a few minutes ago now supports SSH connections. That functionality was re-worked from scratch and now much more stable and user-friendly. Read more details on our [blog post](http://blog.robomongo.org/robomongo-rc8/).

Hooray! 

P.S. We will keep that ticket open, until SSL will be implemented as well.

**Comment by anaibol** [comment]
Compose.io requires SSL connection and Robomongo is the only decent GUI for Linux, but without SSL :(

**Comment by Perados** [comment]
Any news on SSL support? Many of us need it for compose.io. Thank you in advance!

**Comment by jeffwidman** [comment]
Just create a SSH tunnel in your `.ssh/config` file that maps remote mongo port to a local port, then robomongo can connect just fine, and the traffic is encrypted by SSH.

**Comment by ckuethe** [comment]
We know how to tunnel over ssh, that's not always possible.

**Comment by jeffwidman** [comment]
For what reasons?

**Comment by ckuethe** [comment]
A remote database that supports ssl and not ssh

**Comment by IlyaDiallo** [comment]
> Any news on SSL support?

It's happening, see the SSLTab branch: https://github.com/paralect/robomongo/tree/SSLTab

**Comment by simsekgokhan** [comment]
Hi guys, we have officially started developing SSL feature for the new release of Robomongo and SSL support is our top priority right now. Hang in there a little more :) -- Best Regards, Gokhan

**Comment by simsekgokhan** [comment]
Hi guys, we have almost finished developing SSL support and we will start internal testing very soon. If anyone interested in trying/testing beta version of SSL-Robomongo, please send an email to this address: g.simsek@paralect.com

**Comment by vakkalagadda** [comment]
Good to hear the SSL support is soon available to the robomongo users

**Comment by simsekgokhan** [comment]
New Robomongo with SSL support has been released. Thanks everybody for your patience and special thanks to beta testers. Please see also other features of the new release in our blog: http://blog.robomongo.org/robomongo-rc10/ - https://robomongo.org/download - Warm Regards from Robomongo Team.

**Comment by simsekgokhan** [comment]
We also plan to give a free copy of official Robomongo RC10 as gift to beta testers for their help without waiting 17 days :-) Follow the latest updates on twitter: https://twitter.com/Robomongo

**Comment by vakkalagadda** [comment]
Team Robomongo is amazing , @simsekgokhan  I don't find the RC10 windows based version available for testers in twitter, was it tweeted already ? Thanks

**Comment by simsekgokhan** [comment]
Hi @vakkalagadda , beta testing period has been finished. The last comment is for beta testers who have already participated and completed testing for the past weeks.

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed. In any case please feel free to create new ticket in any case. Thank you!
