### ISSUE TITLE
It is not possible to connect to 2.6 server with 0.9 (without ssl or ssh, with 0.8 all fine)

### ISSUE THREAD

**Issue by AlexKovynev** [paralect/robomongo#1003]
It may be necessary to make it possible to select the type of authentication.

**Comment by daernsinstantfortress** [comment]
Interesting, I just did a quick test on my local laptop with 0.9.0 RC2 and could connect to both a local 2.6 as well as a local 3.0 DB without problem. Neither had authentication enabled.

**Comment by michaelwhenderson** [comment]
0.9.0 RC2 failed to connect to my mongo 2.6 server with authentication enabled.  I could connect to 2.6 if I disabled authentication.

**Comment by anorsich** [comment]
@AlexKovynev Could you provide details of your mongodb instance configuration (including authentication)? That should help us investigate an issue.

**Comment by AlexKovynev** [comment]
Linux, old standalone 2.6.1 mongodb, auth is enabled, some users was added. I think problem in this.

Changed in version 3.0: New challenge-response users created in 3.0 will use SCRAM-SHA-1. If using 2.6 user data, MongoDB 3.0 will continue to use the MONGODB-CR.

Maybe you use SCRAM-SHA-1? Maybe you can add some select to the connection dialog? (SCRAM-SHA-1/MONGODB-CR)

**Comment by anorsich** [comment]
If your instance SCAM-SHA-1 authentication, robomongo does not support it yet. You can track progress of implementing that authentication mechanism in this ticket #766. With  MONGODB-CR authentication robomongo should work well.

**Comment by anorsich** [comment]
@AlexKovynev Good news for you. Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) supports SCAM-SHA-1/MONGODB-CR authentications. It works exacly like you suggested, you can select proper authentication when creating connection. Let us know if work for you. Feel free to reopen this ticket if it does not.
