### ISSUE TITLE
Not displaying indexes correctly in 0.9.0 RC2

### ISSUE THREAD

**Issue by daernsinstantfortress** [paralect/robomongo#1004]
Querying for indexes for a collection returns the following:

`db.testCollection.getIndexes();`
[object BSON],[object BSON]

Forcing the output to print works ok:
`printjson(db.testCollection.getIndexes());`
_prints indexes correctly_

This is reproducible against both 3.0 WT and 2.6 MMAPv1.

ps. Many, many thanks for this release. Hugely appreciated!

**Comment by schetnikovich** [comment]
@daernsinstantfortress, this issue is currently fixed and will be part of Robomongo 0.9 RC3.

**Comment by schetnikovich** [comment]
@daernsinstantfortress This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
