### ISSUE TITLE
Why is sad Keanu on the homepage?

### ISSUE THREAD

**Issue by jherman** [paralect/robomongo#1006]
http://blog.robomongo.org/

![Image of Yaktocat](http://images-cdn.moviepilot.com/image/upload/c_fill,h_900,w_1600/t_mp_quality/p8mpbnolztn23f5ooiah.jpg)

**Comment by schetnikovich** [comment]
:)

**Comment by AlexShkor** [comment]
We are working on making him happy :smile:

**Comment by schetnikovich** [comment]
No more sad Keanu on home page :sparkles:
