### ISSUE TITLE
Documents not visible from a restored database

### ISSUE THREAD

**Issue by jtobinisaniceguy** [paralect/robomongo#1007]
If I mongodump a remote database and use mongorestore to load into a local database, the documents are not visible. The structure is present, but details are not available..
If I use the mongo shell I can see the documents, structure and contents are visible in local database

In my setup I use a remote database running mongo 3.0.0, local was 3.2.1
Use mongodump to access remote
Use mongorestore  to replicate in local

Same experience when using db.copyDatabase() 
Robomongo v0.8.5
Awesome tool otherwise

**Comment by anorsich** [comment]
@jtobinisaniceguy Robomongo v0.8.5 does not support mongodb 3+. We already have [0.9 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) version which should works well for you.

**Comment by schetnikovich** [comment]
@jtobinisaniceguy Let us know, how new version (RC2) works for you. For any found issues, please create new ticket.
