### ISSUE TITLE
Where is the SSH tunnel settings on v 0.9.0 RC2 Mac version

### ISSUE THREAD

**Issue by boosis** [paralect/robomongo#1008]
I just downloaded version 0.9.0 RC 2 but cannot see ssh tunnel settings for connection. Is it removed?

![screen shot 2016-01-28 at 10 25 30](https://cloud.githubusercontent.com/assets/548717/12641810/a7235c50-c5a9-11e5-807d-db91fb9b4be1.png)

**Comment by schetnikovich** [comment]
@boosis Yes, it is currently disabled and was mentioned in the list of [known limitations](http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3) of RC versions. The best workaround for now is to open SSH tunnel on your Mac OS and connect Robomongo with MongoDB via this tunnel. I'm ready to help you to do this, if you are unsure how to do this. But here is a detailed explanation about how to do this for Mac: http://manas.tungare.name/blog/ssh-port-forwarding-on-mac-os-x

**Comment by boosis** [comment]
@schetnikovich I guess I missed that from the list :) No worries, I am already using the ssh tunnelling and port forwarding.

Thanks for the help

**Comment by schetnikovich** [comment]
You are welcome!

**Comment by iSuslov** [comment]
So what, is it still disabled?

**Comment by myaskevich** [comment]
@iSuslov We're happy to say SSH support is back in the RC8 version! [Read more](http://blog.robomongo.org/robomongo-rc8/) or [download](https://robomongo.org/download).
Should you have any questions, please do no hesitate to ask them here.
