### ISSUE TITLE
'show collections' query do not run.

### ISSUE THREAD

**Issue by Abhivendra** [paralect/robomongo#1012]

**Comment by anorsich** [comment]
@Abhivendra Whiich version of mongo do you use? Do you use replica set? It seems to be working fine on mongodb 2.6, 3.0 it's work just fine.

**Comment by anorsich** [comment]
@Abhivendra We just released [Robomongo 0.9.0 RC4](http://blog.robomongo.org/p/d7a5d7d8-e13c-4a82-9665-5fae38ebe46e/) which do support connections to the replica set (including slaves) and Mongodb-CR/SCRAM-SHA-1 authentions I beleive that should help with your current issue. Could try it and let us know if it work for you.

**Comment by anorsich** [comment]
@Abhivendra I am closing this ticket for now. If it still does not work for you with latest release - feel free to reopen.
