### ISSUE TITLE
Upgrading from RC1 to RC4 on Mac dropped all my connection settings

### ISSUE THREAD

**Issue by kimyanitov** [paralect/robomongo#1013]
Upgrading from RC1 to RC4 on Mac choosing to replace the old one and found all my connection settings to various DBs were wiped completely..

**Comment by schetnikovich** [comment]
@kimyanitov Starting from RC2 configuration file is located here:

`~/.config/robomongo/0.9/robomongo.json`

For RC1 and previous versions it was here:

`~/.config/robomongo/robomongo.json`

Just copy file to `0.9` folder and all your connections will be restored.

We wrote about this change here: http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/

**Comment by kimyanitov** [comment]
Is that possible to copy old one over to new location on first start up? I can try fixing it if you point me to the file responsible...

**Comment by anorsich** [comment]
@kimyanitov I've created a wiki page, which explains how to copy old connection strings over to the new location [here](https://github.com/paralect/robomongo/wiki/Restore-connection-strings-from-versions-below-0.9.0-RC2). Going to close this ticket now, let us know if you still have any troubles.
