### ISSUE TITLE
Mac OS X: Working through "native" ssh tunnel works faster than internal

### ISSUE THREAD

**Issue by and-rew** [paralect/robomongo#1016]
To connect to my remote MongoDB VM, I have always used ssh tunnel created with terminal in Mac OSX (latest El Capitan).
Then I have found that I could create a tunnel straight in Robomongo, but it appeared much slower than working through terminal tunnel.
Version: 0.8.5
Possibly related to #730 #1014, though I have only four collections currently.

**Comment by RobbeR** [comment]
Hi,
I just installed the latest (0.9) release, and I can't find the option to create SSH tunnel. This is the reason why they removed it? I think it was really handy, so I will miss that feature :(

**Comment by kuteninja** [comment]
I came here searching for the same, a way to automatically connect using an SSH tunnel (it's too tedious to create one each time on the terminal)

**Comment by mindojo-victor** [comment]
https://github.com/paralect/robomongo/issues/1050#issuecomment-195306709

**Comment by anorsich** [comment]
@and-rew @RobbeR @kuteninja @mindojo-victor 

Happy to announce, that Robomongo RC8, which was released just a few minutes ago now supports SSH connections and now works much faster than before. That functionality was re-worked from scratch and now much more stable and user-friendly. Read more details on our [blog post](http://blog.robomongo.org/robomongo-rc8/).

Feel free to reopen this ticket if you'll that it still slow for you. In next versions, we are also planning to add zipping for ssh connections, but even know the performance of Robomongo tunnel is comparable with native ssh tunnel performance.
