### ISSUE TITLE
ESC key in edit window cancels edit.

### ISSUE THREAD

**Issue by bitdivision** [paralect/robomongo#1017]
I use VIM and it has become a habit to press escape after typing things. In most cases this isn't an issue however when I'm editing a document in RoboMongo and hit escape, it cancels the edit, losing everything I've typed.

I'd imagine this is an issue for most VIM users, is there any chance of an option to configure this? Or would you accept a PR for it?

**Comment by myaskevich** [comment]
I'm also a Vim user and I find it more comfortable to use `Ctrl+[` instead of `Esc` button. You can try that.
I think we would rather accept a PR for global shortcut management settings in separate dialog, not just an option to turn off `Esc` key binding.
Just let me know if you need help on that.

**Comment by bitdivision** [comment]
I'm quite used to hitting CAPS-LOCK (remapped to ESC), and It would be a fairly significant habit to break...

Adding another dialog is most likely somewhat beyond my ken at the moment. 

What about a confirmation dialog if ESC is hit when there are unsaved edits?

**Comment by schetnikovich** [comment]
@bitdivision, we now show confirmation dialog when you hit ESC in BSON editor. This was implemented by Anton Zering (@synthomat). This feature will be part of the next release (RC7).

We definitely looking forward to allow customisation of this behaviour, including complete disable for ESC key in editors. In the meantime confirmation dialog will temporary solve this problem for VIM users.

**Comment by bitdivision** [comment]
@schetnikovich:

Thanks very much, this will be a great help.

**Comment by juliashibalko** [comment]
@schetnikovich  let's remove confirmation dialog in BSON editor when user clicks 'View Document', makes some changes and then hits ESC button. Changes won't be saved anyway

**Comment by bitdivision** [comment]
Personally I don't think the issue really occurs in view mode - you're never typing so should never hit escape accidentally. So I would suggest removing it completely from the view mode. Doing that does create some inconsistency between modes though, but I don't imagine it's a problem.

Thanks again for sorting this one out @synthomat

**Comment by schetnikovich** [comment]
@synthomat @bitdivision We decided to disable editing in View Mode, because it is useless. It is now simple viewer with just single Cancel button on the screen.
