### ISSUE TITLE
Install on windows without admin rights?

### ISSUE THREAD

**Issue by patryk0605** [paralect/robomongo#1019]
Is it possible to install robomongo on windows without admin rights? Is there a portable/zip version that can be used? Thanks in advance for any feedback!

**Comment by anorsich** [comment]
@patryk0605 Thank you for reporting the issue! We will add a portable version of Robomongo in next release. That shouldn't be a big problem. I'll update you once it ready!

**Comment by anorsich** [comment]
@patryk0605 Starting from RC-6 release we are building portable `zip` archive, which you can download, unpack and use :) Thank you for helping us!

**Comment by patryk0605** [comment]
That is great news! Thanks for the very quick turnaround.
