### ISSUE TITLE
Getting collection is really slow

### ISSUE THREAD

**Issue by eman1986** [paralect/robomongo#1023]
My team and I love your mongo client.

One issue we all hit is that our mongo instance has a lot of collections and it takes a long time to load the list.

We've used other tools that didn't take as long but we really like your tool better so I'm hoping its something that could get looked at.

Thanks

**Comment by anorsich** [comment]
Hi @eman1986! I have great news for you! This issue was fixed in the latest RC-6 release. If you'll have a minute, write back to me if it works for you. If it doesn't -- please, reopen this ticket!
