### ISSUE TITLE
Windows Defender detects Trojan:Win32/Varpes.L!plock

### ISSUE THREAD

**Issue by leebradley** [paralect/robomongo#1024]
Downloaded from the official URL: https://download.robomongo.org/0.9.0-rc4/windows/robomongo-0.9.0-rc4-windows-x86_64-8c830b6.exe

Windows Defender automatically quarantines it and claims it contains Trojan:Win32/Varpes.L!plock

![malware](https://cloud.githubusercontent.com/assets/597352/13037303/fbfb9b9a-d33a-11e5-92a3-bd7bdec4781d.PNG)

Can't verify this is the case with any of the future release candidates.

**Comment by juliashibalko** [comment]
@leebradley Thank you for submitting the issue! Could you please provide your downloaded .exe file of 0.9.0-RC4? I verified version downloaded from the link you've mentioned above, it works well for me on Win 10 (x64) and Win 8.1 (x64).

**Comment by anorsich** [comment]
@leebradley We do not detect any issues on our side, we assume that distributive was infected right after download and there might be an issue on a client side. I am closing this one for now, if you still think that issue is on our side and can help us troubleshoot it -- feel free to reopen the ticket.

**Comment by leebradley** [comment]
I checked the SHA1 hash of the downloaded file with another website. It is indeed the same file.

**Comment by leebradley** [comment]
[robomongo-0.9.0-rc4-windows-x86_64-8c830b6.zip](https://github.com/paralect/robomongo/files/133604/robomongo-0.9.0-rc4-windows-x86_64-8c830b6.zip)

I had to zip the exe in order to upload to GitHub, but it's the same one that was quarantined by Windows Defender.

**Comment by anorsich** [comment]
@leebradley Thank you! We will check it and let you know the results. 
@juliashibalko Can you check this version using antiviruses you have?

**Comment by juliashibalko** [comment]
@leebradley Thanks for the file you provided. I have checked it under several antiviruses (Eset Nod32, Kaspersky, Avast) and Windows Defender but no threats were found. I am closing this ticket as all distributives (including yours) look fine. Feel free to reopen the ticket if you have more details that can help us in troubleshooting.
