### ISSUE TITLE
NUUID _Id request not working

### ISSUE THREAD

**Issue by fbarnard** [paralect/robomongo#1026]
Hi

In the rc04 version if i do a find _id : nuuid({guid}) i always get no result but the document is there. If i go with prev version it works. 

I used uuidhelper where i added NUUID alias

[uuidhelpers.txt](https://github.com/paralect/robomongo/files/134222/uuidhelpers.txt)

**Comment by dmitriynosenko** [comment]
I have same issue in RC6 version. Neither NUUID or CSUUID are not working. Always got no results to show.

**Comment by anorsich** [comment]
@schetnikovich I do believe that was fixed and will be as part of RC9. Please, remove RC9 milestone if I am wrong.

**Comment by schetnikovich** [comment]
@anorsich Yes, UUID helpers are now built-in and will be available in Robomongo RC9. More info: #1080

**Comment by juliashibalko** [comment]
Hi @fbarnard @dmitriynosenko! Could you please try to reproduce the issue with the latest [Robomongo 0.9.0-RC9](https://robomongo.org/download) version if you have free time? I didn't manage to replicate it on my machine. Thank you in advance!

**Comment by fbarnard** [comment]
Will  do...

On Tuesday, 5 July 2016, Julia Shibalko <notifications@github.com> wrote:

> Hi @fbarnard <https://github.com/fbarnard> @dmitriynosenko
> <https://github.com/dmitriynosenko>! Could you please try to reproduce
> the issue with the latest Robomongo 0.9.0-RC9
> <https://robomongo.org/download> version if you have free time? I didn't
> manage to replicate it on my machine. Thank you in advance!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/paralect/robomongo/issues/1026#issuecomment-230498472>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB_htJCIuy0BY5PscVEFMcujCK2H4GdAks5qSm1UgaJpZM4HcC5j>
> .
>


-- 
Francois D. Barnard
083 380 6645

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed. In any case please feel free to create new ticket. Thank you!
