### ISSUE TITLE
Getting build errors when making windows exe

### ISSUE THREAD

**Issue by eman1986** [paralect/robomongo#1028]
I'm trying to compile the latest tag so that I can test it but I keep getting the following error:

> -- Building for: Visual Studio 14 2015
>-- The C compiler identification is MSVC 19.0.23506.0
>-- The CXX compiler identification is MSVC 19.0.23506.0
>-- Check for working C compiler using: Visual Studio 14 2015
>-- Check for working C compiler using: Visual Studio 14 2015 -- works
>-- Detecting C compiler ABI info
>-- Detecting C compiler ABI info - done
>-- Check for working CXX compiler using: Visual Studio 14 2015
>-- Check for working CXX compiler using: Visual Studio 14 2015 -- works
>-- Detecting CXX compiler ABI info
>-- Detecting CXX compiler ABI info - done
>-- Detecting CXX compile features
>-- Detecting CXX compile features - done
>-- Looking for pthread.h
>-- Looking for pthread.h - not found
>-- Found Threads: TRUE
>CMake Error at CMakeLists.txt:26 (find_package):
>  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>  asked CMake to find a package configuration file provided by "Qt5Core", but
>  CMake did not find one.
>
>  Could not find a package configuration file provided by "Qt5Core" with any
>  of the following names:
>
>    Qt5CoreConfig.cmake
>    qt5core-config.cmake
>
>  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>  "Qt5Core_DIR" to a directory containing one of the above files.  If
>  "Qt5Core" provides a separate development package or SDK, be sure it has
>  been installed.

I have everything in the wiki installed so I'm at a huge loss at what I'm doing wrong. This is a first time I've ever tried to compile a C++ application so I have no experience (I've done C# & Java but know thats apples & Oranges).

Any Help would be great.

**Comment by anorsich** [comment]
Hi @eman1986,

It looks you are not set `ROBOMONGO_CMAKE_PREFIX_PATH ` environment variable. For windows path should looks like this `C:\\Qt\\5.5\\msvc2013_64;` 

Also, it looks like that you are building using vs 2015, which might work, but we never tried it. All Robomongo builds are produced using vs 2013 (Update 5)

I hope that will help you successfully build latest Robomongo.

**Comment by eman1986** [comment]
I have a small issue building mongo, I get a list index out of range error.

you guys wouldn't happen to know how to contact them on how to fix this would you? everywhere I look I don't see anything but a jira system and I'd rather just email them.

**Comment by anorsich** [comment]
@eman1986 Could you post your error log here? We might be able to help you!

**Comment by eman1986** [comment]
![mongo-build](https://cloud.githubusercontent.com/assets/2343334/13151333/af9fa7fa-d637-11e5-9d4f-fb2980339b42.png)

**Comment by anorsich** [comment]
@eman1986 The issue is with [git describe](https://git-scm.com/docs/git-describe) command. MongoDB to find most recent tag information to this commit. To check that exactly just type `git describe` in the robomongo-shell repository. If that command does not return anything - that the issue. You might pull only one branch without tags. Typically to pull everything you just need use `git clone` command.

Hope this helps!

**Comment by eman1986** [comment]
it did return a value: r3.3.3-255-gf93655d

**Comment by anorsich** [comment]
@eman1986 Which branch you are using? You should checkout to the `roboshell-v3.2`. For me it returns `r3.2.0-17-gde480c0`.

**Comment by eman1986** [comment]
![builderror](https://cloud.githubusercontent.com/assets/2343334/13153737/89a1b2e4-d643-11e5-8059-1165da726d81.png)

I grabbed the right repo and the branch you spoke of but I still get the same error.

**Comment by eman1986** [comment]
![build-err](https://cloud.githubusercontent.com/assets/2343334/13153913/595e7a76-d644-11e5-9af6-ff581b3c790e.png)

Sorry this one may be more accurate.

**Comment by eman1986** [comment]
so after playing around I got it working finally, my only question now is after I build robomongo where can I find the exe at?

**Comment by eman1986** [comment]
I got it all figured out, thank you so much for your help

**Comment by anorsich** [comment]
@eman1986 Awesome! Just curious what was the issue? Could you post it here? It can potentially help to the future readers. Thank you in advance!

**Comment by eman1986** [comment]
It was complaining about my version of mongo, in terms of not being able to know what version I had. Once I got it to know that it was all smooth from there.
