### ISSUE TITLE
Exceptions thrown in the shell are not reported any more (0.9.0-RC4)

### ISSUE THREAD

**Issue by adampridmore** [paralect/robomongo#1035]
As far as I can tell as of version 0.9.x runtime exceptions in the shell are not reported in the output pane.

### Example:
```
throw "Error";
```
### Output in Robomongo 0.8.5 (Windows 10)
```
uncaught exception: Error
```
### Output in Robomongo 0.9.0-RC4 (Windows 10)
Nothing!

### Notes
This is a slightly more realistic and less contrived example of a runtime exception, which is not reported in 0.9.0-RC4
```
var text = null;
text.toString();
````

**Comment by myaskevich** [comment]
Thanks Adam for reporting this issue.
We'll address that in the upcoming releases.
Max

**Comment by schetnikovich** [comment]
@adampridmore This issue is fixed and all errors are now reported to the output pane. This fix will be shipped with upcoming RC7 release. Thank you for reporting!

**Comment by juliashibalko** [comment]
@schetnikovich please, take a look at Windows version. Logs are shown correctly, but errors don't occur in the output http://prntscr.com/aa98rv (0.9RC7 under Win 10, 8.1, 7 x64)

**Comment by juliashibalko** [comment]
`>var testVar = null; testVar.toString();`
mongo shell has next error in output:  _2016-03-02T17:46:02.599+0300 E QUERY    [thread1] TypeError: testVar is null : @(shell):1:25_
robomongo shell output: _TypeError: testVar has no properties (shell):1_

**Comment by schetnikovich** [comment]
@juliashibalko Tested just now and it works for me. Seems that you received build without changes that were made to `robomongo-shell`. We will rebuild and ship updated build to you soon.

**Comment by schetnikovich** [comment]
@juliashibalko Does the latest build work for you on Windows?

**Comment by anorsich** [comment]
@schetnikovich I just checked the latest build on windows and it works as expected. I think we are ready to go.

**Comment by juliashibalko** [comment]
@schetnikovich works as expected under supported versions of Windows.
