### ISSUE TITLE
Robomongo 0.90-RC5 Cannot connect to MongoDB, Windows 10

### ISSUE THREAD

**Issue by IlyaMokin** [paralect/robomongo#1046]
![image](https://cloud.githubusercontent.com/assets/5592397/13467992/b5f3cdb4-e0b1-11e5-9921-34d19796bdd1.png)

mongod -v
![image](https://cloud.githubusercontent.com/assets/5592397/13467975/a29117ae-e0b1-11e5-9523-e52b7afc4cf1.png)

**Comment by juliashibalko** [comment]
Hi @IlyaMokin! This happens because of _mongod_ instance hasn't started according to logs attached above. Please restart one. Just in case I've checked - _--verbose_ option is working fine with Robomongo RC5.

**Comment by IlyaMokin** [comment]
:) I've attached log to show version of mongo. Mongo was started and MongoChef connected successfully, but robomongo can't

**Comment by juliashibalko** [comment]
@IlyaMokin Thank for details! Let us check once again. To help investigate issue, do you use only -v option while _mongod_ start? Could you please try 0.9RC4 to see if it has the same behavior?

**Comment by IlyaMokin** [comment]
@juliashibalko
> do you use only -v option while mongod start?

no, I've stopped before

>Could you please try 0.9RC4 to see if it has the same behavior?

I have the same behavior for RC4

**Comment by IlyaMokin** [comment]
http://screencast.com/t/YdYAzePde

**Comment by schetnikovich** [comment]
@IlyaMokin Am I correct that you can connect to your MongoDB instance using `mongo` shell with just this command:

    $ mongo

Also, any reasons you are using MongoDB 3.2.0 RC2, and not final version?

**Comment by IlyaMokin** [comment]
> Am I correct that you can connect to your MongoDB instance using mongo shell with just this command

I am using 'mongod --dbpath .....' command

But you are right, I've updated mongo to latest version(3.2.3) and it works fine now.

Thanks!

**Comment by schetnikovich** [comment]
You are welcome!
