### ISSUE TITLE
it doesnt display the full value for long numbers

### ISSUE THREAD

**Issue by lesterjanpearson** [paralect/robomongo#1050]
so i pulled db.currentOP();
and getting this:

"opid" : 9.55311e+008,
"connectionId" : 1.05608e+006,

how to display the full value?

**Comment by juliashibalko** [comment]
Hi @lesterjanpearson! Thanks for submitting issue. Could you please specify versions of Robomongo and MongoDB used?

**Comment by lesterjanpearson** [comment]
0.8.5, I recently download 0.9, hoping it gets fixed, but having problem transfering 0.8 config to 0.9. it doesnt work just copy paste.

**Comment by juliashibalko** [comment]
@lesterjanpearson Please let us know if it works for you with new 0.9 build. Will get you updates on config file soon.

**Comment by lesterjanpearson** [comment]
im back using 0.8.5 because some of my servers need ssh tunneling. anyway to get around the numbers not displaying full value?

**Comment by schetnikovich** [comment]
@lesterjanpearson This issue is fixed in 0.9 version of Robomongo. Today it is better to manually create SSH tunnel and use the latest version. Read [here](https://github.com/paralect/robomongo/issues/1008) about how to create such tunnels.  

Support for SSH is planned for next version.

**Comment by anorsich** [comment]
@lesterjanpearson Since the original issue has been fixed in most recent version and we have #1002 to track ssh support implementation, I am going to close this one. Feel free to reopen if you think we missed something.
