### ISSUE TITLE
use 0.8.5 config to the 0.9

### ISSUE THREAD

**Issue by lesterjanpearson** [paralect/robomongo#1051]
is there a way to use the config for 0.8 or older to the latest 0.9 version?

I tried copying the C:\Users\[ME]\.config\robomongo\robomongo.json

to the 0.9 folder but didnt work, no connections.

**Comment by schetnikovich** [comment]
Yes, just close Robomongo and copy file from:

    C:\Users\YourName\.config\robomongo\robomongo.json

To:

    C:\Users\YourName\.config\robomongo\0.9\robomongo.json

Run Robomongo.

**Comment by lesterjanpearson** [comment]
got it, was SSH removed on 0.9? now cant connect to my servers

**Comment by juliashibalko** [comment]
Support for SSH and SSL are our current priority for 0.9. We are working on SSH feature right now. Please use #1002 to track the progress on it.
