### ISSUE TITLE
Unable to build `robomongo-shell` on Windows 10 

### ISSUE THREAD

**Issue by dingzhengkai** [paralect/robomongo#1055]
Hi, people!

I followed the instructions in https://github.com/paralect/robomongo/blob/master/docs/BuildingRobomongoOnWindows.md 
and
https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source
to build my robomongo-shell.
The Prerequisites 1 need Visual Studio 2013 (i.e. MSVC12) Update 4 or newer,  and i use visual studio 2015 update 1.
Then I get the following error:
```
build\opt\mongo\util\version.cpp(78): fatal error C1001: Internal error occurred in the compiler.
(The compiler file “f:\dd\vctools\compiler\cxxfe\sl\p1\c\constexpr.h”，line 630 )
To solve this problem, please try to simplify or change the program near the  listed position above.

cl /Fobuild\opt\mongo\logger\log_component_settings.obj /c src\mongo\logger\log_component_settings.cpp /TP /nologo /EHsc /W3 /wd4355 /wd4800 /wd4267 /wd4244 /wd4290 /wd4068 /wd4351 /we4013 /we4099 /we4930 /Z7 /errorReport:none /MD /O2 /Oy- /Gw /Gy /Zc:inline /DPCRE_STATIC /DNDEBUG /DBOOST_ALL_NO_LIB /D_UNICODE /DUNICODE /D_CONSOLE /D_CRT_SECURE_NO_WARNINGS /D_WIN32_WINNT=0x0600 /DNTDDI_VERSION=0x06000000 /DBOOST_THREAD_VERSION=4 /DBOOST_THREAD_DONT_PROVIDE_VARIADIC_THREAD /DBOOST_SYSTEM_NO_DEPRECATED /DBOOST_THREAD_DONT_PROVIDE_INTERRUPTIONS /DBOOST_THREAD_HAS_NO_EINTR_BUG /Isrc\third_party\asio-asio-1-11-0\asio\include /Isrc\third_party\s2 /Isrc\third_party\pcre-8.37 /Isrc\third_party\boost-1.56.0 /Ibuild\opt /Isrc /Z7
scons: *** [build\opt\mongo\util\version.obj] Error 2
log_component_settings.cpp
scons: building terminated because of errors.
```

I see that you guys recommend the Visual Studio 2013 Update 5, and i  don't  know about cpp programming, anyone  can help? Thans!

**Comment by anorsich** [comment]
@dingzhengkai Thank you for reporting an issue. To get it going I would recommend you try to build Robomongo according to our requirements (VS 2013) on a brand you windows copy (or using a virtual machine). At some point, we for sure going to test builds on different windows versions, but we just have very few hand to do this at the moment.

**Comment by dingzhengkai** [comment]
@anorsich, thank you and all the other guys for the effort to make robomongo a amazing tool.
I'm not very skilled at programing, while it's  a pleasue for me to test these things.

**Comment by anorsich** [comment]
@dingzhengkai Thank you for the warm words! I just wondering if you were able to build Robomongo. Can I assist you in anyway?

**Comment by dingzhengkai** [comment]
@anorsich Thank you for help, last time i used Visual Studio 2013 update 5 to build my robomongo-shell, and finally it works.
But two days before, when i pulled the new code and to do the same thing,  i got the same error above. 
My procedure 
```
git clone https://github.com/paralect/robomongo-shell.git
cd robomongo-shell
git checkout roboshell-v3.2
bin\build.bat
```
Anyone can help?

**Comment by anorsich** [comment]
@dingzhengkai That sounds weird, since we haven't changed anything in Robomongo build process during last month. Mb you can post your error output once more to be sure, that issue the same.
Also you can probably try to clean code (`bin\clean.bat`) before building. In general, I would recommend keeping you build machine clean, just install all dependencies and you only for building Robomongo. 

I hope that helps.

**Comment by dingzhengkai** [comment]
Yesterday, i prepared a clean environment, and only install windows_10_version_1511_x64 and all the other dependencies, disable windows update, and it worked.
Since last month i built my robomongo successfully, I didn't  do anything on that machine, i think the problem was the "windows update", but i forgot to record the control panel's content, or it would be helpful for other guys.

**Comment by anorsich** [comment]
@dingzhengkai Thanks for sharing your results! This is great to know that it is possible to build Robomongo on Windows 10. We use Windows 8 at the moment. 
I am closing the issue for now.
