### ISSUE TITLE
Document limit not work in "aggregate" operation.

### ISSUE THREAD

**Issue by itlodge** [paralect/robomongo#1060]
I work with robomongo 0.9.0-RC6. However, there are at most 50 documents in an aggregation query. Is it a bug?

**Comment by myaskevich** [comment]
Hi @itlodge 
Did you notice a small Previous/Next button block? Guess what it's used for? ;)

![image](https://cloud.githubusercontent.com/assets/958221/13944577/3fa620d8-f017-11e5-8431-9b9b58ed68f4.png)

**Comment by itlodge** [comment]
@myaskevich ,  there is a small Previous/Next button when I perform "find", but not "aggregate" action.

**Comment by schetnikovich** [comment]
@itlodge, you are correct, this is a problem of all 0.9 versions of Robomongo. We will fix this with nearest new release. This problem is also reported here: #1058

**Comment by anorsich** [comment]
@schetnikovich / @itlodge Let's close this one as duplicated of #1058. @itlodge If you think your issue is different, feel free to reopen.

**Comment by schetnikovich** [comment]
@itlodge You may find it useful: we wrote about simple workaround that you can use to view all documents for `aggregate` query: #1058

**Comment by benevbright** [comment]
Why I'm still facing the same problem on 1.1.1?
