### ISSUE TITLE
OSX Edit/View Document Popup only opens on main display

### ISSUE THREAD

**Issue by ClarenceL** [paralect/robomongo#1063]
This wasn't an issue in earlier versions, but now when I try to edit documents on my external displays the edit dialog always pops up on my main display.

Tried assigning the app it to all windows from the dock too. Anyone else notice this?

**Comment by anorsich** [comment]
@ClarenceL Thank you for reporting this issue! I was able to replicate it on on El Capitan.

**Comment by anorsich** [comment]
@ClarenceL The issue has been fixed in the latest 0.9.0 RC8 release. We have tested it on El Capitain. There are a lot more notable things in this release and you can read more about it [here](http://blog.robomongo.org/robomongo-rc8/). Let us know if it worked for you!
