### ISSUE TITLE
Double '0.0' gets converted to Int32 '0' after editing

### ISSUE THREAD

**Issue by gvdelst** [paralect/robomongo#1069]
Using 0.9.0-RC7 with a Mongo 3.0.7 DB I insert the following document by using the "Insert Document" from right click on collection name.

`{
    "uuid" : "my-uuid",
    "test" : 0.2,
    "test2" : 0.0
}`

Then I click on "Edit document", decide not to change anything and notice that "0.0" gets converted to "0" (integer instead of double). After pressing Save the value is converted to Int32 type instead of Double type.
References : #622 #628 #429 

![1 after_insert](https://cloud.githubusercontent.com/assets/13745090/14207077/fcd424ea-f817-11e5-81e9-5b28be0876d6.PNG)
![2 edit_document](https://cloud.githubusercontent.com/assets/13745090/14207078/feafccf6-f817-11e5-9500-c4c6a053db2b.PNG)
![3 after_update__double_replaced_by_int32](https://cloud.githubusercontent.com/assets/13745090/14207079/00b2fdac-f818-11e5-9deb-69075edd3127.PNG)

**Comment by anorsich** [comment]
@gvdelst Thanks for reporting this issue! Looks like it were missed during our testing phase. We will work on it and get back to you as soon as it fixed.

**Comment by anorsich** [comment]
@yonatang The issue has been fixed in the latest 0.9.0 RC8 release. There are a lot more notable things in this release and you can read more about it [here](http://blog.robomongo.org/robomongo-rc8/). Let us know if it worked for you!
