### ISSUE TITLE
0.8.5 crashes on "drop collection" if a previous "drop collection" was not yet complete

### ISSUE THREAD

**Issue by zladuric** [paralect/robomongo#1070]
I am experiencing crashes on delayed commands.

I click on drop-collection on a remote server. While waiting for refresh, I click another one, robomongo then crashes.

I'm using 0.8.5 on Ubuntu 15.10 64bit. Anything else I can add?

**Comment by juliashibalko** [comment]
Hi @zladuric ! Thanks for reporting the issue. We recommend to use latest version 0.9.0-RC7, because it has fixes of several critical issues. 
If SSH/SSL feature is necessary for you, please track progress in #1002 task. SSH support is on the way and SSL would be a priority right after.

**Comment by zladuric** [comment]
Ok, thanks, I'll see if 0.9 works for me. I don't know if I should close the ticket, so I'll leave that to you.

**Comment by schetnikovich** [comment]
Hi @zladuric! I think we should try to reproduce this issue even with RC7. Upcoming release RC8, that is not released yet, contains several fixes related to connectivity. We found exact reasons of the Robomongo crash when we have network instability. Still it is possible, that your reported issue is not solved.

@zladuric, do you experience this problem each time you drop remote collection and open another one? 

@juliashibalko, please try to reproduce this issue with both Robomongo 0.8.5 and 0.9.0-RC7. I will check this issue at the code level soon.

**Comment by zladuric** [comment]
@schetnikovich 

On 0.8.5 it was repeatbale every time. If I've managed to click on "Drop collection" and open that dialog before the previous one got back to me, it would crash.

I couldn't get it to repeat on RC7. Still not sure if it's fixed or not because right now the previous collection dropping seems to finish much faster (and the re-render of the collections in the sidebar) so I don't have enough time to drop collection.

I'll check back here if I notice it again.

**Comment by juliashibalko** [comment]
@schetnikovich for 0.8.5 issue is reproduced with steps described above. For 0.9.7-RC I wasn't able to reproduce it with the same steps, but checked another case: while duplicating collection, drop the other one (but issue isn't reproduced permanently).
