### ISSUE TITLE
Latest Build does not have a SSH option

### ISSUE THREAD

**Issue by amitasthana** [paralect/robomongo#1071]
Latest Build does not have a SSH option. As it is clear by headline the latest version of Robomongo is not supporting the connection via SSH. Lot of developers use AWS and they would like to connect with online mongo instance, I am using some old version probably 0.8.4 or 0.8.3 which supports connecting the AWS via the pem file which is given at the time of making the cloud instance of AWS. I am using OS X El Captain. Before this I was using ubuntu and was working on 0.8.5 which has a option for SSH.

**Comment by IlyaDiallo** [comment]
See that issue: https://github.com/paralect/robomongo/issues/1002
