### ISSUE TITLE
Crash when "Copy JSON" an object within an array

### ISSUE THREAD

**Issue by yonatang** [paralect/robomongo#1074]
**Reproduce (using Robomongo 0.9.0-RC7, Mac):**
1. Create the following document:
```{ "_id":"example", "a" : [  {"first":"first"}, {"second":"second"}] }```
2. Show the document (```db.getCollection('test').find({"_id":"example"})```)
3. Right click on one of the elements in the array ```a``` and click "Copy JSON" (see screenshot attached)
![image](https://cloud.githubusercontent.com/assets/697449/14454169/b088aaf6-00a1-11e6-810d-21c08f87e850.png)

**Expected result:**
The object's string will appear in the clipboard

**Actual result:**
Robomongo crashes

**Comment by juliashibalko** [comment]
@yonatang Thanks for reporting the issue! I was able to reproduce it under Mac. We will work on it and get back to you as soon as it fixed.

**Comment by schetnikovich** [comment]
Hi @yonatang! Thank you for the excellent bug report! Your detailed information helped us to identify and quickly fix this problem. Fix will be available in the upcoming RC8 release, that you can expect by the end of this week.

Thank you!

**Comment by anorsich** [comment]
@yonatang The issue has been fixed in the latest 0.9.0 RC8 release. There are a lot more notable things in this release and you can read more about it [here](http://blog.robomongo.org/robomongo-rc8/). Let us know if it worked for you!

**Comment by yonatang** [comment]
Thanks! That's great. 
Perhaps you want to create a release tag for 0.9.0.RC8? That way I'll be sure I'm building the correct version.

**Comment by schetnikovich** [comment]
@yonatang Release was tagged with v0.9.0-rc8
