### ISSUE TITLE
robomongo config suddenly wipe

### ISSUE THREAD

**Issue by lesterjanpearson** [paralect/robomongo#1079]
When i woke up today and turn on pc, my robomongo config/connections are gone.

not sure why this happend.

**Comment by anorsich** [comment]
@lesterjanpearson 
I assume you recently update to the latest version of Robomongo. If that that case, starting from RC2 configuration file is located here:

`~/.config/robomongo/0.9/robomongo.json`

For RC1 and previous versions it was here:

`~/.config/robomongo/robomongo.json`

Just copy file to `0.9` folder and all your connections will be restored:

```sh
$ cp ~/.config/robomongo/robomongo.json ~/.config/robomongo/0.9/robomongo.json
```

We wrote about this change here: http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/

**Comment by juliashibalko** [comment]
@lesterjanpearson Could you please tell us if suggested solution listed above works for you? If so, seems that ticket can be closed. Thanks in advance!
