### ISSUE TITLE
Ability to recover lost queries

### ISSUE THREAD

**Issue by jaider** [paralect/robomongo#1081]
I was working, when suddenly the MongoDB Server went down and RoboMongo crashes. Immediately, I lost all the work(queries) I was doing in Robomongo.
It will be nice if I could recover those files/queries.

**Comment by schetnikovich** [comment]
@jaider Sorry for that! We are planning to maintain query log that will be stored on the file system. It will allow to restore all previous queries. 

Problem with crash is solved in Robomongo 0.9.0 RC8, that was released 8 days ago. This release will be available for download very soon.

**Comment by juliashibalko** [comment]
Hi @jaider! Thanks for reporting the issue! We will review this one, but to help us could you please specify versions of Robomongo and OS used?

**Comment by ckuethe** [comment]
@juliashibalko I'm not experiencing any crashes, but it would be nice to have my query logs available between sessions, like bash_history

**Comment by juliashibalko** [comment]
@jaider @ckuethe I'll close this ticket as duplicate, so let's track feature implementation progress within this card [Auto-save/Restore tabs #340 ](https://github.com/paralect/robomongo/issues/340). Thank you!
