### ISSUE TITLE
How do you connect to a replica set?

### ISSUE THREAD

**Issue by dottodot** [paralect/robomongo#1082]
I can connect to a single server fine but can't work out how to connect to a replica set. 

I've tried a comma seperated list i.e server1,server2,server3 but auth fails. 

I'm using 0.9.0-RC7 but can't find any docs

**Comment by juliashibalko** [comment]
Hi @dottodot! Unfortunately, feature "connect from URL" is in Open status for now - [Ability to add connections as standard MongoDB connection strings (URL) #600](https://github.com/paralect/robomongo/issues/600). We plan on adding this feature soon and will let you know when you can start using it. 
Now if you want to connect to Replica Set, you need to create single connection to each server (to master, to slave1,etc.) separately. 
Please let me know if you have any questions. Thanks!
