### ISSUE TITLE
0.9.0-RC7 crashes when dropping collection which was already dropped

### ISSUE THREAD

**Issue by zladuric** [paralect/robomongo#1085]
I've managed to open a "Drop collection" confirm dialog twice - the first time regularly and then the second time quickly before the remote server responded.

Basically, a similar thing to https://github.com/paralect/robomongo/issues/1070.

I've right-clicked a collection on a remote server, selected "Drop collection" and confirmed the dialog with "Y".
Then I quickly (kind of on purpose, because it was reported fixed) clicked the collection again and managed to open a "Drop collection" confirm dialog again. In the meantime, the underlying list of collections refreshed (removing the coll in question), but my dialog was already open.

And I clicked "Yes" again and Robomongo dissapeared.

I know it's an edge case and I kind of hunted for it specifically although I actually was manually dropping a bunch of temp collections. Not simple to reproduce because I'd have to probably kill my network bandwidth with something or really strain the remote server with this, but it's doable.

**Comment by anorsich** [comment]
@zladuric Thanks for reporting this! Let's see if will work on RC8, where we focused on a better error handling and fixed a lot of potential crash situations. That was the first big step to make Robomongo more stable and there is good chance that this issue has been fixed.

**Comment by juliashibalko** [comment]
Hi @zladuric! Could you please try to reproduce the issue using the latest Robomongo version 0.9.0-RC8? I didn't manage to replicate it, so seems that issue can be closed.

**Comment by zladuric** [comment]
Sorry it took a while to get around to this, I could not reproduce the isue so far. Running RC9 though.
