### ISSUE TITLE
application crashes

### ISSUE THREAD

**Issue by tacho87** [paralect/robomongo#1094]
Application crashes when remotely editing a json payload.

To reproduce:
1. Connect to a remote db (Should happen on local too, but its easier to reproduce with the network delay).
2. Edit a doc and update.
3. As soon as you update, click or move around the documents rows and watch the app crash (updating current data from server while editing or interacting old data on the client) 
* Table mode

**Comment by coolnalu** [comment]
same issue. as soon as i enter a character in the shell, it crashes.

**Comment by juliashibalko** [comment]
Hi @tacho87, @coolnalu. Thank you for reporting the problem! To help us with reproducing could you please share version of OS and version of Robomongo used?

**Comment by tacho87** [comment]
Hello @juliashibalko no problem. I used Robomongo 0.9.0-RC8 on OSX el capitan.

**Comment by juliashibalko** [comment]
@tacho87 thank you! I reproduced issue you have described. Seems that https://github.com/paralect/robomongo/issues/1087 is similar one. Let's track progress within mentioned card. We're working on the fix and will let you know on any updates.
