### ISSUE TITLE
Maintain column width in tabular results

### ISSUE THREAD

**Issue by ckuethe** [paralect/robomongo#1095]
Timestamps are particularly vulnerable to being set too narrow for the data they contain... an ISODate (2016-04-30 08:30:06.672Z) will default to displaying as "2016-..." Every time I refresh my search all the columns get narrow again even after I expand them.

Perhaps have a setting for default column width?

**Comment by ckuethe** [comment]
This seems somewhat related to #913

**Comment by juliashibalko** [comment]
@ckuethe thank you for reporting! You're absolutely right, these issues seem to be the same. So let me close this one as duplicate and offer you to track progress with #913 ticket
Feel free to reopen in case of any questions
