### ISSUE TITLE
Window size is not saved on Windows 10 x64

### ISSUE THREAD

**Issue by marcbaas** [paralect/robomongo#1097]
When resizing the main RoboMongo window size, closing the app and reopening it, it always resets to the default size (which is almost full screen on 1920x1080). It would be nice if the main window were to retain its last used size like all Windows apps do normally.

**Comment by simsekgokhan** [comment]
Hi @marcbaas, this feature has already been implemented in the next release Robomongo 0.9.0 RC9. We are planning to release it very soon. Best Regards.

**Comment by marcbaas** [comment]
Thanks man, looking forward for that.

**Comment by simsekgokhan** [comment]
No worries, it is our pleasure, it is RC 9 has been released by the way. I hope it will solve your problem.
