### ISSUE TITLE
remove does not works

### ISSUE THREAD

**Issue by julienfr112** [paralect/robomongo#1107]
db.getCollection('db').find({img:{$exists:false}}) works perfectly, and show some documents i want to delete.

but db.getCollection('db').remove({img:{$exists:false}}) does return Removed 0 record(s) in 70ms, not the expected results...

ps : robomongo 0.9.0-rc7 on ubuntu 14.04 amd64

**Comment by juliashibalko** [comment]
Hi @julienfr112. Thanks for reporting the issue! I tried to reproduce the issue with the same query - it works well for me. Could you please name MongoDB version (`db.version()`) and check some items before further investigation?
- Is collection capped? Documents can't be removed from capped collection. You could check this by using  `db.getCollection().stats()` query;
- If it's replica set, is this server primary member? Please use `rs.status` to see replica set's members.
- Is your user has readWrite role? (`db.getUser("<username>")`)

**Comment by julienfr112** [comment]
It was a replica set, i got usefull debug info with the mongo client.
Le 7 juin 2016 12:23 PM, "Julia Shibalko" <notifications@github.com> a
écrit :
