### ISSUE TITLE
Aggregate searches limited to 50 and unable to page

### ISSUE THREAD

**Issue by SuperSephy** [paralect/robomongo#1111]
It looks like "aggregate" searches don't trigger the pagination like "find" searches do. This result set should have 182 results, but only 50 are able to be shown (confirmed by using a suggestion from an old thread to raise the displayed result set limit). See image for details.

![sampleaggregateissue](https://cloud.githubusercontent.com/assets/6792723/16019198/951fc34e-315c-11e6-86d4-7d32b1954652.jpg)

**Comment by simsekgokhan** [comment]
Hi @SuperSephy, thanks for reporting the issue. We will try to reproduce and investigate the problem. Best Regards, Gokhan.

**Comment by juliashibalko** [comment]
Hi @SuperSephy. Issue is reproducible for me too and we will fix it in the next releases. As a workaround, until we will make it more convenient for users, you could use tips from the ticket https://github.com/paralect/robomongo/issues/1058. 
Also let me suggest you to track fixing progress with the same https://github.com/paralect/robomongo/issues/1058 card. So I will close current ticket as duplicate if you don't mind.
