### ISSUE TITLE
Add shortcut key combination for refresh

### ISSUE THREAD

**Issue by brunoais** [paralect/robomongo#1112]
Please add a shortcut key to refresh the thing that is selected either be a database or a collection or just a single BSON document.
Recommended shortcut combo. Ctrl + R

**Context:**
As part of the development while using MongoDB requires doing stuff in the code being developed that uses MongoDB and then go and check if it was actually done in MongoDB.
Additionally, most of the times, there's also the need to undo whatever was done it directly in MongoDB.

**Comment by juliashibalko** [comment]
Hi @brunoais! Thank you for suggestion. We have the same request submitted earlier, so let me offer you to track progress with this ticket [Refresh feature (add shortcut key) in Explorer](https://github.com/paralect/robomongo/issues/822). We will get back to you as feature's ready!

**Comment by brunoais** [comment]
Ups. I didn't notice the other issue was also related to a shortcut key. Sorry about that

**Comment by juliashibalko** [comment]
@brunoais No problem, it's okay!
