### ISSUE TITLE
What is used for robomongo website

### ISSUE THREAD

**Issue by eMahtab** [paralect/robomongo#1117]
I loved robomongo website, can someone tell me what is used as the frond end. Those charts look gorgeaous , what is used to create those svg charts. Please tell, I will like to use them in my projects

**Comment by schetnikovich** [comment]
@eMahtab, we use D3 framework for animation and data-driven creation of SVG primitives. Besides this there are no additional frameworks. Check [their site](https://d3js.org/) to get even more inspiration :)

**Comment by juliashibalko** [comment]
I'm closing the ticket as solved. Please feel free to re-open it.
