### ISSUE TITLE
Network Unreachable When Connecting to AWS EC2

### ISSUE THREAD

**Issue by artforlife** [paralect/robomongo#1118]
I had Robomongo 0.9 installed and was having a difficulty connecting to a remote database on AWS EC2. The authentication would fail on the second step (seemingly, user authorization).

In trying to fix that, I updated to the most recent 0.9.0-RC9 version. Now, the connection fails at the first step, returning "Network is unreachable" error. That said, the database is running on that server as I have a beta app there and am able to use it successfully.

Am I doing something wrong or is there a bug of some sort that causes this?

**Comment by simsekgokhan** [comment]
Hi @artforlife, thanks for your interest in Robomongo. 
Please see a working example, here the cloud service is Compose.io
Can you give a bit more information about your setup, which cloud service are you using?

![screenhunter_13 jul 06 11 36](https://cloud.githubusercontent.com/assets/19390749/16645532/392a78ca-442d-11e6-920d-6fe0ecb27c5a.jpg)

![screenhunter_14 jul 06 11 36](https://cloud.githubusercontent.com/assets/19390749/16645537/44874ad6-442d-11e6-8d1c-780ef89bbb9f.jpg)

**Comment by artforlife** [comment]
I am using a basic AWS EC2 with MEAN stack installed. Everything works on it. I even have a running application that uses that DB. Perhaps there are some Linux settings I am missing?

Let me know if you want to see any log files.

**Comment by knigal** [comment]
+1 I seem to be bumping against this problem on Compose.io with a MongoDB 3.2.8 deployment

**Comment by simsekgokhan** [comment]
Hi @knigal , thanks for reporting the problem. Yes, would be great if you can provide details how to reproduce. We will try to reproduce and investigate the problem.

@artforlife We are very sorry for the delay, we have been snowed under with preparing new Robomongo release with SSL. We will test AWS as soon as we do new release. Note: It will be possible to use brand new & official cloud service "MongoDB Atlas" with new Robomongo 0.9.0 RC10 - planning to release in a week. Log files would be awesome.

**Comment by knigal** [comment]
On my end this ended up being an SSL issue. When I tried to connect using MongoChef it also failed, but it connected when I enabled the "Use SSL Protocol to Connect" option.

I looked for a similar option in Robomongo but couldn't find one. It's my understanding that Robomongo SSL support is on the roadmap (?)

Anyway, last note here is that although Compose.io creates 3.2.x deployments with SSL enabled by default, during deployment creation it allows to uncheck the SSL option. One can create a mongdb 3.2.8 deployment w/o SSL and connect using Robomongo (confirmed)

**Comment by simsekgokhan** [comment]
@knigal Yes, development and internal testing of Robomongo with SSL have finished, we are now making final touches before release. In addition to SSL, new Robomongo comes with High DPI Support and Mongo Atlas support. Details here: [Milestone: Robomongo 0.9.0 RC10](https://github.com/paralect/robomongo/milestone/14)

**Comment by knigal** [comment]
@simsekgokhan these are great news, thanks!
I see RC10 should have SSL, is this correct? 
Also, it will help to know it's release ETA. Can I keep track of it anywhere?

**Comment by artforlife** [comment]
Thanks to all involved. If this could get fixed, it would truly make Robomongo a much more valuable software. I would love to tweak my production DB from my local machine.

@knigal Could you give any tips on how you fixed the SSL and got it to work?

**Comment by knigal** [comment]
@artforlife I didn't get SSL working with Robomongo (yet). See my previous post in this thread

**Comment by simsekgokhan** [comment]
@knigal 
Yes, RC10 will have SSL. We plan to release today or on monday. 
New releases are announced on our twitter: https://twitter.com/Robomongo

**Comment by simsekgokhan** [comment]
New Robomongo with SSL support has been released. Please see also other features of the new release in our blog: http://blog.robomongo.org/robomongo-rc10/ - https://robomongo.org/download

**Comment by simsekgokhan** [comment]
@artforlife AWS EC2 investigation has been started.

**Comment by juliashibalko** [comment]
@artforlife Could you please specify Linux version running on your EC2 instance? That'd help us a lot with replicating. Thanks in advance!

**Comment by artforlife** [comment]
When I run the `uname -or` command I get the following back: 

> 4.4.14-24.50.amzn1.x86_64 GNU/Linux

In my AWS panel, it appears as the basic t2.micro type of EC2 instance.
Let me know if this helps or I need to do something else.

**Comment by artforlife** [comment]
I would like to let everyone know that I was able to get the new Robomongo RC10 to connect to my EC2 through SSH. At this point I am unsure whether it had to do solely with the update to RC10 or the settings I had changed. 

Here is what I did:

<img width="549" alt="screen shot 2016-09-09 at 11 27 09 am" src="https://cloud.githubusercontent.com/assets/8064423/18392934/9d6de7c8-7681-11e6-9611-fab4bdccabc6.png">
<img width="551" alt="screen shot 2016-09-09 at 11 27 18 am" src="https://cloud.githubusercontent.com/assets/8064423/18392933/9d6ca62e-7681-11e6-92e0-a64df61b67e0.png">
<img width="553" alt="screen shot 2016-09-09 at 11 27 27 am" src="https://cloud.githubusercontent.com/assets/8064423/18392932/9d6c661e-7681-11e6-8f6d-93e10d007d24.png">

**Comment by simsekgokhan** [comment]
@artforlife Great to hear it works. We have updated OpenSSL library in RC10. That might have an effect on solution.

**Comment by juliashibalko** [comment]
Hi @knigal! Could you please check if your connection is established with new Robomongo version RC10 so we can close the ticket? All release details are described [in the blog](http://blog.robomongo.org/robomongo-rc10/). 
Thanks in advance!

**Comment by knigal** [comment]
@juliashibalko atm I don't have access to the ssl-enabled db, so it's difficult to confirm. That being said, I have no reason to believe that there's still a problem

**Comment by juliashibalko** [comment]
@knigal Thanks a lot! I will close this ticket as fixed. Anyway please feel free to reopen in any case.
