### ISSUE TITLE
0.9-RC8+ silently stops script when inserting in loop

### ISSUE THREAD

**Issue by oschrenk** [paralect/robomongo#1119]
I have a small migration script that basically transforms a bit of data from one collection and pumps it one by one into a different collection. 

With 0.9-RC7 this script inserts all documents, starting with 0.9-RC8 this script fails silently. Most of the times it stops at around 128 insertions.

```
// we are only interested in signups less than ~3 months
var cursor = db.things.find({});

function insert(item) {
  // transform things
  // ... removed code ...

  var result = db.differentthings.insert({
    "request": item
  }, {"w":1});
  print("done");

  return result;
};

cursor.forEach( function(item) {
  try {
    insert(item);
  } catch(err) {
    print(err);
  }
});
```

Sample output from execution

```
...
Inserted 1 record(s) in 107ms
done
Inserted 1 record(s) in 112ms
done
```

It even prints `done`. So insertion works but I know for sure that cursor is not exhausted.

**Comment by juliashibalko** [comment]
Hi @oschrenk, thank you for reporting! I was able to reproduce it. We will fix it in the nearest releases, but let me offer you to track progress with this ticket [#1106 Scripts end prematurely and randomly when using loop](https://github.com/paralect/robomongo/issues/1106)
Feel free to reopen in case of any questions. We will get back to you as issue'll be fixed.
