### ISSUE TITLE
ELF : not found Ubuntu 12.04 LTS 32 bit

### ISSUE THREAD

**Issue by keerthivasan-r** [paralect/robomongo#1120]
Hi,
I am trying to install in Ubuntu 12.04 LTS precise 32 bit, I have downloaded the .tar and extracted. When i try to execute robomongo binary in the bin directory. It throws below error with encoding, not sure what is the problem? Can anyone guide me? 
```
/usr/local/bin/robomongo: 1: /usr/local/bin/robomongo: ELF: not found
/usr/local/bin/robomongo: 2: /usr/local/bin/robomongo: Syntax error: ")" unexpected
keerthivasan@Keerthi-PC: file --mime robomongo 
robomongo: application/x-executable; charset=binary
keerthivasan@Keerthi-PC: file --mime qt.conf 
qt.conf: text/plain; charset=us-ascii
keerthivasan@Keerthi-PC: tr -d \\000-\\177 < qt.conf | wc -c
0
```

**Comment by juliashibalko** [comment]
Hi @keerthivasan-r, thank you for reporting us!
Unfortunately, there is no 32-bit version of [Robomongo](https://github.com/paralect/robomongo#supported-platforms) available at the moment. The main reason for that is that MongoDB itself [stopped supporting 32-bit versions](https://docs.mongodb.com/manual/installation/#deprecation-of-32-bit-versions). That would be quite a big effort to bring support for 32-bit versions back to MongoDB shell and require decent amount of work from our side for every new version of MongoDB. 
I'll close the issue,but please fell free to reopen it in any case.
