### ISSUE TITLE
Save coulmn widths and batch size

### ISSUE THREAD

**Issue by lastochkin** [paralect/robomongo#1123]
Every time when I press "Run query" button the grid columns width are reset to their default values and so is the batch size (amount of rows to fetch from DB). It would be nice to memorize those values at least untill the tab is closed.

**Comment by juliashibalko** [comment]
@lastochkin thank you for reporting. You're absolutely right, that's a good suggestion! But let me offer you to track progress with [#333 Remember width of column in table mode for view during paging and queries](https://github.com/paralect/robomongo/issues/333) ticket and close current as duplicate. We will let you know on any news!
Feel free to reopen in case of any questions
