### ISSUE TITLE
Search didn"t work in RoboMongo but work in shell

### ISSUE THREAD

**Issue by Yoraphael** [paralect/robomongo#1130]
Hello robo ! 

 I want to made a search in robomongo, by example : db.people.find({"family_name":"SUTTER"})

and each time I did that, I have this message : Script executed successfully but there is no results to show

The samle search works perfectly in command line in my mongo shell.

Any idea why ? 

My database is on digital ocean and I import it in command line. 

Thanks

Raphael

**Comment by giannicic** [comment]
Maybe is just a stupid answer but, is it possible that some values in the db are in lower case?
If you run `db.people.find({"family_name": new RegEx("SUTTER","i")}) ` is there the same result?

**Comment by juliashibalko** [comment]
Hi @Yoraphael! Let me suggest you to check workaround described in the ticket https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348 (increase `shellTimeoutSec` value) . I believe this should help and search should be executed successfully with results listed.

**Comment by juliashibalko** [comment]
@Yoraphael I manage to replicate your problem and solution from https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348 solves it. So I will close this issue (you could track progress within #1106 card) but please feel free to re-open or create new ticket. Hope workaround help you, thanks!
