### ISSUE TITLE
Robomongo stops other queries from running while one is still running

### ISSUE THREAD

**Issue by LeeSingFanda** [paralect/robomongo#1135]
If a query is currently running in Robomongo, there is no way to kick off another query, even though the query might be targeting in a different MongoDB instance. 

I think this should be allowed.

**Comment by juliashibalko** [comment]
@LeeSingFanda thank you for reporting! This is a known issue and you can read more about it here: http://blog.robomongo.org/mongodb-shell-integration/. In short, only one query can be executed over embedded MongoDB shell at a time. All subsequent queries will wait in the queue. MongoDB shell wasn’t designed to support parallel execution of queries. We have solution for this problem and it will be implemented after we complete few major features.

**Comment by juliashibalko** [comment]
@LeeSingFanda I will close the ticket if you don't mind. In any case feel free to reopen or create new one.

**Comment by simsekgokhan** [comment]
@LeeSingFanda
It is possible to subscribe to updates about this feauture from the following ticket: 
#1161 Feature: Robomongo to support execution of multiple simultaneous queries
