### ISSUE TITLE
Robomongo closes cursor when reaching batch size (by default 101)

### ISSUE THREAD

**Issue by cristian-vertiz-tierconnect-com** [paralect/robomongo#1139]
Robomongo closes cursor when reaching batch size (by default 101)

by example:
var a = db.myCollection1.find({"field": "value"}).forEach(function(x){
    print(x.serialNumber) 
});
var b = db.myCollection2.find({"field": "value"}).forEach(function(x){
       print(x.serialNumber) 
});

prints 101 docs for each query

NOTE: It works as expected in RC7 but not in RC9 (not  tested in RC8)

**Comment by juliashibalko** [comment]
@cristian-vertiz-tierconnect-com thank you for reporting! Let us try to reproduce the issue and we will get you back on any updates.

**Comment by giannicic** [comment]
Just experienced the same issue now. 
It's related to the shellTimeoutSec  https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348

**Comment by juliashibalko** [comment]
@cristian-vertiz-tierconnect-com I can confirm that workaround from https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348 will solve the problem. So let me suggest to track issue progress with #1106 (comment). I will close this one but please feel free to reopen or create new ticket. 
Hope workaround will help you, thanks!
