### ISSUE TITLE
Basic Connection to Mongo Atlas

### ISSUE THREAD

**Issue by fchengpc** [paralect/robomongo#1140]
Does anyone know the basic config setup to connect to mongo atlas?

**Comment by mjmasn** [comment]
Robomongo doesn't support SSL yet, although it will be released soon according to https://github.com/paralect/robomongo/issues/1002#issuecomment-234460826. I don't think you can turn off SSL in Atlas. When SSL support is released, make sure you add your IP address to the Atlas whitelist too :)

**Comment by fchengpc** [comment]
@mjmasn, thank you very much for the info. 
Yeah been trying turn off SSL in Atlas, no luck.

**Comment by simsekgokhan** [comment]
Hi @fchengpc, if you want to try beta SSL-Robomongo with Atlas, we will be happy. You can send beta request email in the previously referenced comment. - Warm Regards, Robomongo Team

**Comment by helton-souza-labdoor** [comment]
Any news in the release with SSL?

**Comment by fchengpc** [comment]
sry @simsekgokhan, I was got pull to different project. yeah, I would like to try beta. What does it the beta. Will send email. thxs

**Comment by simsekgokhan** [comment]
Hey guys, we have completed internal testing, we plan to release on this friday or at the beginning of next week. We will respond to beta request email.

**Comment by simsekgokhan** [comment]
New Robomongo with SSL support has been released. 

Please see new features and an example "how to connect to Mongo Atlas" in our blog (section 2): http://blog.robomongo.org/robomongo-rc10/ 

Download:
https://robomongo.org/download

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed. In any case please feel free to create new ticket in any case. Thank you!

**Comment by fchengpc** [comment]
Thank you guys for all the hard work.
