### ISSUE TITLE
Edit document always in main screen

### ISSUE THREAD

**Issue by equero** [paralect/robomongo#1144]
I have two screens, the laptop screen ( main ) and my second screen ( Robomongo opened here).

When i edit a document, the edit window, always is opened in the laptop screen instead the robomongo app is showing

Robomongo 0.9.0-RC7

**Comment by juliashibalko** [comment]
Hi @equero, thank you for reporting! Could you please try to reproduce the issue with the latest Robomongo version RC9 if you have some free minutes? I have tested with RC9 under Mac OS X 10.11 and didn't manage to replicate it. Thanks a lot!

**Comment by equero** [comment]
thx @juliashibalko i could confirm you that the bug is completely solved in Robomongo 0.9.0-RC9 and Robomongo 0.9.0-RC8

The Robomongo 0.9.0-RC7 version is the one with the problem

Thx for your help.

Greetings

**Comment by juliashibalko** [comment]
@equero Happy to hear that! You are always welcome. Closing ticket as fixed. 
Thank you!
