### ISSUE TITLE
Error: Unable to parse JSON

### ISSUE THREAD

**Issue by arturmelanchyk** [paralect/robomongo#1165]
Robomongo version: 0.9.0-RC9
System: MacOSX 10.11.6

I have some documents in collection. When I try to edit some document (simply edit-> save even without any modifications) [Robomongo throws this exception](https://s4.postimg.org/b695w5fv1/Screen_Shot_2016_08_22_at_12_04_14_PM.png). This is critical bug which makes Robomongo absolutely useless for me

**Comment by juliashibalko** [comment]
@arturmelanchyk thanks for reporting! It's known issue, so let me suggest to check workaround mentioned in https://github.com/paralect/robomongo/issues/912#issuecomment-179054217. I believe it will solve the problem.
I am closing this ticket as duplicate of #912. Let's keep progress there.
