### ISSUE TITLE
Script executed successfully, but there are no results to show

### ISSUE THREAD

**Issue by leifengfeng** [paralect/robomongo#1169]
db.hbase_tags_0824_2227.count()
25920026
db.hbase_tags_0824_2227.count({tag:/^axg[0-9]$/})
0
db.hbase_tags_0824_2227.count({tag:/^a[0-9]$/})
10
db.hbase_tags_0824_2227.count({tag:/^[0-9]$/})
Script executed successfully, but there are no results to show
db.hbase_tags_0824_2227.count({tag:/^[0-9]+$/})
Script executed successfully, but there are no results to show
db.hbase_tags_0824_2227.count({tag:/^9[0-9]+$/})
4633

![image](https://cloud.githubusercontent.com/assets/6386776/17955649/4dcb725c-6ab6-11e6-8cd7-2dda5e3be9c0.png)

**Comment by juliashibalko** [comment]
Hi @leifengfeng, thank you for reporting! It's one of known issues, so let me suggest you to check workaround described in the next comment https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348.
I believe this will solve your problem. 
I'm closing the ticket as duplicate, but anyway please feel free to reopen the ticket. Thanks!
