### ISSUE TITLE
insert data [missing] 

### ISSUE THREAD

**Issue by playcodebyflapjack** [paralect/robomongo#1174]
hello eveny one ...
I am just learning mongo tool 
I have a problem about insert data into collection

I'm inserted data about 100,000 rows but when i use count query the result not match 100,000 rows
I want to know the problem

This is scripte insert
[https://drive.google.com/file/d/0B4XQXKz8Z1RWMFBPQkhxLXFQdGM/view?usp=sharing](url)

when  I run query  `db.getCollection('persontest').find({}).count()`  I got the result as below:
![datamissmongodb](https://cloud.githubusercontent.com/assets/6084576/18041017/57c971de-6dde-11e6-809e-bba3b659b08c.png)

**Comment by playcodebyflapjack** [comment]
I solve problems
this link
[https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348](url)
thx ^^''

**Comment by juliashibalko** [comment]
Glad hear it solved. I'm closing the issue, please feel free to reopen.
