### ISSUE TITLE
Can't edit/delete collection or documents [solved]

### ISSUE THREAD

**Issue by HaraldBregu** [paralect/robomongo#1179]
I'm using Mongodb Atlas and the connection with Robomongo is ok, but the problem is that i'm able to create or delete databases but not collections or documents. 
I'm authenticated to the database as admin with Read and Write to any database. What can i do?

**Comment by simsekgokhan** [comment]
@HaraldBregu 
Thanks a lot for your interest in Robomongo. We have just did a quick test, it works for us. 

The problem seems to us related to permissions, we suggest to double check users, roles and permissions. Also please make sure you are connected to primary node one more time. 

<img src="https://cloud.githubusercontent.com/assets/19390749/18342354/23cf1740-75b7-11e6-8bf7-076f8320e605.jpg" width="500" />


Please also see screenshots from a working example:

<img src="https://cloud.githubusercontent.com/assets/19390749/18342663/9d9e105c-75b8-11e6-85f7-14a4e03deff3.jpg" width="400" />

<img src="https://cloud.githubusercontent.com/assets/19390749/18342681/b270577e-75b8-11e6-803b-76df00eaa42d.jpg" width="400" />

**Comment by HaraldBregu** [comment]
@simsekgokhan i did exactly as you suggested, i created a new user with atlasAdmin Role in Atlas dashboard and than connected, but still cant delete or edit any document and collection. I can do it just from shell terminal.

<img width="550" alt="schermata 2016-09-08 alle 11 03 01" src="https://cloud.githubusercontent.com/assets/1328379/18343628/7bcfd982-75b4-11e6-8da0-c00e4e9a1290.png">

<img width="558" alt="schermata 2016-09-08 alle 11 03 14" src="https://cloud.githubusercontent.com/assets/1328379/18343640/8ceeac48-75b4-11e6-9a8c-4fdd4fc1fad3.png">

<img width="550" alt="schermata 2016-09-08 alle 11 03 23" src="https://cloud.githubusercontent.com/assets/1328379/18343664/9fd8be84-75b4-11e6-9789-f0e4f8ca1810.png">

<img width="546" alt="schermata 2016-09-08 alle 11 03 29" src="https://cloud.githubusercontent.com/assets/1328379/18343686/abb88a54-75b4-11e6-9b61-87ddb08453a2.png">

<img width="547" alt="schermata 2016-09-08 alle 11 03 35" src="https://cloud.githubusercontent.com/assets/1328379/18343695/b2774fb0-75b4-11e6-88d2-96ebff324bb6.png">

// Cant do anything here.....

<img width="664" alt="schermata 2016-09-08 alle 11 04 48" src="https://cloud.githubusercontent.com/assets/1328379/18343702/b8c93612-75b4-11e6-9dec-571723a5782c.png">

**Comment by HaraldBregu** [comment]
When trying to update i have this error:

<img width="521" alt="schermata 2016-09-08 alle 11 11 34" src="https://cloud.githubusercontent.com/assets/1328379/18343792/16933f04-75b5-11e6-821f-a814daa696f7.png">

**Comment by HaraldBregu** [comment]
@simsekgokhan i was not using the primary node from the cluster. 
Now it work perfectly, thanks to the last error i found the solution.
Thank you

**Comment by simsekgokhan** [comment]
Exactly, I was just writing that you are not connecting to primary.
Great that it works.

Support for Replica Sets is under development to be included in the next or the following release, which connects to primary automatically. This kind of problems will not exist in the future hopefully.

You can follow the latest releases and news here: 
https://twitter.com/Robomongo

**Comment by juliashibalko** [comment]
Closing as solved

**Comment by Wilopez95** [comment]
Hello friends, I am having the same problem here, I see that maybe they could help me, I have read the solution and I understand that the problem may be that I am not using the primary node, however I am not sure that it is exactly the primary node, Could you help me tell me what it is or how I change it ...?

**Comment by rotimi-best** [comment]
> i was not using the primary node from the cluster.

In case anyone else didn't understand what he meant by this. It also took me a while to find the primary cluster. Here is a screenshot. Copy the long string that starts with `cluster0` and place it into the `Address` field in Robomongo's connection interface.

![connnection_to_primary_cluster_mongoatlas](https://user-images.githubusercontent.com/31730715/67887367-cce61980-fb53-11e9-8c0f-80a71c59e36b.png)
