### ISSUE TITLE
SSL Tunnel Failure

### ISSUE THREAD

**Issue by HaraldBregu** [paralect/robomongo#1186]
I don't know why, but it seems that does not want to connect anymore. How can i fix this now?

<img width="510" alt="schermata 2016-09-16 alle 08 54 09" src="https://cloud.githubusercontent.com/assets/1328379/18577667/7a3ce078-7beb-11e6-9b7a-34fcf5e1b950.png">

**Comment by HaraldBregu** [comment]
I can connect the mongolab with no errors but not mongodb atlas.

**Comment by HaraldBregu** [comment]
The problem war the IP address to reset in Mongodb Atlas, i changed with mine and it is working now

**Comment by simsekgokhan** [comment]
Hi @HaraldBregu , thanks a lot for your interest in Robomongo. Great to hear it works :)

**Comment by qaispak** [comment]
I have included my current IP address but am still getting this error. Any thoughts?

**Comment by CagataySert** [comment]
I had save problem and I have  solved the problem with reset api as well. Thank you to share your solution :) It helped me a lot!
