### ISSUE TITLE
New Feature: Full Screen Query Editor (Dockable Output Window)

### ISSUE THREAD

**Issue by simsekgokhan** [paralect/robomongo#1187]
Some screenshots from new feature.

![screenhunter_48 sep 16 13 28](https://cloud.githubusercontent.com/assets/19390749/18583164/8cabec24-7c11-11e6-8c2f-5af3d3b9904e.jpg)

![screenhunter_49 sep 16 13 29](https://cloud.githubusercontent.com/assets/19390749/18583192/af33baba-7c11-11e6-8510-e3f03c0da772.jpg)

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed. In any case please feel free to create new ticket. Thank you!
