### ISSUE TITLE
Putty SSH'd to a Vagrant CentOS6.5 machine

### ISSUE THREAD

**Issue by Nebojsaa** [paralect/robomongo#1188]
Vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/Users/nebojsa/.vagrant.d/boxes/richdynamix-VAGRANTSLASH-magestead-centos65-nginx-php56/1.0.2/virtualbox/vagrant_private_key
  IdentitiesOnly yes
  LogLevel FATAL

Then I go in putty and add all of those fields
![unbenannt](https://cloud.githubusercontent.com/assets/3692864/18600909/5bac58d0-7c60-11e6-95a0-f724c42b093d.PNG)
This is my vagrant_private_key
![unbenannt1](https://cloud.githubusercontent.com/assets/3692864/18600917/664973f4-7c60-11e6-9feb-a0845cf4ea8c.PNG)
And mostly important -- 
![unbenannt2](https://cloud.githubusercontent.com/assets/3692864/18600941/820151f2-7c60-11e6-9e79-a4dfba172086.PNG)

I have even tried as passwords in Putty 'vagrant' and it says access denied. 
I don't know what the password is. 
What am I doing wrong ?

**Comment by simsekgokhan** [comment]
Hi @Nebojsaa , can you tell us the connection between Robomongo and what you are trying to finally achieve? At first glance, I'd suggest to copy the file different location & retry and verify the file content (if it really contains SSH private key format).

**Comment by Nebojsaa** [comment]
It doesn't have anything with Robomongo. I have put it in here mistakenly.
