### ISSUE TITLE
export data as csv

### ISSUE THREAD

**Issue by prabhatsharma** [paralect/robomongo#1193]
feature - ability to export result of the query as csv

**Comment by juliashibalko** [comment]
Hi @prabhatsharma! Thanks a lot for request. This feature has already been included into our to-do list. But let me suggest you to track implementation progress within this card [#348 Export to csv](https://github.com/paralect/robomongo/issues/348). I'll close this one as duplicate. Thank you!

**Comment by prabhatsharma** [comment]
Thank you. Appreciate it.

Regards,
Prabhat
+1.972.445.7205
http://www.linkedin.com/in/hiprabhat
