### ISSUE TITLE
Do not rescale columns after document deletion in table view

### ISSUE THREAD

**Issue by adammichalik** [paralect/robomongo#1211]
Robomongo 0.9.0-RC10

When viewing the query results in table mode, I right-click on an item and use "Delete document". After the deletion, the table is refreshed, but if I adjusted columns width, they are now scaled back to the default width.

**Comment by juliashibalko** [comment]
@adammichalik thank you for reporting! This enhancement has been added to our wish-list. So it will be fixed in further releases. 
Let me suggest to track progress within https://github.com/paralect/robomongo/issues/913 card. I'm closing this one as duplicate but feel free to reopen in any case.
