### ISSUE TITLE
regex queries are not working properly

### ISSUE THREAD

**Issue by ismetozalp** [paralect/robomongo#1214]
Hi
reqex queries seems to have problem,
let there be logs collection and a document like this in it.

{
    "_id" : ObjectId("56cac81e0a975a255f2f1bd8"),
    "a" : "ac",
    "l" : "I",
    "t" : ISODate("2016-02-22T08:34:38.488Z"),
    "r" : "7062064496895063770",
    "i" : "94.70.255.145",
    "e" : "",
    "n" : "",
    "c" : "RequestFilter",
    "f" : "doFilter",
    "m" : "[REQUEST START] $ http://app3.navatom.com/alarga.accounts/alarga.accounts.nocache.js"
}

db.getCollection('logs').find({m: /app3.navatom.com/}); this query returns no result in robomongo 0.9.0 

but when i connect to server with "mongo" and run the same query i got results.

however,
db.getCollection('logs').find({m: /app3/});

this works in robomongo seems to be there is problem with the dots.

Thanks!

**Comment by juliashibalko** [comment]
Hi @ismetozalp, thank you for reporting! I try to replicate issue, but it works fine for me. So we will continue investigation.
But if you have rather large collection let me suggest you to check workaround described here https://github.com/paralect/robomongo/issues/1106#issuecomment-230258348. In short you can increase value of `shellTimeoutSec` in config file and then run query again. Please let me know if it works for you!

**Comment by ismetozalp** [comment]
Hi Julia,
After increasing the timeout everything seems fine thanks!
