### ISSUE TITLE
db.getCollection('collection').updateMany() causes error

### ISSUE THREAD

**Issue by thammadi** [paralect/robomongo#1215]
Dot the following causes error:
db.getCollection('collection').updateMany(
      { field1: "somevalue" },
      { $set: { "field2" : true } }
   );

**Error:** TypeError: err.hasWriteErrors is not a function

**Comment by thammadi** [comment]
My bad, this is a false issue.

I'm using a replica set and noticed that the replica I was using to run update, was not primary. Hence, the error.

I ran the script in a new shell from primary server and it works.

**Comment by simsekgokhan** [comment]
Hi @thammadi , glad to hear it works :) 
Fyi, support for replica sets is under development and with this feature Robomongo will automatically connect to primary node. We plan to include replica set feature in the next release. (hopefully export/import feature as well)

You can follow related updates here: https://github.com/paralect/robomongo/issues/116#issuecomment-250784228 or on twitter: https://twitter.com/Robomongo

I am closing this ticket, feel free to re-open or create a new ticket if you have any issues.
Warm Regards from Robomongo Team

**Comment by WegDamit** [comment]
as it was the first hit: for me it was a permission problem. Seems it need some more permission to even write the correct error message to ... as the the actual user had.
