### ISSUE TITLE
MongoDB Shell was not initialized robomongo

### ISSUE THREAD

**Issue by imkratos** [paralect/robomongo#1219]
on mac os sierra system, open it show the message "MongoDB Shell was not initialized robomongo".
i try reinstall ,but is not work.
version:Robomongo 0.9.0-RC8

**Comment by juliashibalko** [comment]
@imkratos thanks a lot for reporting. We are sorry for that!
Could you please share error screenshot? Also any info about your host OS, remote server OS, MongoDB version is very helpful.
Btw usually I see the same error when my server with MongoDB is down and I'm trying to execute any query in shell.
![image](https://cloud.githubusercontent.com/assets/16773195/19652099/3d4fb5dc-9a18-11e6-91f6-adcf623009a1.png)

**Comment by imkratos** [comment]
@juliashibalko i think mybe is network is unstable，one day after it's worked. thank you very much.nexttime i will report my server detaile .whatever thanks.

**Comment by harukaeru** [comment]
Same here. But I solved this.

In my case, I open another client on the terminal.
So MongoDB Shell cannot be initialized.

That's why I shutdown the client and re-connect through Robomongo and it works well.

**Comment by yiruocici** [comment]
> Same here. But I solved this.
> 
> In my case, I open another client on a terminal.
> So MongoDB Shell cannot be initialized.
> 
> That's why I shutdown the client and re-connect through Robomongo and it works well.

yeah, it worked! thanks a lot
