### ISSUE TITLE
Aggregation query results greater than 50 not displayed

### ISSUE THREAD

**Issue by vsethi13** [paralect/robomongo#1221]
If an aggregation query results in more than 50 records, only 50 are displayed in the robomongo window, and there's no way to navigate to the remaining records.

I am using Robomongo v0.9.0-RC10.

**Comment by juliashibalko** [comment]
@vsethi13 thanks for reporting! It's known issue and we're sorry for that! Issue'll be fixed it in the next releases. As a workaround please check the tips from the ticket 1058 here https://github.com/paralect/robomongo/issues/1058#issuecomment-203305989 and here https://github.com/paralect/robomongo/issues/1058#issuecomment-241706228. Hope they will help you!
Also let me suggest you to track fixing progress with the same #1058 card. So I will close current ticket as duplicate if you don't mind.

**Comment by vsethi13** [comment]
Cool.. thanks @juliashibalko

**Comment by youstartlabs** [comment]
Switch to next page......

**Comment by youstartlabs** [comment]
In robo mongo 1 page has only 50 entrise..

**Comment by simsekgokhan** [comment]
Sorry for the long delay, this issue should be fixed in Robo 3T 1.2. 
Please see: https://blog.robomongo.org/robo-3t-1-2/#a2
