### ISSUE TITLE
Closing a connection doesn't reflect in the open tabs

### ISSUE THREAD

**Issue by revolter** [paralect/robomongo#1228]
Following these steps:

- open a connection
- double click a collection
- close the connection
- execute the `find` command in the opened tab

It executes it! This is highly insecure, as one expects from disconnect to completely break the connection with the server.

**Comment by juliashibalko** [comment]
@revolter thank you for reporting! It's known issue and is still under discussion. Let me suggest you to check this ticket with comments https://github.com/paralect/robomongo/issues/11. I think we will consider this question in further releases. Now our main priority is [Replica Sets.](https://github.com/paralect/robomongo#whats-planned-for-the-next-releases)

**Comment by revolter** [comment]
Sorry, didn't find that issue, I'll close this duplicate one.
