### ISSUE TITLE
Don't reload background tabs on document update

### ISSUE THREAD

**Issue by revolter** [paralect/robomongo#1236]
If I have 2 `.find()` tabs, expand a document (except the first one) in the last one and update a document in the first one, the last tab gets refreshed (does the command actually gets executed a second time?) and so the expanded document gets collapsed.

Is there an option to disable auto-reload for background tabs?

**Comment by simsekgokhan** [comment]
Hi @revolter , I was able to reproduce the problem. Thanks for reporting. 
Seems like it does get refreshed automatically. We will investigate.

**Comment by revolter** [comment]
That's great!

**Comment by juliashibalko** [comment]
Closing as fixed
