### ISSUE TITLE
Version 0.9.0 Counts not being returned when iterating over a large data set

### ISSUE THREAD

**Issue by nshumoogum** [paralect/robomongo#1240]
Specifically when counting all documents that have a particular field been set, see query below:

db.getCollection('collection').find({"field": { $exists : true }}).count()

The field in question is indexed and the collection contains over 23.5million documents to iterate through; using mongo version 2.6.

**Comment by juliashibalko** [comment]
Hi @nshumoogum! It's known issue, so let me suggest you to check workaround described in the ticket #1106 (comment) (increase shellTimeoutSec value). I believe this should solve the problem so I'm closing ticket as duplicate. Please let us know if it works for you and feel free to reopen in any case.
