### ISSUE TITLE
Multi shard (we guess so) edit fail

### ISSUE THREAD

**Issue by seckins** [paralect/robomongo#1244]
On multi shard server (https://atlas.mongodb.com/), when connect with primary instance and trying to edit a document from a collection, Robomongo returns "Error when saving document: 1 Not primary while performing update on {database}.{collection}"
![capture](https://cloud.githubusercontent.com/assets/6057050/20668727/04c8411c-b579-11e6-958b-2610a58aa352.PNG)

**Comment by seckins** [comment]
Ok now, if i use the secondary shard for the connection string, everything works well.

**Comment by juliashibalko** [comment]
Hi @seckins, thank for reporting. Glad to hear it works! But let me clarify, so if you connect to secondary shard, document can be updated successfully? Is it exactly that this shard is not primary? (Status can be checked by running `rs.status()`) 
Thanks in advance for the answer!

**Comment by seckins** [comment]
Yes @juliashibalko, all crud works. And yes, i got wrong with the situation, second shard is not secondary, it's primary. I guess Atlas cloud change the primary shard recently.

Thank you.

**Comment by juliashibalko** [comment]
@seckins Thanks for details! Closing this ticket as Solved.

**Comment by simsekgokhan** [comment]
Merhaba Seckin, for your information, the next version of Robomongo will include support for Replica Sets which means Robomongo will automatically connect and work on primary node. So hopefully, this kind of problems will be seen anymore. ETA for Replica Set support is two weeks, you can follow https://twitter.com/Robomongo to be informed. - Best Regards.

**Comment by spondbob** [comment]
Hey I have exact error message when I am trying to save/update a document through a Direct Connection (not replica as the original issue here). It says

> Error when saving document: 1 Not primary while performing update on mydb.mycollection

What would cause the issue? For the record I am using the latest Robo3T 1.1.1
