### ISSUE TITLE
0.9.0: In-Progress widget not centered for "Update Documents/Remove Documents" context menu actions

### ISSUE THREAD

**Issue by simsekgokhan** [paralect/robomongo#1256]
**Current:**
![screenhunter_63 dec 09 12 30](https://cloud.githubusercontent.com/assets/19390749/21044181/b585d6be-be0b-11e6-8e75-100f9be07383.jpg)

**Expected:**
![screenhunter_64 dec 09 12 33](https://cloud.githubusercontent.com/assets/19390749/21044192/be5a8636-be0b-11e6-8da3-2b1e744bf9a1.jpg)

**Comment by juliashibalko** [comment]
Closing as fixed
