### ISSUE TITLE
DocumentDb Support

### ISSUE THREAD

**Issue by philcarbone** [paralect/robomongo#1263]
Any plans to add DocumentDB support?

**Comment by juliashibalko** [comment]
Hi @philcarbone! Thank you a lot for interesting!
DocumentDB support is in our wish-list, but current priority is delivering critical features like Replica Sets and Export/Import.
Let me suggest you to check progress of DocumenDB support implementation within this card https://github.com/paralect/robomongo/issues/1192. I'm closing this one as duplicate. We will get back to you with any updates. Stay tuned!
