### ISSUE TITLE
Robomongo.org is down

### ISSUE THREAD

**Issue by WoLpH** [paralect/robomongo#1281]
Similar to #962 I suppose, the site is down due to certificate issues.

**Comment by simsekgokhan** [comment]
Hi @WoLpH , thanks a lot for reporting the problem. We started to investigate.

**Comment by WoLpH** [comment]
The easiest solution right now might be to simply disable ssl at the server side. Cloudflare will serve ssl regardless so it won't matter for the end user

**Comment by simsekgokhan** [comment]
Seems to be fixed now. Can you check? Thanks.

**Comment by WoLpH** [comment]
Works great again. Thanks
