### ISSUE TITLE
Error APPCRASH

### ISSUE THREAD

**Issue by GosuUnDeadGhost** [paralect/robomongo#1283]
Hello! 
I get an error while connecting or testing the connection
However, not all addresses.

My OS - windows 7 x64 Maximum

Robomongo 0.9.0-RC9

Сигнатура проблемы:
Имя события проблемы:	APPCRASH
Имя приложения:	Robomongo.exe
Версия приложения:	0.9.0.0
Отметка времени приложения:	574ee9ff
Имя модуля с ошибкой:	Robomongo.exe
Версия модуля с ошибкой:	0.9.0.0
Отметка времени модуля с ошибкой:	574ee9ff
Код исключения:	c0000005
Смещение исключения:	00000000005dcb5e
Версия ОС:	6.1.7601.2.1.0.256.1
Код языка:	1049
Дополнительные сведения 1:	d1f5
Дополнительные сведения 2:	d1f5831eef11cf3ef119971af6eebe98
Дополнительные сведения 3:	e684
Дополнительные сведения 4:	e68462108ee60b8a3fbc9a3db7ebb985

**Comment by juliashibalko** [comment]
Hi @GosuUnDeadGhost, 
thanks for reporting. It's known issue and we are very sorry for that. 
But let me suggest you to track progress within next card https://github.com/paralect/robomongo/issues/1158.
I'm closing this ticket as duplicate. But do not worry, we will get back to you with any news.
