### ISSUE TITLE
Authentication: multiple databases?

### ISSUE THREAD

**Issue by fresheneesz** [paralect/robomongo#1293]
I just enabled authentication for a user to 4 databases, but robomongo makes you choose just one database. Why is this? Why not open all the databases that user has access to?

**Comment by simsekgokhan** [comment]
Hi @fresheneesz , thanks for reporting the problem. Are you using single server or replica set connection? Can you also tell us Robomongo version and server MongoDB version and what kind of MongoDB server you are using? (cloud or local...)

**Comment by fresheneesz** [comment]
I'm realizing that I didn't fully understand user roles and hadn't correctly given that user access to multiple databases. Its hella confusing that you have the "db" parameter on all roles, when that paremeter is meaningless unless you're in the admin database. Roles are pretty damn confusing to me, but now that i've given the user the role `{role: 'root', db:'admin'}` robomongo seems to open up all the databases to me like i'd expect. So i'm closing this.

**Comment by simsekgokhan** [comment]
@fresheneesz , an important information about users, I forgot to mention is that Robomongo "Add User" from GUI is not working as expected, this might definitely increase or cause your confusion. I strongly suggest you to use Robomongo shell to add/edit users.

We have serious plans to fix user management on Robomongo GUI, we also consider to remove "Add User" option from GUI until we fix the problems. Shortly, as I said, for any users related operation Robomongo shell should work without problems.
