### ISSUE TITLE
[1.0 RC1] Can't connect to replica set to MongoDB Atlas Cluster 3.4

### ISSUE THREAD

**Issue by zachrattner** [paralect/robomongo#1299]
I'm having trouble connecting Robomongo 1.0 RC1 to a 3-node replica set on MongoDB Atlas. I'm running Mac OS X 10.12.3. The [blog post](http://blog.robomongo.org/robomongo-1-rc1/) for the 1.0 RC1 release shows a screenshot of Robomongo connected to an Atlas replica set, but I am not able to get it to work. Robomongo gives this error:`SSL connection failure: `

For what it's worth, I _am_ able to import data into Atlas from the Terminal via this command (sensitive details changed): 

`mongorestore --host cluster0-shard-00-00-fgrio.mongodb.net --port 27017 --username my_username --password my_password_here --db db_name --authenticationDatabase admin --ssl --collection MyRecord --drop MyRecord.bson`

Below are the screenshots of my Robomongo configuration (again, sensitive details changed):

<img width="544" alt="screen shot 2017-03-07 at 10 41 41 pm" src="https://cloud.githubusercontent.com/assets/449150/23693178/039e4248-0388-11e7-8d22-4d4c96a2a217.png">

<img width="542" alt="screen shot 2017-03-07 at 10 41 51 pm" src="https://cloud.githubusercontent.com/assets/449150/23693182/0735c5e8-0388-11e7-822b-e1fa13aaff3d.png">

<img width="546" alt="screen shot 2017-03-07 at 10 41 57 pm" src="https://cloud.githubusercontent.com/assets/449150/23693183/0a51beb2-0388-11e7-9dfb-6a31baecbbfe.png">

<img width="558" alt="screen shot 2017-03-07 at 10 42 04 pm" src="https://cloud.githubusercontent.com/assets/449150/23693186/0cac1c98-0388-11e7-9928-f5c443b8e257.png">

<img width="543" alt="screen shot 2017-03-07 at 10 42 11 pm" src="https://cloud.githubusercontent.com/assets/449150/23693189/0f42cd6c-0388-11e7-8c40-77237ec41a08.png">

**Comment by simsekgokhan** [comment]
Hi @zachrattner , thanks for reporting the problem.

Can you make sure and try with the following suggestions?
- Use a user with Atlas Admin privileges as shown in the screenshots.
- Try removing default database option on last tab.

(My second suggestion will be entering set name manually in config file. But let's try that later.
I will guide you about that depending on result of current suggestions.)

**1**
------------
![screenhunter_62 mar 09 09 35](https://cloud.githubusercontent.com/assets/19390749/23738724/c5b125b6-04ab-11e7-9d17-cc2366d9e448.jpg)

**2**
------------

![screenhunter_61 mar 09 09 34](https://cloud.githubusercontent.com/assets/19390749/23738725/c5b4f1c8-04ab-11e7-9a01-a5fdaf142520.jpg)

**Comment by zachrattner** [comment]
Thanks @simsekgokhan. I did both suggestions but to no avail:

1. I changed the user I was connecting as to an Atlas admin
2. I removed the default database

Atlas screenshot:
<img width="1423" alt="screen_shot_2017-03-08_at_10_47_02_pm" src="https://cloud.githubusercontent.com/assets/449150/23739086/9146ec7a-0451-11e7-86ba-c6d6b8373ad5.png">

Error message from Robomongo (after waiting a few minutes for Atlas changes to propagate):
<img width="417" alt="screen shot 2017-03-08 at 10 47 10 pm" src="https://cloud.githubusercontent.com/assets/449150/23739088/94e2f964-0451-11e7-9b0f-d2d44b6e94d7.png">

**Comment by zachrattner** [comment]
I think it's worth adding that I tried both connecting to the replica set and directly to the primary node. Both options are giving the same SSL connection failure message.

**Comment by simsekgokhan** [comment]
Yes, it is useful information. Any chance you are using Atlas free cluster which is MongoDB 3.4? 
Robomongo does not support it yet. (Note: 3.4 support will be the most prior task after a minor release soon)

Secondly, can you connect via terminal using mongo executable?

**Example:**
`mongo "mongodb://cluster0-shard-00-00-f8axx.mongodb.net:27017,cluster0-shard-00-01-f8axx.mongodb.net:27017,cluster0-shard-00-02-f8axx.mongodb.net:27017/DATABASE?replicaSet=Cluster0-shard-0" --ssl`

**Comment by zachrattner** [comment]
Aah, thanks @simsekgokhan that's the issue. It seems free tier deployments use [v3.4](https://docs.atlas.mongodb.com/) and I'm not sure how to downgrade (contacted Atlas support to see if it is possible).

Thanks for the update. Looking forward to seeing v3.4 support in Robomongo. 

Yes, I am able to connect via the command line.

```
>> mongo --version
MongoDB shell version v3.4.2
```

**Comment by simsekgokhan** [comment]
For news about 3.4 support, you can follow us twitter https://twitter.com/Robomongo and/or follow this ticket: https://github.com/paralect/robomongo/issues/1250

I will close this issue. Feel free to re-open for any reason.

**Comment by simsekgokhan** [comment]
Hi @zachrattner , please see [Robomongo 1.1 - Beta version with MongoDB 3.4 Support](https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770)

**Comment by zachrattner** [comment]
Thanks @simsekgokhan! Works great for me.

**Comment by jeanphameldo** [comment]
Hey @zachrattner ,

What settings did you use? I'm not able to connect using RoboMongo 1.1. 

Thanks!

**Comment by simsekgokhan** [comment]
Hi @jeanphameldo , are you trying to connect to Mongo Atlas 3.4 free cluster?
You should enter your cluster members correctly, user/pw into authentication tab and enable SSL with basic setting then it should connect. 

Can you share your settings or the error screenshot you are getting?

**Comment by thammadi** [comment]
Hi @simsekgokhan, I have the same problem connecting to my MongoDB Atlas Cluster (v 3.2.13)
Just installed Robo3T 1.1 and removed all previous versions of Robomongo. Also, created a new user in MongoDB Atlas with Admin permissions.

Below are the screenshots:
![robo3tv1 1-issue-01](https://user-images.githubusercontent.com/5976170/27208303-4a4ee892-5288-11e7-904d-a6dbae340f44.png)
![robo3tv1 1-issue-02](https://user-images.githubusercontent.com/5976170/27208304-4a514fec-5288-11e7-898e-da070781f7ef.png)
![robo3tv1 1-issue-03](https://user-images.githubusercontent.com/5976170/27208305-4a5220fc-5288-11e7-86e5-f699525a5c26.png)
![robo3tv1 1-issue-04](https://user-images.githubusercontent.com/5976170/27208308-4a577d86-5288-11e7-8f83-a35214981c50.png)
![robo3tv1 1-issue-05](https://user-images.githubusercontent.com/5976170/27208307-4a5697c2-5288-11e7-9081-477bd5c4339e.png)
![robo3tv1 1-issue-06](https://user-images.githubusercontent.com/5976170/27208306-4a569b64-5288-11e7-9b13-733b2669b588.png)

With the above config, 'my-cluster', 'unique-id' and 'my-admin' were replaced with actual values.
Am I missing anything?

Cheers,

**Comment by thammadi** [comment]
@simsekgokhan, Apologies. Looks like there was issue with copy paste of username with and extra '\n' appearing in the config file for username. Removing it and restarting Robomongo fixed it.
Pls ignore my previous comment.

Cheers,

**Comment by leovazquezz1** [comment]
![screen shot 2017-06-16 at 6 43 28 am](https://user-images.githubusercontent.com/28604559/27223523-d3e1fc7c-525e-11e7-812c-500927e74203.png)
I am trying to connect to MongoDB following all the setting that are above and it returns this failure. On MongoDB website it says version 3.4.4!! Does Robo support 3.4.4?

**Comment by leovazquezz1** [comment]
Never mind, I removed the "@admin" from the username input and that made the connection.

**Comment by liampmccabe** [comment]
For anyone foolish like me. The database should be **admin** - not the name of your database...

![image](https://user-images.githubusercontent.com/3018957/28790926-a8422640-7622-11e7-87d5-d9bd38a74b61.png)

**Comment by jeebb** [comment]
This is how I fixed it:
![image](https://user-images.githubusercontent.com/8677412/29401944-4e8878c8-835d-11e7-97d7-a9a5146371ad.png)

In my atlas, the node ...-shard-00-02 is marked as primary node. Therefore, I have to move this member to the top of the list in the connection dialog and it works (other settings are the same as yours).

**Comment by MohammedEssehemy** [comment]
Thanks @jeebb

**Comment by siritan** [comment]
Before this steps please download mongodbCompass

Just goto your ->clustors page and find overview tab 
than click connect button
than click connect with compass


it gives you a link  copy it paste compass link part

**Comment by ztrange** [comment]
I found that the Set Name is not optional for MongoDB Atlas Cluster. Also, the way @jeebb puts it, didn't work for me. Turns out my `replicaSet` name was not called the same as the cluster members prefix. I found the correct one on any of the connect strings that Atlas gives. 

They can be found as @vahapgencdal says on:
->clustors page and find overview tab
than click connect button.
any of the options have a `replicaSet=` parameter

**Comment by TompiT** [comment]
@ztrange indeed my `replicaSet` name was the issue. Thanks.

**Comment by GuiEloiSantos** [comment]
@ztrange that's it, it worked for me as well.

**Comment by LadikCZ** [comment]
@ztrange  Thank you very much. It worked well.

**Comment by AntoineEsteve** [comment]
@ztrange Following your steps i can connect to my cluster Atlas ! 

Unfortunately we may have found another issue:
If you only have an admin access (`dbAdmin`) to one DB you can't see it in the explorer, even when you set it as your default database. 
![image](https://user-images.githubusercontent.com/11315805/34045735-87c79974-e1aa-11e7-8dfd-82b9db8d2109.png)

To see it in the explorer you need admin access to all the DB with `dbAdminAnyDatabase` which is not perfect.

**Comment by ChristianFinckler** [comment]
I have the same problem as AntoineEsteve.
I thought, I could just open a shell and type "use myDB". The response sais "switched to db myDb". But sadly the shell forgets that for the following requests.
As a workaround I could enter two lines:
use myDb
db.myCollection.find()

It seems, that the default database is somehow ignored.

**Comment by Dishanx** [comment]
https://stackoverflow.com/questions/43694799/how-can-i-connect-to-mongodb-atlas-using-robomongo

**Comment by mehs2690** [comment]
Does anyone know why this error comes out?
![mongodberrorconnection](https://user-images.githubusercontent.com/9628066/36344004-790c2e16-13d9-11e8-9943-64fd0fdfd328.png)

**Comment by aisemuslu** [comment]
I wrote "admin" as database name and this solved my problem. 
<img width="520" alt="screen shot 2018-10-04 at 10 03 59" src="https://user-images.githubusercontent.com/33437340/46457968-dcfac080-c7bc-11e8-9fd4-ef5de7badacb.png">

**Comment by HOLAPH** [comment]
> Does anyone know why this error comes out?
> ![mongodberrorconnection](https://user-images.githubusercontent.com/9628066/36344004-790c2e16-13d9-11e8-9943-64fd0fdfd328.png)

same issue i am facing please guide us ... how to resolve it ..
