### ISSUE TITLE
Error while trying to launch ROBOMONGO on Ubuntu 12.04.2 LTS

### ISSUE THREAD

**Issue by sujeetbuddiga** [paralect/robomongo#286]
When i try to install ROBOMONGO using robomongo-0.8.1-i386.deb, It gets installed and doesn't show any error. see images: http://bit.ly/1eCXmHU , http://bit.ly/17PxAwR 

but when i try to run the application i get the following error
root@sujeet:/home/sujeet# robomongo
SettingsManager initialized in  "/root/.config/robomongo/robomongo.json" 
Settings saved to:  "/root/.config/robomongo/robomongo.json" 
/usr/bin/robomongo: line 16:  5144 Segmentation fault      "$ROBO_DIR/robomongo"

see: http://bit.ly/15QJ9pO

**Comment by bibyzhang** [comment]
I have the problem too -\--
all output going to: /tmp/robomongo.log
/usr/bin/robomongo: row 16: 10841 error               (The core has been dump) "$ROBO_DIR/robomongo"

**Comment by matusjuraj** [comment]
I have the same problem.
I'm using Ubuntu 14.04, it worked perfectly, but then from day to day it just stopped working.

Tail from strace is:
> read(255, "\nexport LD_LIBRARY_PATH=\"$ROBO_D"..., 631) = 140
> rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
> rt_sigprocmask(SIG_BLOCK, [CHLD], [INT CHLD], 8) = 0
> rt_sigprocmask(SIG_SETMASK, [INT CHLD], NULL, 8) = 0
> clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb754f768) = 16150
> rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
> rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
> rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
> rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
> rt_sigaction(SIGINT, {0x8087ed0, [], 0}, {SIG_DFL, [], 0}, 8) = 0
> waitpid(-1, all output going to: /tmp/robomongo.log
> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], 0) = 16150
> rt_sigaction(SIGINT, {SIG_DFL, [], 0}, {0x8087ed0, [], 0}, 8) = 0
> open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
> fstat64(3, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
> mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb773f000
> read(3, "# Locale name alias data base.\n#"..., 4096) = 2570
> brk(0x90f8000)                          = 0x90f8000
> brk(0x90f9000)                          = 0x90f9000
> brk(0x90fa000)                          = 0x90fa000
> read(3, "", 4096)                       = 0
> close(3)                                = 0
> munmap(0xb773f000, 4096)                = 0
> open("/usr/share/locale/en/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
> open("/usr/share/locale-langpack/en/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
> open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
> open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = 3
> fstat64(3, {st_mode=S_IFREG|0644, st_size=3595, ...}) = 0
> mmap2(NULL, 3595, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb773f000
> close(3)                                = 0
> write(2, "/usr/bin/robomongo: line 16: 161"..., 81/usr/bin/robomongo: line 16: 16150 Segmentation fault      "$ROBO_DIR/robomongo"
> ) = 81
> rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
> --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=16150, si_status=SIGSEGV, si_utime=52, si_stime=14} ---
> waitpid(-1, 0xbfb865f8, WNOHANG)        = -1 ECHILD (No child processes)
> sigreturn() (mask [])                   = 0
> read(255, "", 631)                      = 0
> rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
> rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
> exit_group(139)                         = ?
> +++ exited with 139 +++

Some solution would be appreciated as other Mongo UI software is incomparably worse in my opinion.

**Comment by stennie** [comment]
I believe I've fixed all of the major install issues for Ubuntu 14.04. It would be helpful if you can help test the 0.8.5 .deb release package and provide feedback (via a new issue with details of your O/S, graphics driver, stack trace, etc) if you have any problems: #782.

This issue has had discussion across a number of different versions and system configurations (all the way back to Robomongo 0.8.1) so I'm not clear what environment would be needed to reproduce the issue (or if it still exists).

I'm going to close this in favour of a fresh start with reports against the latest release (0.8.5).

**Comment by erdinctaskin** [comment]
My strace showed that some files (bash.mo & libc.mo) could not found. Quick and dirty solution is,  I copied "libc.mo"  & "bash.mo" from other lang-ack (e.g /usr/share/locale-langpack/en_AU/LC_MESSAGES ) than, run as root robomongo (sudo robmongo) on command line.
