### ISSUE TITLE
Context menu shows incomplete and out of position (sometimes)

### ISSUE THREAD

**Issue by danielbanda** [paralect/robomongo#314]
![issue](https://f.cloud.github.com/assets/5540896/1209809/56092134-25f0-11e3-98a0-7a915cc2e3a0.png)

How to reproduce:
I right click any server explorer item.

**Comment by seanachaidh** [comment]
i also have the same issue. Strange fact. The same thing also happens with other QT applications

**Comment by danielbanda** [comment]
My issue got resolved; I was given a new HDD with Win 8.1, as opposed to my previous Win 8, about a month ago after my HDD got fried.

So what solved it exactly? I don't know. From what I've read it's seems to be some kind of Qt/OS related issue.

Good luck to all of you! Robomongo is a great tool and is still worth using it even with this bug.

**Comment by stennie** [comment]
There are a number of comments on this issue, but I'd agree with the suspicion that this is related to Qt bugs.

Qt has been updated from 5.1.2 to 5.3.2 for the 0.8.5 packages of Robomongo and this resolves a number of cross-platform UI quirks.

If anyone is still seeing issues with 0.8.5 / Qt 5.3.2+, please create a new issue with the specific details of your O/S and Qt version. Screenshots would also help for display glitches.

Thanks!
