### ISSUE TITLE
Segmentation fault on CentOS 6.4 64bit Final

### ISSUE THREAD

**Issue by milanaleksic** [paralect/robomongo#353]
Downloaded 0.8.3 64 bit gzip (same happens with rpm file) from http://robomongo.org/files/linux/robomongo-0.8.3-x86_64.tar.gz

Installed / unzipped without problems.

Start-up ends up with:

    [milan@localhost bin]$ ./robomongo.sh
    
    (<unknown>:3873): Gtk-WARNING **: Attempt to load unknown IM context type 'gtk-im-context-none'
    all output going to: /home/milan/.robomongolog.txt
    ./robomongo.sh: line 16:  3873 Segmentation fault      "$ROBO_DIR/robomongo"

in .robomongolog.txt I can see only these lines being repeated over and over from all failed startups:

    ***** APPLICATION RESTARTED *****
    
    
    Tue Oct  8 17:03:24.641 [Robomongo] SettingsManager initialized in /home/milan/.config/robomongo/robomongo.json
    Tue Oct  8 17:03:24.641 [Robomongo] Settings saved to: /home/milan/.config/robomongo/robomongo.json

Have you encountered something like this before? Can I give you some extra information to maybe fix this problem?

Thanks

**Comment by stennie** [comment]
Closing out old issue against Robomongo 0.8.3.

RPM packaging has been updated and testing for [0.8.5 release](https://github.com/paralect/robomongo/issues/783).

If there are problems with 0.8.5+ install, please open a new issue with details of your environment.

Thanks!
