### ISSUE TITLE
SSL with CA file and Encrypted SSL Private Keys

### ISSUE THREAD

**Issue by stmoroz** [paralect/robomongo#399]

**Comment by KekSfabrik** [comment]
*bump*
i want this aswell - alternatively maybe add the `mongo --sslIgnoreInvalidCertificates` Option so i can at least connect to an instance that runs with `--sslMode requireSSL`

**Comment by jackhsu978** [comment]
:+1:

**Comment by schetnikovich** [comment]
@KekSfabrik @jackhsu978 SSL support is planned and will be the next feature we will work on. Right now we are very close to release new version of Robomongo with SSH support (check #1002 for more info)

**Comment by simsekgokhan** [comment]
New Robomongo with SSL support has been released. Please see SSL connection examples with Robomongo explained and other features of the new release in our blog: http://blog.robomongo.org/robomongo-rc10/ 

Download: https://robomongo.org/download 

Warm Regards from Robomongo Team.

**Comment by juliashibalko** [comment]
Closing this card as implemented and fixed. In any case please feel free to create new ticket in any case. Thank you!
