### ISSUE TITLE
Default screen size/location for new windows

### ISSUE THREAD

**Issue by ghost** [paralect/robomongo#459]
when opening any new window in the app, it seems to use a default value vs the last screen size and location for that window. using this app on a 4k screen causes a lot of extra work to resize and move the windows. ideally it should remember what was the last size and location of the window. thanks!

**Comment by alexhung** [comment]
:+1:

**Comment by juliashibalko** [comment]
Hi guys!
This feature (https://github.com/paralect/robomongo/issues/1102) was implemented in 0.9.0-RC9. Please check our blog post about that release http://blog.robomongo.org/robomongo-rc9/.
So I believe issue is solved and can be closed. In any case please feel free to create new ticket.
Thank you!
