### ISSUE TITLE
Bug: Wrong window size on monitors with screen rotation (90°) (Linux)

### ISSUE THREAD

**Issue by askmatey** [paralect/robomongo#471]
I want to report a small **bug**. This issue happens for users with rotated monitors. However, Robomongo does not fit to the new resolution.

- The window-height is oversized (the application uses 90% of the window height!)
- I'm not able to change the window-height/width (size) any more

## System information:

- Robomongo version: 0.8.4
- OS: GNU/Linux - Fedora 20
- Kernel: 3.12.8-300.fc20.x86_64
- Screen Resolution: 1920 x 1080 + 1920 x 1080 (two monitors)
- Is a bug: Yes
- Reproduced in: GNU/Linux - Ubuntu

![hehft](https://f.cloud.github.com/assets/812964/2017536/df143234-87fc-11e3-8c6f-e1801468c46a.png)

**Comment by pgifford** [comment]
This appears to be similar to #736
