### ISSUE TITLE
QCleanlooksStyle gone in Qt 5.1.x

### ISSUE THREAD

**Issue by nlaplante** [paralect/robomongo#479]
QCleanlooksStyle not found when building with Qt 5.1.2. I had to change src/robomongo/gui/AppStyle.h to fix build error:

```c++
// #include <QCleanlooksStyle>
#include <QCommonStyle>
// typedef QCleanlooksStyle OsStyle;
typedef QCommonStyle OsStyle;
```

**Comment by anorsich** [comment]
@nlaplante We use QT 5.5 to build latest releases of Robomongo and `QCleanlooksStyle` was cleaned up.
