### ISSUE TITLE
ssh tunnel using private key

### ISSUE THREAD

**Issue by drujensen** [paralect/robomongo#484]
I have not been able to successfully connect via tunnel using a private key. The private key doesn't have a pass phrase. I selected my ~/.ssh/id_dsa private key and verified that I can ssh from a terminal with no password requested.  I use this same technique using SQLPro for MySQL with no issues.

![screen shot 2014-03-01 at 7 38 28 am](https://f.cloud.github.com/assets/18718/2301761/be44862a-a157-11e3-96c5-c1cbc1839a89.png)

Thanks!

**Comment by robocon** [comment]
I test on ubuntu 14.04(Vagrant+Puphpet) not using putty it work well
### Connection
```
Address: 127.0.0.1
Port: 27017
```
### SSH
```
SSH Address: 192.168.56.101
Port: 22
SSH User Name: vagrant
SSH Auth Method: Private Key
Private key: part_to_your_puphpet_folder/files/dot/ssh/id_rsa
Passphrase: 
```

**Comment by amitava82** [comment]
@robocon Works great, thanks!

**Comment by nhammond101** [comment]
i'm on ubuntu too and testing the connection (from the connection window) failed , but simply saving the settings and connecting worked

**Comment by jchamberlain** [comment]
+1 On a Mac. It acts like it's not using the tunnel at all, and instead trying to connect directly to localhost.

**Comment by mchen-cb** [comment]
Hey, I just tried out the 0.8.5 os X release. It seems like ssh tunnel (with private key) still doesn't work.

**Comment by stennie** [comment]
@mchen-cb There haven't been any changes to this issue for 0.8.5, so I wouldn't expect any different outcome from previous releases.

**Comment by Jakobovski** [comment]
+1

**Comment by ddo** [comment]
+1

**Comment by ddo** [comment]
After trying some, it works for me now from home -> ec2.
My mistake is missing the ssh username which is "ubuntu" in my case

:+1:

**Comment by askilada** [comment]
+1

**Comment by jonlachlan** [comment]
This works for me. Make sure that the Connection is localhost:27101 (or whatever port you're using), and that your SSH Address has the actual host IP address. I'm using Ubuntu so "ubuntu" is the username, otherwise for Amazon it might be "ec2-user" or "root". For (It's whatever you use for your SSH connection.)

Thanks so much for this feature, now I can just SSH connect to my deployment DB and avoid setting up Mongo's outside connection settings.

**Comment by drujensen** [comment]
Verified that this is still not working with @jonlachlan 's suggestions.  Connection is set to localhost:27017 and SSH Address is using the actual host IP Address.  Also verified I can connect using ssh with username@ipaddress without requiring password.  Verified the private key matches the public key on the server.

**Comment by jonlachlan** [comment]
Huh. My setup is similar. I presume it would be helpful for debugging to know what operating system you're on and what version of Robomongo you're using. I'm on a Mac using Robomongo 0.8.5
Here's my settings:
Connection tab -> address: localhost, port: 27017
Authentication tab -> "Perform Authentication" is turned off
Advanced tab -> Default Database is left blank
SSL tab -> "Use SSL Protocol" is not checked
SSH tab -> 
 "Use SSH tunnel" is checked
 "SSH Address": first field is my server's IP address, second field is the port "22" as was default
 "SSH User Name": ubuntu (my server's username)
 "SSH Auth Method": Set to Private Key
"Private Key": Click the ... button to select your .pem file
"Passphrase": left blank

![screen shot 2015-05-18 at 10 52 24 pm](https://cloud.githubusercontent.com/assets/2972585/7696430/162642c2-fdb2-11e4-8c2f-59fd0d9f896f.png)

Then I click "Test" button and it says:
![screen shot 2015-05-18 at 11 04 15 pm](https://cloud.githubusercontent.com/assets/2972585/7696443/3bb49dea-fdb2-11e4-9b0b-2117bccfe3c1.png)

When I go to connect, it works just fine.

**Comment by drujensen** [comment]
@jonlachlan Thanks for your detailed response.

Everything looks exactly the same:
Mac using Robomongo 0.8.5
Connection tab -> address: localhost, port: 27017
Authentication tab -> "Perform Authentication" is turned off
Advanced tab -> Default Database is left blank
SSL tab -> "Use SSL Protocol" is not checked
SSH tab -> "Use SSH tunnel" is checked
"SSH Address": first field is my server's IP address, second field is the port "22" as was default
"SSH User Name": admin
"SSH Auth Method": Set to Private Key
"Private Key": Click the ... button to select your .pem file
"Passphrase": left blank
 
The exception is that I am using "~/.ssh/id_rsa" file which I generated using `ssh-keygen -t rsa -b 2048 -C "admin@mydomain.com"`

How did you get the .pem format for your private key?  Did you manually convert it or did you use a different technique for generating your ssh pub/private keys?

**Comment by jonlachlan** [comment]
The pem file is what I downloaded from Amazon AWS originally. I think the pem format is required for the SSH Tunnel.

Try this:
```
openssl rsa -in ~/.ssh/id_rsa -outform pem > mydomain-key.pem
```
It will ask you for your password if you have one, then you should have your pem file. You can name it whatever you want.

**Comment by drujensen** [comment]
Once I saw that you were using .pem, I tried:
`openssl rsa -in ~/.ssh/id_rsa -outform pem > id_rsa.pem`

I also tried:
`openssl req -x509 -key ~/.ssh/id_rsa -nodes -days 365 -newkey rsa:2048 -out id_rsa.pem`

Unfortunately, neither worked.

**Comment by jonlachlan** [comment]
That's strange. Did you verify that the "out" file was in the .ssh folder? Did you update the file in the Robomongo settings? Obvious things, but just checking.

You can check that the ssh key file is working by using it in terminal
```
ssh -i ~/.ssh/id_rsa.pem admin@mydomain.com
```

**Comment by jonlachlan** [comment]
I just determined that the "Private Key" must be the full path, so
```
Users/yourself/.ssh/id_rsa.pem
```
not
```
~/.ssh/id_rsa.pem
```

**Comment by drujensen** [comment]
The full path fixed it!  No `.pem` conversion necessary.  @jonlachlan Thanks for your help on this.  It's been over a year and you are the first to help us figure this out!

Users/{yourself}/.ssh/id_rsa

**Comment by jonlachlan** [comment]
Yay! I'm really glad. Happy SSH-ing ;-)

**Comment by petek** [comment]
I just ran across this again, working on some hosts and not on others.  After a bit of debugging, I ran across this in the ssh log:
`Jun 17 16:31:06 xxx sshd[11935]: fatal: Unable to negotiate a key exchange method [preauth]`
This is happening because of the server's KexAlgorithms settings, and RoboMongo not supporting the ones recommended by https://stribika.github.io/2015/01/04/secure-secure-shell.html
It would be helpful if ssh connection debugging could be provided when using an ssh tunnel and the connection fails due to that.

**Comment by Repox** [comment]
I'm on Mac what fixed the issue for me was basically copying my private key and give it the .pem extension. Nothing else.

    cp ~/.ssh/id_rsa ~/.ssh/id_rsa.pem

I selected the .pem file as the private key for Robomongo it worked.

**Comment by scalastic** [comment]
@Repox : Yes, that's the trick on Mac !
And set an existing database name otherwise you'll be waiting very, very long........

**Comment by cburatto** [comment]
Solution from @VierenV using Putty worked just fine for me. Just one minor reminder to the steps in the end:

> Connect with ssh : user@DNSname Port : 22 (server which hosts MongoDB)
If you need a key : 
Menu : Connection/SSH/Auth
Browse.. >Select your key file (.ppk in my case, got with PuttyGen)
Click Open
Enter your passphrase if needed
You are connected now. Then, right click on the window border
Select Change settings
Go to Connection/SSH/Tunnels
Source Port : 27017 (Default MongoDB port)
Destination : 127.0.0.1:27017
Local & Auto selected
**Click Add to add the port to the list**

Also, remember to open your port to your IP (or all IPs) on the AWS security group for the instance.

**Comment by yelgulwa** [comment]
Works great. Thanks for the great product!

**Comment by fracasula** [comment]
Same issue here. It works just fine with MongoChef but it doesn't with Robomongo. I'm using a vagrant machine created with puphpet.com and I tried using both 127.0.0.1:2222 and the direct ip address 192.168.33.10:22.

Thanks for your efforts :+1:

**Comment by ayonliu** [comment]
@jonlachlan thanks, it's worked for me. 

For me, the trick is:
> Connection tab -> address: localhost, port: 27017

The "address" here is "localhost" or "127.0.0.1", not the server's IP address you want to access, because we're using SSH tunnel here.

**Comment by travism** [comment]
@petek is right also. Any server that is using best practices security for their supported openssh settings will probably also fail. 

Please update robomongo to support key exchanges with the latest recommended settings.

**Comment by madhurangaonbit** [comment]
@ayonliu  thankz .

**Comment by iancwinter** [comment]
Fix for me was to use the more complete path for the .pem file, i.e.:

/Users/[me]/.ssh etc.

…rather than:

~/.ssh etc.

(On OS X 10.11.2)

**Comment by anorsich** [comment]
@drujensen @travism @iancwinter @fracasula  In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. It is now much faster and worked seamlessly for during our testing phase. You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/)

Let us know if it worked for you, if there are any issues -- please re-open or create a new issue.

**Comment by zmirc** [comment]
Still doesn't work with 0.9.0 RC9.
Thanks @VierenV for helping. That worked.

**Comment by simsekgokhan** [comment]
Hi @zmirc , we are very sorry that it is not working. For us to investigate, can you please inform us about your local/remote OS version, SSH configuration you use and the error you are getting? (maybe a screenshot)

**Comment by zmirc** [comment]
Hi, @simsekgokhan 
Here are my connection settings in RoboMongo 0.9.0 RC9
TAB Connection:
- some name
- localhost
- 27017
TAB SSH
- checked "Use SSH tunnel"
- address: IPv4 address of an internet reachable server
- address port: **NOT 22 -> I'm using a custom SSH port**
- username: (can't mention)
- method: Private key -> pointing to .ppk private key made with Putty on **Windows 8 (my machine)**
- no key pass

Local OS (my machine): Windows 8
Remote OS (server I wanted to connect): CentOS 7 latest version with latest updates
Remote Mongo: 3.2.9

I attached how it looks when I press "test".
![robomongo ssh tunnel failure on custom port](https://cloud.githubusercontent.com/assets/1527236/17930991/6e2783ea-6a09-11e6-9554-a0f7b0f46641.png)

I wish this helps.

**Comment by simsekgokhan** [comment]
@zmirc 
Thank you very much for lots of useful information.

First of all, start with converting ppk file to OpenSSH format.
Open puttygen, Converstations -> Import Key, select ppk file, convert to OpenSSH key
Normally ppk file is for Putty and Robomongo should use OpenSSH format private key file.

Secondly, as I understand (not sure) your SSH server and mongodb server are the same Centos 7 machine. If so, use the same IP address on connection and SSH tabs but different ports of course. (Different IPs are used when port forwarding or SSH jump-server solutions are used)

If problem still exists, please send us Robomongo SSH logs. 
> How-to: Select the connection and press "shift+enter", and share the logs with us.

**Comment by zmirc** [comment]
@simsekgokhan 
Thanks for the OpenSSH tip. It seems to work now. Great!!!

Maybe mention it somewhere in the user interface. Other tools that I use support Putty's format, that's why I put that one without even thinking about.

**Comment by clearride** [comment]
@ayonliu  after all the over analysis seems the fix was simple ;-), thanks for saving my time

**Comment by abenedetti** [comment]
@simsekgokhan

OpenSSH conversion worked here as well! You've put an end of a 2 days search !!🥇

**Comment by simsekgokhan** [comment]
@abenedetti 
Happy to hear that. Thanks for the feedback ; )

**Comment by mdkshuvo** [comment]
I have not been able to successfully connect to remote server 
![authorization-failed](https://user-images.githubusercontent.com/30826181/29063006-e17a3c58-7c45-11e7-9e5b-7a88f7359273.jpg)

**Comment by nervgh** [comment]
> I have not been able to successfully connect to remote server

I have same issue.

**Comment by yo2boy** [comment]
Had the same issue with Robo3T (rebranded Robomongo).

The putty thing worked but I don't understand why.

**Comment by RoboSparrow** [comment]
This may sound incredibly stupid: Make sure you don't have trailing whitespace in your ssh address and connection name fields.

**Comment by gelldur** [comment]
In my case I have problem with port forwarding on my serwer simply replace `127.0.0.1` with `localhost`

1. Open tunnel
`ssh -vvvL 27020:localhost:27017 username@my_host`
2. Then simply connect in Robo to `localhost` on port 27020

**Comment by fluentart** [comment]
Found the issue on linux and fix.

Copy your private key up to home and add an extension like this:

cp ~/.ssh/id_rsa ~/id_rsa.ssh 

Then use the new file and it works. So the error seems to be when using folders with leading dot, and/or filename without extension.

**Comment by niy** [comment]
This could also be a key incompatibility issue as reported in #1590 and #1189 , Some users were able to fix the problem by regenerating their ssh private keys using RSA. So if your using *Ed25519* algorithm for your private keys, it probably won't work here.

btw @fluentart suggestion fixed the issue for me.

**Comment by davNazaryan** [comment]
Hi. Had the same issue on Windows 10 and Robo 3T 1.2.1
It seems that we need to use a pure private key instead of PuTTY `.ppk` key.
**Note:** As I understand it's not the only issue with Robo 3T SSH tunnel, but for those who tried to use `.ppk` file it may help.

1. Open PuTTYgen ( It must be installed with PuTTY )
2. Load your `.ppk` file there.
3. Click on `Conversions`
4. Then on Export SSH key
 - ![image](https://user-images.githubusercontent.com/16171651/57208522-42c65980-6fe5-11e9-9bfe-c06285a8cb5e.png)
5. Save the file. ( `key_private_pure` in our example )
 - ![image](https://user-images.githubusercontent.com/16171651/57208596-ca13cd00-6fe5-11e9-850c-6fc3a14161a6.png)
6. Use it instead of `.ppk` file for SSH tunneling in Robo 3T
 - ![image](https://user-images.githubusercontent.com/16171651/57208708-4a3a3280-6fe6-11e9-8e65-5fd39f3e55d8.png)

**Comment by krishnaspace** [comment]
On my situation, I had to do few configurations on my Ubuntu 18 Vagrant box in order to successfully connect MongoDB remotely using Robo 3T GUI. I've explained in the following steps.

 1. On Ubuntu server, to open mongo shell run:  
    ````
    $ mongo
    ````
 2. Inside mongo shell, type following command to create new a admin user.
    ````
    > use admin;
    > db.createUser({user:"admin", pwd:"password", roles:[{ role: "root", db: "admin" }]});
    ````

 3. By default mongodb is configured to allow connections only from localhost(IP 127.0.0.1). We need to allow remote connections from any ip address. The following change should only be done in your development server. Open up  **etc/mongod.conf** file and do the following change.

    ````
    # network interfaces
    	net:
    	    port: 27017
    	    bindIp: 0.0.0.0   #default value is 127.0.0.1
    ````

  Also in the same **mongod.conf** file uncomment security option and add *authorization* option as shown below.
````
     security:
    	 authorization: enabled
````

 4. Save and exit the **mongod.conf** file and  restart mongodb server.
    ````
    $ sudo servcie mongod restart
    ````

 5. Download and install Robo 3T GUI tool.

 6. On Robo 3T GUI, in the connection settings, you need to do few changes as shown on
    below screen shots.

[![enter image description here][1]][1]

Enter mongodb **admin** database username and password which you have created earlier.

[![enter image description here][2]][2]

Here, I have entered my Ubuntu 18 Vagrant box ssh credentials.

[![enter image description here][3]][3]


  [1]: https://i.stack.imgur.com/VNz9b.jpg
  [2]: https://i.stack.imgur.com/ZrJ9K.jpg
  [3]: https://i.stack.imgur.com/VP6PY.jpg

Save the changes and press *connect* icon to see if the connection is working fine.

I hope above details would give some help to your situation.

**Comment by brieucdlf** [comment]
Have the issue as well ... Tried your solution @fluentart but not working :(
I'm going to try to regenerate my key !

**Comment by felix-voicehub** [comment]
For people on macOS this should work:

`/Users/YOURUSERNAME/.ssh/id_rsa`

**Comment by AsterixMechant** [comment]
> Found the issue on linux and fix.
> 
> Copy your private key up to home and add an extension like this:
> 
> cp ~/.ssh/id_rsa ~/id_rsa.ssh
> 
> Then use the new file and it works. So the error seems to be when using folders with leading dot, and/or filename without extension.

This fixed it for me!
