### ISSUE TITLE
Remove SSH authentication

### ISSUE THREAD

**Issue by fgarcia** [paralect/robomongo#485]
Although I do love the SSH tunnel for my connections, I find the current implementation to be somehow redundant.

I have just verified that I am required to type a user password which is stored in plain json. for security reasons, it would be better to remove the password field and ask the user.

However I would argue that the most sensible way to connect through ssh is using private keys, and in that case, the user should have a proper ssh configuration. Would it not be easier to have a setup where Robomongo assumes that the user has a good ssh configuration with private keys to the server?

The proposal is to remove all authentication related fields and let Robomongo to rely on the local ssh client configuration.

**Comment by stennie** [comment]
@fgarcia As part of working on the upgrade to MongoDB 3.0 shell I've reviewed the current state of the SSH implementation and agree it needs to be refactored (see #798).

I'm reopening your proposal and will be removing SSH support for the 0.9.0 release.

Setting up an SSH tunnel outside of Robomongo is a more secure (and robust) approach at the moment.

**Comment by anorsich** [comment]
@fgarcia @m3nu In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. We do not store password key password in robomongo config, instead, we ask for it every time when new ssh connection was initiated. You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/) 

Let us know if it worked for you, if there are any issues -- please re-open or create a new issue.
