### ISSUE TITLE
Editor and output window font size on Linux Mint

### ISSUE THREAD

**Issue by cmhdevelopment** [paralect/robomongo#492]
On Linux Mint 16 “Petra” Cinnamon (64bit) the font size of the editor and text mode output window is out of proportion to everything else.  On my system it is too big as the attached screenshot shows.

![robo-mongo](https://f.cloud.github.com/assets/6222070/2404270/86887896-aa39-11e3-9633-636ee3c766e2.png)

**Comment by stennie** [comment]
The font sizes are currently hardcoded, however there is an open feature request to make this a user preference: #645.
