### ISSUE TITLE
Can't type quotes in Shell commands LINUX

### ISSUE THREAD

**Issue by juanitomint** [paralect/robomongo#493]
Hi there, robomongo is my favourite tool for working with mongo but can't make it write quotes, instead a blank space is typed.

**Comment by stennie** [comment]
Robomongo 0.8.5 packages use Qt 5.3.2; issue no longer appears to be reproducible:
 - [RPM](https://github.com/paralect/robomongo/issues/783)
 - [DEB](https://github.com/paralect/robomongo/issues/782)

If you're still having problems with Robomongo 0.8.5+, please open a new issue with details of your environment. 

Thanks!

**Comment by kauegimenes** [comment]
Robo 3T v1.2.1
Deadkeys
Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cant type double quotes.

**Comment by moak** [comment]
Same problem here :/

**Comment by snippet** [comment]
I had the same problem.

I fixed **changing keyboard layout**, from English (US, intl., with dead keys) to **English (US)**

Ubuntu 19.10
Robo 3T 1.3.1

**Comment by AlexandreBonneau** [comment]
The problem is still present in the last version 1.4.4, where dead keys are not correctly recognized.
Using a dvorak, I'm using the workaround mentioned by @sanfilippopablo:
- Using rightAlt+' to type the '
- Using rightAlt+Shift+' to type the "
