### ISSUE TITLE
Full processor power usage

### ISSUE THREAD

**Issue by avilchinsky** [paralect/robomongo#531]
Robomongo was opened and connected to remote host
After time of work computer was turned to waiting mode
After restoring the system robomongo use 95% of system resources.

This issue was checked 10 times.

OS Windows 7 x64

**Comment by anorsich** [comment]
@avilchinsky @stennie 
In the latest 0.9.0 RC8 release we did the first chunk of work to make Robomongo more stable and crash less. We can't reproduce that issue on our side. Please, let us know if it worked for you and if it doesn't -- please, create a new ticket. 

You can read more information in the following [blog post](http://blog.robomongo.org/robomongo-rc8/)

P.S. Don't be hesitant to post any issues, we promise to respond much much faster than before :)
