### ISSUE TITLE
Issue with Qt 5.3

### ISSUE THREAD

**Issue by gavruk** [paralect/robomongo#586]
When I build robomongo with Qt 5.3, it fails very often on connecting to server (with and without auth). This issue is not stable, Robomongo can fail with error few times and then connect successfully after restart

Error:
http://pastebin.com/ZS1HCNMp

**Comment by stennie** [comment]
@gavruk Can you still reproduce this issue with Robomongo 0.8.5? The release packages are using Qt 5.3.2, so there have been two 5.3 releases since the initial report which would have been using Qt 5.3.0.

**Comment by gavruk** [comment]
I cannot reproduce this right now
