### ISSUE TITLE
Robomongo should not force to save passwords

### ISSUE THREAD

**Issue by wienczny** [paralect/robomongo#609]
When configuring Robomongo with authentication or ssh tunnel passwords are required. It should be possible to have Robomongo not save passwords on disk and instead ask again when establishing a connection.

**Comment by venalis** [comment]
+1

**Comment by markstos** [comment]
+1

**Comment by anorsich** [comment]
@wienczny @AlexEllo @jorritd @markstos  In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. We do not store password key password in robomongo config, instead, we ask for it every time when establishing a new ssh connection. You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/) 

Let us know if it worked for you, if there are any issues -- please re-open or create a new issue.

**Comment by ms1111** [comment]
@anorsich Robo 3T 1.2.1 still seems to require you to save the password for authentication (not SSH tunnel).

![image](https://user-images.githubusercontent.com/17057295/49914056-e3ad5000-fe5d-11e8-936a-f841e838570e.png)

From the original description `When configuring Robomongo with authentication or ssh tunnel passwords are required. It should be possible to have Robomongo not save passwords on disk and instead ask again when establishing a connection.`

It looks like SSH tunnel passwords have been addressed, but not database authentication passwords.

**Comment by directdevice** [comment]
> @anorsich Robo 3T 1.2.1 still seems to require you to save the password for authentication (not SSH tunnel).
> 
> ![image](https://user-images.githubusercontent.com/17057295/49914056-e3ad5000-fe5d-11e8-936a-f841e838570e.png)
> 
> From the original description `When configuring Robomongo with authentication or ssh tunnel passwords are required. It should be possible to have Robomongo not save passwords on disk and instead ask again when establishing a connection.`
> 
> It looks like SSH tunnel passwords have been addressed, but not database authentication passwords.

Any plans to prompt database password in case if it wasn't saved? Could not find related ticket for this
