### ISSUE TITLE
[OS X 10.9] App crashes when trying to refresh after mongod has been killed

### ISSUE THREAD

**Issue by DdWr** [paralect/robomongo#642]
Hi,

I've found an issue where Robomongo will crash when refreshing a database after I kill the mongod process. The steps to reproduce the bug are as follows:

1) Start mongod + Robomongo
2) Connect to database
3) Kill mongod
4) Right click database name in left pane and hit 'refresh'

The app then crashes. Perhaps this can be modified to gracefully fail and give an error message of some sort. I noticed that operations on collections such as 'Statistics', 'Shard Operation', and 'Shard Distribution' appropriately give a notice of not being able to connect after mongod is killed.

**Comment by schetnikovich** [comment]
@DdWr This issue is fixed in Robomongo 0.9.0 RC8. Please reopen this ticket if this problem still exists for you.
