### ISSUE TITLE
Resize query editor

### ISSUE THREAD

**Issue by soapergem** [paralect/robomongo#657]
This is a small feature request. Right now the query editor shows one line by default, and expands somewhat if you start putting more content in there. However, it seems to be limited to a maximum height of 312 pixels, no matter what. It would be really nice if you could just drag the space between the query editor and the query results pane as a vertical handle, so you could resize it to be whatever height you wanted. This is especially useful when you've got bigger queries as it's really obnoxious to have to work in a window that's only 312 pixels high.

Here's the "query editor" pane I'm talking about:
![robomongo](https://cloud.githubusercontent.com/assets/8888628/4381404/7c3ed526-4375-11e4-85e0-8a065163c198.png)

**Comment by d0x** [comment]
+1

**Comment by ktw** [comment]
Yes please, this is how it looks on my OpenSuse 13.2 KDE: 
![robomongo](https://cloud.githubusercontent.com/assets/105196/6432661/60d3ec48-c059-11e4-899e-701d1daa3052.png)

**Comment by roaringskyinc** [comment]
+1. This is a must. I shouldn't have to scroll on a 30" display to see all of my 20-line aggregation query.

**Comment by antonioalegria** [comment]
+1, this would be really good to have. Would make Robomongo much more usable!

**Comment by viztastic** [comment]
+1

**Comment by simsekgokhan** [comment]
Hi guys, thanks for your interest. We have put this into our high vote list. We will be considering this in the next releases.

**Comment by simsekgokhan** [comment]
Hi guys, thanks a lot for your interest, sorry for the long delay. We have finished development of a new feature which will give you full screen query editor and dock-able output window (for each tab). 

Please see the screenshots here:
[New Feature: Full Screen Query Editor (Dockable Output Window)](1187) 

Feature is under internal testing, planing to release next week. 
Follow the latest releases and news here: 
https://twitter.com/Robomongo

**Comment by juliashibalko** [comment]
I'm closing this card as implemented and fixed in 0.9.0 release (https://github.com/paralect/robomongo/issues/1187).
Please see the new Robomongo 0.9.0 with new features described here http://blog.robomongo.org/robomongo-0-9-0-final/
Download site: https://robomongo.org/download

In any case please feel free to create new ticket. Thank you!
Follow us for latest news: https://twitter.com/Robomongo
