### ISSUE TITLE
ssh tunnel not working when using password auth method

### ISSUE THREAD

**Issue by deseman** [paralect/robomongo#681]
When using the ssh connection settings I'm not able to connect to my database. I am able to connect when I manually create a tunnel.

Platform:
![screen shot 2014-10-29 at 11 35 14](https://cloud.githubusercontent.com/assets/8594951/4824161/54e89d4c-5f57-11e4-8683-9254fc320ffd.png)

Robomongo version:
![screen shot 2014-10-29 at 11 36 13](https://cloud.githubusercontent.com/assets/8594951/4824173/6e8e44b8-5f57-11e4-8ead-61a258c7cefc.png)

The credentials in the following screenshot have been censored for privacy reasons.
![screen shot 2014-10-29 at 11 37 34](https://cloud.githubusercontent.com/assets/8594951/4824192/9fe2a112-5f57-11e4-8125-b411c2f46b92.png)

![screen shot 2014-10-29 at 11 30 44](https://cloud.githubusercontent.com/assets/8594951/4824108/af33482a-5f56-11e4-9d21-63fe895bc26e.png)

**Comment by tamasmahr** [comment]
+1... It would be a nice feature though...

**Comment by finscn** [comment]
Me too . SSH can't work

**Comment by anorsich** [comment]
@deseman @ChrisGitIt @pauloschilling @tamasmahr @finscn 
In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. It's now much faster and has some security improvements. We also re-worked diagnostic window, so now it's clear what exactly is not working. You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/) 

Let us know if it worked for you, if there are any issues -- please re-open or create a new issue.
