### ISSUE TITLE
SSH Private Key Selection only shows files with extension

### ISSUE THREAD

**Issue by robo47** [paralect/robomongo#685]
The dialog for selecting private keys only shows files with extensions.

Since the  default for ssh private key generation is something like id_rsa which has no extension it would be nice to show files without extensions too, so there is no need to rename each private key to be usable.

OS: Ubuntu 13.10/64
Robomongo: 0.8.4

**Comment by anorsich** [comment]
@robo47   In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. You can select key files without extension. It is also much faster now and has some security improvements.   You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/) 

Let us know if it worked for you, if there are any issues -- please create a new issue.
