### ISSUE TITLE
SSH Tunnel connection fails with DNS

### ISSUE THREAD

**Issue by confuser** [paralect/robomongo#686]
The tunnel itself is fine through another server, however, when trying to connect to the database using a custom domain name with a custom DNS server, it fails.

Changing the address to its internal IP allows a successful connection. Other systems are successfully connecting using the domain name.

The SSH tunnel has the custom DNS server, and can successfully look up the domain.

**Comment by anorsich** [comment]
@confuser   In the latest 0.9.0 RC8 release we reworked ssh tunnel from scratch. It now works much faster, supports DNS and has some security improvements. You can read more in the following [blog post](http://blog.robomongo.org/robomongo-rc8/) 

Let us know if it worked for you, if there are any issues -- please create a new ticket.

**Comment by confuser** [comment]
Amazing, thanks @anorsich!
