### ISSUE TITLE
On yosemite it doesn't exit cleanly

### ISSUE THREAD

**Issue by bhaveshkothari** [paralect/robomongo#690]
Every time you try to exit it, it throws error and asks to reopen.

**Comment by farneman** [comment]
On OS X 10.10.2 with Robomongo 0.8.4 I'm no longer seeing this issue now. Not sure exactly when it stopped occurring though.

**Comment by stennie** [comment]
@farneman I haven't been able to reproduce this .. if anyone has a more consistently reproducible test case please reopen with further details.

Thanks!
