### ISSUE TITLE
Double precision in mongo shell v Robomongo 

### ISSUE THREAD

**Issue by gavinpullen** [paralect/robomongo#699]
If I insert a value(which is a double) into my Mongo database. Then I query the shell and get the expected value :

    "Value" : 8.7363636

If I use the same query in MongoVUE I also get the expected result.

If I use the same query in Robomongo.
I get the following output when I view results in text mode :

    "Value" : 8.736363600000001

I get the following output when I view results in tree mode :

    "Value" : 8.7363634

Is there a reason for this????

**Comment by pierrefevrier** [comment]
I'm facing the same problem with Double value:
Furthermore, field "montant" is displayed differently between screen (18.900000 versus 18.8999999999999990), see screenshot below:
![mongo double](https://cloud.githubusercontent.com/assets/239586/8775020/92c4884e-2ee4-11e5-9c14-960bcfe8c0ff.jpg)

**Comment by acrolink** [comment]
I store big integers like:
999999999999 using mongo shell and what I see inside Robomongo is:
999999999999.00000000000000

while inside Mongo shell I see the expected:
999999999999

Great software but those zeros are annoying, any way to hide them?

**Comment by tjconcept** [comment]
This is affecting me with smaller integers as well.

An integer like `3793737` is shown as `3.79374e+06` in text mode while it is correctly shown in table mode.

**Comment by schetnikovich** [comment]
@gavinpullen @pierrefevrier @acrolink @tjconcept This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.

**Comment by gavinpullen** [comment]
Great job... Works as expected... Thanks

**Comment by anorsich** [comment]
@gavinpullen Awesome, happy to hear that!

**Comment by lionvs** [comment]
I still can see different results for doubles in mongo shell and robomongo.

Try the following code:
db.test.insert({value: 225.99999999999997})
db.test.find().pretty()

In robomongo I see result as:
{ "value" : 228, ...}
In mongo shell:
{ "value" : 227.99999999999997, ...}

I am using Robomongo 0.9.0 final.

**Comment by juliashibalko** [comment]
Hi @lionvs,
thanks for reporting! It's known issue and we suggest to track progress within this card https://github.com/paralect/robomongo/issues/1245
