### ISSUE TITLE
Insanely High CPU Usage

### ISSUE THREAD

**Issue by Jake0oo0** [paralect/robomongo#714]
I'm running 64x Windows 7, and RoboMongo seems to randomly start using 90%+ of my CPU, even after closing it, meaning I have to kill the process. Has anyone else been experiencing this? Is there any logs that might indicate what is causing this?

**Comment by stennie** [comment]
@Jake0oo0 I haven't been able to reproduce this issue on Windows yet with either Robomongo 0.8.4 or [0.8.5 release preview](https://github.com/paralect/robomongo/issues/779) and haven't come across any similar issue reports.

I'm going to close this, but please feel free to reopen if you have additional details that might help.

Thanks!

**Comment by Jake0oo0** [comment]
@stennie Hey, where could I find the RoboMongo log? I had this happen this morning after waking up my computer, and closing RoboMongo. CPU spiked to ~75% or so after 'closing' it.
