### ISSUE TITLE
Keyboard not working on Ubuntu 14.04 remote desktop

### ISSUE THREAD

**Issue by araad** [paralect/robomongo#716]
Hi,

I'm using Robomongo 0.8.4 on a Ubuntu 14.04 machine with Mate desktop which I'm connecting through xRDP from my Windows 7 machine. I can click and use the app as normal but i can't type anything and it only happens in Robomongo, my keyboard works everywhere else.

**Comment by and3rson** [comment]
I've found a dirty solution. On my end, I had those errors:
```
Error:    Couldn't find file "symbols/"us" in include paths
Error:    1 include paths searched:
Error:    	/usr/share/X11/xkb
Error:    1 include paths could not be added:
Error:    	/home/anderson/.xkb
```

Seemed like some bug with string generation - `"symbols/"us"` includes extra quotes for some reason.
...So I went to `/usr/share/X11/xkb` and manually created symlinks for those **wrong** languages:

```
$ cd /usr/share/X11/xkb/symbols
$ sudo ln -s us \"us
```

I had to do this few times for various missing languages, including `us"`, `"us` and `ua"`.
Dirty, but works!

**Comment by stennie** [comment]
@araad @dechaoz05 @erickorb @and3rson Can you retest with the 0.8.5 .deb preview: https://github.com/paralect/robomongo/issues/782

The dependencies have been updated (including Qt 5.3.2) so I'm hoping this may also address the keyboard issues.

Thanks!

**Comment by Eisrep** [comment]
I had this same problem with 0.8.4 using Windows Remote Desktop to connect to Ubuntu with xrdp and xfce4. I tried the 0.8.5 preview and the keyboard is working fine.

**Comment by stennie** [comment]
@Eisrep Thanks for confirming! Will assume this has been fixed in the 0.8.5 release packages :). If anyone is still have problems please open a new issue with details of your environment.

**Comment by juleedev** [comment]
I just upgraded from 0.8.4 to 0.8.5 via the ubuntu software center but I'm still having the problem where my keyboard doesn't work.  Using xrdp... ubuntu 15 with mate desktop.  Any suggestions would be appreciated.

**Comment by jnarr** [comment]
Hi all, I have Ubuntu 16.10 with xrdp 0.9 with MATE desktop for xrdp and generally using Cinnamon. xrdp is setup and generally working. If I connect from within my own system (Ubuntu Remmina to Ubuntu, same machine) everything works nicely. If I connect from Windows or iPad (iOS) no keystrokes are recognised in a terminal in Ubuntu than Return and the Arrow keys. Normal letters and digits are not recognised. If I press on the iPad on-screen keyboard the "Ctrl"-button and a letter afterwards, the letter is recognised, i. e. Ctrl, i creates an i. If I press the "Shift" button (on-screen) and a letter, the capital letter is properly recognised, i. e. onscreen Shift, l creates an L. Has anyone an idea? Thanks for your help.
