### ISSUE TITLE
Very Slow Listing of Collections in Explorer

### ISSUE THREAD

**Issue by excalq** [paralect/robomongo#730]
Unfortunately, I am tasked with managing a database which has about 1800 collections (many are generated during daily tasks, then cleaned up every few weeks). Robomongo takes on the order of 10 minutes to list collections when viewing this database via an SSH tunnel! When using the mongo shell directly however, it is fairly instant.

I realize it's probably not great design to have so many collections in a DB, but waiting 10-minutes after any operation that loads or modifies the list of collections is a pretty unhappy experience. The problem doesn't seem to happen during a localhost connection.

**Comment by excalq** [comment]
I should also mention that each collection itself is about 50MB, although I don't think that would matter in retrieving the collection list.

**Comment by stennie** [comment]
@excalq I'll try repro'ing this. To be clear, are you only seeing this issue on remote tunnelled connections and not with a similar number of collections in a local database? What sort of network connectivity do you have to the remote server? Have you tried monitoring your bandwidth or server usage to see if there are interesting correlations when Robomongo is updating the collection info?

Also, what version of MongoDB are you using and what O/S + version are you running Robomongo on?

Thanks!

**Comment by excalq** [comment]
I'm not entirely confident my local DB has ever been quite as large as the remote systems I'm connecting to, probably about 500 collections at the max. However, I recall that being fairly instant.

One factor may be that our remote MongoDB instances are version 2.4.6. :cold_sweat: These are on Engine Yard Gentoo Linux.

I'm running the client on Mac OS X 10.9.5. Similar setups on other boxes exhibit the same behaviour.

**Comment by kvirkki** [comment]
Hi,

We have about 300 collections in a database and it takes 0,2 seconds to do db.getCollectionNames(), but about 18 seconds to open the collections branch in the tree view. In my opinion that's a lot of time and makes working with Robomongo a pain :(

We're using MongoDB 2.4.6 running in AWS and I'm connecting there from Robomongo running in Windows.

**Comment by ankitjaininfo** [comment]
Same issue here. The  collections branch in the tree view takes ~2 mins to open/refresh. We have  603 collections and these are getting fetched from a remote DB.

Does the tool fetch all schema details when the tree needs to be rendered ?

**Comment by stennie** [comment]
@ankitjaininfo I suspect the tree view is pulling stats for all collections (Count and Size are used in the tool tip for a collection). I haven't confirmed yet, but expect this should be done lazily (i.e. on mouseover or on request) or perhaps even be a user preference.

**Comment by ankitjaininfo** [comment]
Would love if someone fixes this in next release. I see this is marked as `needs_rero` but it is happening with me always.

1. The DB has too many collections > 600
2. Many of the collections are more than 1MB - 100MB range with indexes.

**Comment by ankitjaininfo** [comment]
Thanks for taking this for `Robomongo 0.9.0` release.

One simplest solution I think is - *disabling stats pulling for tree view using a command-line flag*.

**Comment by dcumin39** [comment]
I am having a similar issue.  It takes about 1 minute to open the list.  We have 2826 collections.

**Comment by rubensainiuc** [comment]
Same issue here. I takes a little over 1 minute to expand 1350 collections in one db.
We are creating 1 collection every day, so this will go slower and slower. :smiley: 
Also, running `db.getCollectionNames()` in the console is almost instant (0.5s).
I suppose the slowness is for getting Count and Size statistics for the tooltip, just as @stennie said.

I'm using Robomongo 0.8.5 on Windows 7, connecting directly to a distant server (hosted on EC2).

**Comment by anorsich** [comment]
@rubensainiuc @excalq @ankitjaininfo @kvirkki @dcumin39 I have a great news for you! This issue was fixed in latest 0.9.0 RC6 release. If you'll have a minute to check that it works for you - that would be awesome. I am closing this ticket, if the issue still exists for anyone -- feel free to reopen.
