### ISSUE TITLE
Not working in windows x32

### ISSUE THREAD

**Issue by Sanuich** [paralect/robomongo#734]
Not working
OS windows xp SP3 game edition
just don't start without any explains

**Comment by stennie** [comment]
@Sanuich As per #411, Windows XP is not supported and there are no current plans to do so.

MongoDB also dropped official support for Windows XP as at 2.2 (ref: [Install MongoDB on Windows](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/)).

> MongoDB for Windows 32-bit runs on any 32-bit version of Windows newer than Windows XP. 32-bit versions of MongoDB are only intended for older systems and for use in testing and development systems. 32-bit versions of MongoDB only support databases smaller than 2GB.

**Comment by Sanuich** [comment]
Wery sad. It is better to notice it somwhere in download section.

2015-01-12 1:41 GMT+02:00 Stephen Steneker <notifications@github.com>:
