### ISSUE TITLE
Right Click popup disappears before clicking when using a remote VM Ware based Windows 7 VM

### ISSUE THREAD

**Issue by vasanramani** [paralect/robomongo#740]
I use a VMWare based remote desktop that runs on Windows 7. I have Robomongo verison 0.8.4 running. I see this annoying behavior when right clicking on a row for any operation. The popup immediately disappears. I use many such applications on the VM and it is fine infact the Robomongo older version 0.7.1 beta looks good as well.

**Comment by stennie** [comment]
@vasanramani Can you retry with the 0.8.5 preview on #779? I suspect the bug here is related to the Qt version, which has been updated from 5.1.2 to 5.3.2 for the 0.8.5 packages.

Thanks!

**Comment by stennie** [comment]
@vasanramani Have had other supports of success with Robomongo 0.8.5, so going to assume this will work for you as well. Please feel free to reopen with additional details if you're still having issues.

Thanks!

**Comment by vasanramani** [comment]
thanks Stephen, I will take a look.

*-----------------------------------------------------------------------------------*
*Vasan Ramani*
3619 Hogan Circle
Rochester Hills, Michigan - 48307
Ph# Cell-248-495-1655

*Love All. Serve All. - Baba*
*-----------------------------------------------------------------------------------*
