### ISSUE TITLE
Connect !

### ISSUE THREAD

**Issue by R008-Coder** [paralect/robomongo#742]
I Can't Connect Robo Mongo , it's show error Message , Any Solution ?

**Comment by TheHett** [comment]
omg, go to on stackoverflow with a noob questions.

**Comment by stennie** [comment]
@R008-Coder Hard to guess what the error might be, but I would start by making sure you can connect with a normal `mongo` shell first using the same connection details. If you can connect with a `mongo` shell and are still having issues you could reopen this issue with more details (exact error message, connection settings for auth/ssl/ssh, MongoDB version).

Thanks!
