### ISSUE TITLE
hi, i build it on 10.10.1, but failed

### ISSUE THREAD

**Issue by jacksonpan** [paralect/robomongo#743]
renpandeMacBook-Pro:~ renpan$ qmake --version
QMake version 3.0
Using Qt version 5.4.0 in /usr/local/Cellar/qt5/5.4.0/lib
renpandeMacBook-Pro:~ renpan$ cmake --version
cmake version 3.1.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
renpandeMacBook-Pro:~ renpan$ scons --version
SCons by Steven Knight et al.:
	script: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
	engine: v2.3.4, 2014/09/27 12:51:43, by garyo on lubuntu
	engine path: ['/usr/local/Cellar/scons/2.3.4/libexec/scons-local/SCons']
Copyright (c) 2001 - 2014 The SCons Foundation

and do:
cmake .. -DCMAKE_BUILD_TYPE=RELEASE 
cpack

then:

Linking CXX executable build/Robomongo.app/Contents/MacOS/Robomongo
Undefined symbols for architecture x86_64:
  "mongo::BSONObj::getField(mongo::StringData const&) const", referenced from:
      Robomongo::CollectionStatsTreeItem::CollectionStatsTreeItem(boost::shared_ptr<Robomongo::MongoDocument>) in libRobomongo_lib.a(CollectionStatsTreeItem.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/build/Robomongo.app/Contents/MacOS/Robomongo] Error 1
make[1]: *** [src/CMakeFiles/Robomongo.dir/all] Error 2
make: *** [all] Error 2

**Comment by jacksonpan** [comment]
can you give me some advice?

**Comment by jacksonpan** [comment]
Linking CXX static library libRobomongo_lib.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libRobomongo_lib.a(Event.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libRobomongo_lib.a(StdUtils.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libRobomongo_lib.a(Event.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libRobomongo_lib.a(StdUtils.cpp.o) has no symbols
[ 98%] Built target Robomongo_lib
Scanning dependencies of target VersionConf
[ 99%] Generating ../Robomongo/robomongo.desktop
[ 99%] Built target VersionConf
[ 99%] Generating qrc_gui.cpp
Scanning dependencies of target Robomongo
[ 99%] Building CXX object src/CMakeFiles/Robomongo.dir/robomongo/app/main.cpp.o
[ 99%] Building CXX object src/CMakeFiles/Robomongo.dir/qrc_gui.cpp.o
Linking CXX executable build/Robomongo.app/Contents/MacOS/Robomongo
Undefined symbols for architecture x86_64:
  "mongo::BSONObj::getField(mongo::StringData const&) const", referenced from:
      Robomongo::CollectionStatsTreeItem::CollectionStatsTreeItem(boost::shared_ptr<Robomongo::MongoDocument>) in libRobomongo_lib.a(CollectionStatsTreeItem.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/build/Robomongo.app/Contents/MacOS/Robomongo] Error 1
make[1]: *** [src/CMakeFiles/Robomongo.dir/all] Error 2
make: *** [all] Error 2

**Comment by phildebrand** [comment]
Got the same result on OSX 10.9.5    
```
Scanning dependencies of target Robomongo
[ 99%] Building CXX object src/CMakeFiles/Robomongo.dir/robomongo/app/main.cpp.o
[ 99%] Building CXX object src/CMakeFiles/Robomongo.dir/qrc_gui.cpp.o
Linking CXX executable build/Robomongo.app/Contents/MacOS/Robomongo
Undefined symbols for architecture x86_64:
  "mongo::BSONObj::getField(mongo::StringData const&) const", referenced from:
      Robomongo::CollectionStatsTreeItem::CollectionStatsTreeItem(boost::shared_ptr<Robomongo::MongoDocument>) in libRobomongo_lib.a(CollectionStatsTreeItem.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/build/Robomongo.app/Contents/MacOS/Robomongo] Error 1
make[1]: *** [src/CMakeFiles/Robomongo.dir/all] Error 2
make: *** [all] Error 2
```

What I did:
```
$ brew install qt52
$ brew install gt5
$ export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.4.0/lib/cmake
$ ./build.sh
```

**Comment by Syirrus** [comment]
I'm having the same issue. :(

**Comment by tessus** [comment]
Same here. I'm on 10.9.5.

**Comment by tessus** [comment]
I was able to narrow down the issue:

The `make` and `make install` works, if a Debug build type was selected (the default): `cmake ..`

As soon as you use `cmake .. -DCMAKE_BUILD_TYPE=Release`, I get an error (the same error everybody else got in this thread).

Also, my debug executable (the entire .app) is 114MB ! It's running, but WTH is going on?

**Comment by stennie** [comment]
>  my debug executable (the entire .app) is 114MB ! It's running, but WTH is going on?

@tessus A debug build includes symbols and extra info, so will be larger than a release build. It also links to debug versions of referenced libraries. What concerns you about the size?

**Comment by tessus** [comment]
@stennie the size concerns me, because it is 5 times bigger than the version I got from @topilski.

It also does not explain, why everybody in this thread (me included) gets the same error when trying to compile a release build.

I tried to dig through the linker and compile flags and commands to figure out what the issue might be, but with no avail. After several hours of figuring it out, I gave up.

**Comment by stennie** [comment]
@tessus The size difference is to be expected for debug vs release builds.

> I tried to dig through the linker and compile flags and commands to figure out what the issue might be, but with no avail. 

I'll look into the build error. fwiw, I'm using Qt downloaded from www.qt.io (not the Brew packages).

**Comment by tessus** [comment]
I'm using MacPorts. I tried the 64-bit and the Universal variants. Same problem. Other people here used the Homebrew version. I would find it very strange, if that was the reason.

**Comment by stennie** [comment]
@tessus I'm not sure either, but the error appears be somewhere in the build toolchain: "Undefined symbols for architecture x86_64"

**Comment by tessus** [comment]
@stennie I checked all libs and object files. They are all 64 bit. The error message is a bit misleading. CollectionStatsTreeItem.cpp.o is in fact included in libRobomongo_lib.a. I suspect that a library is missing in one of the linker commands.

**Comment by tessus** [comment]
@stennie it seems that `mongo::BSONObj::getField(mongo::StringData const&) const` is missing somehow.

**Comment by hellysmile** [comment]
I have same issue with QT from brew and from www.qt.io

**Comment by tessus** [comment]
yep. this solved it for me. resulting app: 6.9MB (debug build: 124MB) awesome. thx.
