### ISSUE TITLE
SSH, setting localport

### ISSUE THREAD

**Issue by colinbes** [paralect/robomongo#744]
As when manually creating a SSH tunnel using *ssh user@host -L <local port>27018:127.0.0.1:<destination port>27017* is it possible using RoboMongo's ssh support to specify the local port address to be different to the remote port address, it appears that both local and remote ports are setup via 'Connection' tab's *Address:port* setting (unless I am doing something wrong).

~C

**Comment by stennie** [comment]
@colinbes The connection set up is an SSH tunnel, not port forwarding. The details you put in the Robomongo Connection tab with SSH forwarding are the same as how you would connect if logged into the remote server via SSH (i.e. `localhost:27017`).

Robomongo does not setup local port forwarding, so you cannot connect with other apps via the same tunnelled connection.

As an alternative to setting up the tunnel in Robomongo, you could do port forwarding using your `ssh` example and then connect to `localhost:27018`.
