### ISSUE TITLE
reload shortcut does not work

### ISSUE THREAD

**Issue by wallaceturner** [paralect/robomongo#745]
I'm using robomongo 0.8.4

After typing a command in the shell window and hitting Ctrl-R the command is not executed. Am forced always to right click the window with the mouse and select 'Reload'

**Comment by malyavkin** [comment]
@wallaceturner Does Ctrl+Enter work? It works for me

**Comment by wallaceturner** [comment]
yes Ctrl-Enter works. (thank you!) - i'm on windows 8.1. ctrl-r definitely busted for me, have tried it in all contexts, in the shell window, outside, etc

**Comment by stennie** [comment]
FYI, this has been fixed in 0.8.5 (dupe of #551). Windows release coming soon :)
