### ISSUE TITLE
Support for external .js, for UUIDHelpers when using query

### ISSUE THREAD

**Issue by danielHalan** [paralect/robomongo#746]
To be able to use CSUUID() in a Query one needs to inject a js helper,  
mongo --shell uuidhelpers.js
https://github.com/mongodb/mongo-csharp-driver/blob/master/uuidhelpers.js

Full description,
http://stackoverflow.com/questions/8244110/get-bindata-uuid-from-mongo-as-string/8252047#8252047

**Comment by stennie** [comment]
@danielHalan You can load external JavaScript using either `~/.mongorc.js` (will be shared with the `mongo` shell) or `~/.robomongorc.js` (specific to Robomongo).

See also: http://robomongo.org/articles/uuids.html
