### ISSUE TITLE
Whats left for 0.8.5 release?

### ISSUE THREAD

**Issue by toddbluhm** [paralect/robomongo#752]
I was just curious as to whats holding 0.8.5 release up? I was looking through the milestone tickets for 0.8.5 and it seems they are all closed. Just curious as to whats left for that release. 

Thank you :)

**Comment by stennie** [comment]
@toddbluhm Just packaging, testing, and tuits. The last mile is often the hardest because it requires a longer stretch of spare time .. and work/family commitments have to take priority. I have some volunteers helping out this month so would love to finally push out the release.

**Comment by toddbluhm** [comment]
Thanks @stennie! I completely understand about that and totally agree with the work/family priority. Thanks for the update :)

**Comment by stennie** [comment]
@toddbluhm FYI, finally had some lovely round tuits so there are now test builds in the 0.8.5 milestone (OS X: #778, Windows: #779).

**Comment by toddbluhm** [comment]
@stennie Thanks! Ill test it out and let you know if I run into any bugs.
