### ISSUE TITLE
Shift+İ works like Shift+Home in shell

### ISSUE THREAD

**Issue by arcv** [paralect/robomongo#755]
Turkish user here.
Capital "i" is "İ" in Turkish, whenever I try to enter "İ", editor in shell selects all letters before cursor.
![screenshot](https://cloud.githubusercontent.com/assets/1155206/6109026/a8df3f26-b080-11e4-9495-61a80bc798ee.png)

``` 
$ uname -a
Linux 3.16.0-30-generic #40-Ubuntu
```

Due to #750 issue, I couldn't test my changes.

**Comment by stennie** [comment]
@arcv How do you enter that character on your keyboard? It sounds like it's somehow being mapped to the equivalent of Shift + Qt::UpArrow.

**Comment by arcv** [comment]
After updating QT5 and Robomongo to latest version, this issue seems gone. Everything working as expected now.

**Comment by stennie** [comment]
@arcv Thanks for the update. Can you confirm the version of QT5 that is working for you (it may help others who encounter the same issue).

**Comment by arcv** [comment]
Robomongo 0.8.5 with QT 5.4.1 is working great.
