### ISSUE TITLE
Weird output in result box

### ISSUE THREAD

**Issue by shahinism** [paralect/robomongo#756]
I'm using binary version of `robomongo` in my linux box. It was good but lately it is showing the result box this way:

![resultbox preview](https://dl.dropboxusercontent.com/u/25017694/robomongo.png)

What is the problem?

**Comment by stennie** [comment]
It looks like you are loading [mongo-hacker](https://github.com/TylerBrock/mongo-hacker) in your `~/.mongorc.js`.

Assuming you're using a recent version of mongo-hacker, you can disable colours for Robomongo only by adding the following to your `~/.robomongorc.js` file:

``` 
__colorize = false;
```

Alternatively, you can turn off loading of `mongorc.js` via the Options menu in Robomongo.
