### ISSUE TITLE
Cannot build on osx

### ISSUE THREAD

**Issue by luca-saggese** [paralect/robomongo#757]
Hello i'm not able to compile on osx yosemite (10.10.2)
i've followed the guide and installed scons openssl cmake via brew and QT 5.2 via qt's online installer.
i've then export CMAKE_PREFIX_PATH=/Users/user/Qt/5.4/clang_64/lib/cmake.
mkdir target, cd target, cmake ..
and when i've run make i get:

....
[ 12%] Building C object src/third-party/mongodb/src/third_party/libssh2/CMakeFiles/libssh2_third_party.dir/src/mac.c.o
[ 12%] Building C object src/third-party/mongodb/src/third_party/libssh2/CMakeFiles/libssh2_third_party.dir/src/userauth.c.o
Linking C static library liblibssh2_third_partyd.a
[ 12%] Built target libssh2_third_party
Scanning dependencies of target build_mongoclient
[ 12%] Build mongoclient library
scons: Reading SConscript files ...
scons version: 2.2.0
python version: 2 7 6 'final' 0
Checking whether the C++ compiler worksno
c++ compiler not installed!
make[2]: *** [src/CMakeFiles/build_mongoclient] Error 1
make[1]: *** [src/CMakeFiles/build_mongoclient.dir/all] Error 2
make: *** [all] Error 2

any hint?

**Comment by m--stein** [comment]
Hi,
first you need to install Xcode from Mac App Store.
https://itunes.apple.com/de/app/xcode/id497799835?mt=12
Regards
Michael

**Comment by luca-saggese** [comment]
Hi,
thanks for the reply, i've it installed and updated.
i'm now trying installing qt5 via brew..

**Comment by stennie** [comment]
@luca-saggese Qt installed via Brew should be fine .. but for dev I normally use the full [Qt packages](http://www.qt.io/download-open-source/) (including Qt Creator IDE).

I would also check that qmake is in your path and shows the expected version, i.e.:
```
  qmake --version
```

**Comment by stennie** [comment]
@luca-saggese Given there haven't been any updates for almost a fortnight, I'm going to assume you've figured out how to get your build environment working.

If you're still having issues, please feel free to reopen with further details.

If there is anything missing (or that can be improved) in the build instructions, definitely raise a new issue so that can be addressed. 

Thanks!
