### ISSUE TITLE
How do I check an  ISODate field against the current date/time?

### ISSUE THREAD

**Issue by invegat** [paralect/robomongo#759]
rtm is an ISODate
db.mydb.find({rtm:{$lt:new Date()}})  result is "The query was successful, but there are no results to show"

db.mydb.find({rtm:{$gt:new Date()}})  result is "The query was successful, but there are no results to show"

db.mydb.find({rtm:new Date()}) result is "The query was successful, but there are no results to show"

I get the same results if I use new ISODate.

**Comment by invegat** [comment]
After I restarted Robomongo db.mydb.find({rtm:{$gt:new ISODate()}}) worked.

**Comment by stennie** [comment]
@invegat Are you certain you had the same database selected before and after restart? With no parameters given `new Date()` and `new ISODate()` should return the same object (an ISODate).

Is the problem reproducible or was this a one off?

**Comment by invegat** [comment]
I am almost certain that Robomongo somehow got into a state where all
queries returned "Scrip executed successfully, but there is no results to
show".   Closing and opening Robomongo fixed this problem.   So far this is
a one off.

**Comment by stennie** [comment]
@invegat Not sure how to reproduce this. Please reopen with additional details (including your O/S and Robomongo version) if it's possible to recreate.

Thanks!
