### ISSUE TITLE
Timestamps being handled incorrectly

### ISSUE THREAD

**Issue by WadeG-Findly** [paralect/robomongo#760]
This could be down to my lack of knowledge around timestamps, but I am 99% sure timestamps used to be handled differently. Consider the following : 

Input : 
print(new Timestamp(1424313222, 1));

Output : 
{
    "value" : Timestamp(1424313, 1)
}

The input timestamp was taken from the oplog so I know that it's a valid timestamp. Infact, if I write the timestamp from outside robomongo (e.g. an application or from the command line), it works fine.

**Comment by stennie** [comment]
I tracked down the upstream issue for this: [SERVER-7718: Timestamp constructor in shell should take seconds instead of milliseconds](https://jira.mongodb.org/browse/SERVER-7718).

This will be fixed with the merge for #520 (updating to the latest mongo shell).

**Comment by schetnikovich** [comment]
@WadeG-Findly This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
