### ISSUE TITLE
needs export button for the results of queries

### ISSUE THREAD

**Issue by contractorwolf** [paralect/robomongo#761]
right now I can view the results in a few different formats but I cant export the data in that format.  What I think would make most sense is that if you are looking at your data results in the table mode you should be able to export it as an excel spreadsheet (or CSV if the spreadsheet is too complicated to do).  Even a copy/paste that would allow you to select the results set would work but you really cant do anything with the results except export as .js.

**Comment by stennie** [comment]
@contractorwolf Thanks for the feature suggestion. There's an existing Export to CSV feature request (#348) which includes a JavaScript `toCSV` workaround that might be useful in the interim.

**Comment by D1no** [comment]
This is not really a duplicate. There is no semantic reason why you can select, but not copy - or do anything at all - with the highlighted values in the table-mode gui.

Please enable the table-viewer to pass on the values for copy pasting into spreadsheets. Pointing to a shell workaround does not address the gui-shortcoming.

![image](https://cloud.githubusercontent.com/assets/2397125/7064140/f477ea3e-deb4-11e4-99c9-0afaf97063e3.png)

![image](https://cloud.githubusercontent.com/assets/2397125/7064211/75af2cb6-deb5-11e4-94c5-9c9241f2e12d.png)

![image](https://cloud.githubusercontent.com/assets/2397125/7064214/7e8a799e-deb5-11e4-87ad-b3ce199f70e3.png)

**Comment by stennie** [comment]
@D1no It's a duplicate of two feature requests:
 - "option to export to CSV" is #348 
 - "copy selected values in tree/table view" is #669

**Comment by D1no** [comment]
Thanks @stennie. Its indeed a duplicate of #669 - hope this gui ux-irritation finds recognition.
