### ISSUE TITLE
Add support for SCRAM-SHA-1 authentication (MongoDB 3.0+)

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#766]
Related to #520 (updating the shell to 3.0), but adding here as an explicit placeholder for those searching.

Until this issue is resolved, Robomongo only supports users created with the older MONGODB-CR authentication.

Impact is:
 - users migrated from previous versions of MongoDB to 3.0 will still be able to authenticate
 - new users created in MongoDB 3.0 with SCRAM-SHA-1 authentication will *not* be able to authenticate

**Comment by dstrickland-mdl** [comment]
You talked about a fork before christmas.  Any idea of the status?

**Comment by stennie** [comment]
@dstrickland-mdl Sorry, missed notification on your comment here.

Have finally had some time & tuits to get the 0.8.5 releases packaged this week, so getting that out of the way in order to focus on [0.9.0 release](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0) with MongoDB 3.0 changes. I hadn't built all of the release packages before, but now have the environments set up so the next round will be much less painful :).

I have to cleanup & rebase my WIP for 3.0, but have rough code integration done (client & shell updates). I'll definitely be looking for testers as this is the most significant amount of code change in a long while.

If you'd like to help sanity check the 0.8.5 release, I've [created issues](https://github.com/paralect/robomongo/issues?q=milestone%3A%22Robomongo+0.8.5%22+is%3Aclosed++%22create+0.8.5%22) with preview packages linked. Unfortunately 0.8.5 doesn't include any 3.0 changes, but there have been a lot of other improvements: https://github.com/paralect/robomongo/blob/master/whats-new.txt.

**Comment by stennie** [comment]
A workaround of downgrading authentication has been noted elsewhere (although it *only* addresses MongoDB 3.0 auth compatibility, not WiredTiger support). Best practice would be to use updated drivers and tools with full compatibility.

You can downgrade the authSchema using:

```
// Use MongoDB 2.6 auth schema (default auth mechanism: MONGODB-CR)
use admin;
db.system.version.save({ "_id" : "authSchema", "currentVersion" : 3 })
```

Any users created should now use the older MONGODB-CR authentication.

**NOTE**: This won't change the credentials for any existing users, so you will need to [change their passwords](http://docs.mongodb.org/manual/tutorial/change-user-password/).

To find users with SCRAM-SHA-1 auth:
```
use admin;
db.system.users.find({ "credentials.SCRAM-SHA-1" : { $exists: true}}, { user: 1, db: 1})
```

To find users with the older MONGODB-CR auth:
```
use admin;
db.system.users.find({ "credentials.MONGODB-CR" : { $exists: true}}, { user: 1, db: 1})
```

**Comment by csimonadorf** [comment]
Could we get a backport for this once it's fixed before the 0.9 release? This is a major roadblock for me right now.

**Comment by tim-to** [comment]
I switched to use mongochef instead of waiting 


     On Wednesday, June 17, 2015 9:13 AM, csimonadorf <notifications@github.com> wrote:
   
 

 Could we get a backport for this once it's fixed before the 0.9 release? This is a major roadblock for me right now.—

**Comment by iboxgithub** [comment]
+1 this will be useful =)

**Comment by albsala** [comment]
+1 and thanks for the workaround

**Comment by brifordwylie** [comment]
+1

**Comment by joelkim** [comment]
+1

**Comment by mirchow** [comment]
A backport of support SCRAM-SHA-1 would indeed be so welcome, as we upgraded databases and cannot use this tool anymore. Any ETA on 0.9 release btw? Thanks

**Comment by jdarling** [comment]
Any word on a fix for this?  We are migrating to MongoDB 3.0.4 and this is stopping us from using RoboMongo to work against the cluster.

**Comment by waelrammo** [comment]
+1

**Comment by hossein** [comment]
Can I ask if this is checked in into your repo yet?

If you at least push the 0.9 beta sources someone would be interested to backport it.

Please take into account people's interest on this bug vs other topics, as well as vote count on this [StackOverflow question](http://stackoverflow.com/questions/29006887/mongodb-cr-authentication-failed).

**Comment by narzero** [comment]
+1

**Comment by jamesabbottsmith** [comment]
+1

**Comment by mattisx** [comment]
+1! <3

**Comment by men232** [comment]
+1

**Comment by bmcollier** [comment]
+1

**Comment by ajutras** [comment]
+1

**Comment by moattarwork** [comment]
+1

**Comment by valencianok** [comment]
+1

**Comment by lukaszpaczos** [comment]
+1

**Comment by gregthegeek** [comment]
+1

**Comment by manikandants** [comment]
:+1:

**Comment by klemensz** [comment]
+1

**Comment by siyuanWang** [comment]
+1 thanks, save me.

**Comment by mattisx** [comment]
Not to be douchy (Robomongo is a great project), but I recently gave up waiting and have been using Mongochef since. Working well, seems powerful and the UI is good (except for some minor retina issues).

**Comment by BeardedSteve** [comment]
In the same way as @mattisx - I've found Robomongo super useful but I can't live without these feature and I too have gone all MongoChef. Real shame.

**Comment by Entwanderer** [comment]
Same here... just downloaded mongochef for testing...
+1

**Comment by stefan-kolb** [comment]
:+1:

**Comment by b0ric** [comment]
+1
looking forward to have this feature!

**Comment by 0utsider** [comment]
+1

**Comment by sztefania** [comment]
+1

**Comment by assaframan** [comment]
+1

**Comment by kmanamcheri** [comment]
+1

**Comment by shamruk** [comment]
this repo looks dead, moving to MongoChief. i liked this app

**Comment by jonatassaraiva** [comment]
+1

**Comment by fariza** [comment]
+1

**Comment by harrylaou** [comment]
+1

**Comment by gizmo410** [comment]
+1

**Comment by LNWPOR** [comment]
+1

**Comment by Scarysize** [comment]
+1

**Comment by moconnell** [comment]
+1

**Comment by pbozzi** [comment]
+1

**Comment by sauron918** [comment]
+1

**Comment by mariobaldini** [comment]
+1

**Comment by georgiosd** [comment]
+1

**Comment by pritamkarmakar** [comment]
+1

**Comment by AddoSolutions** [comment]
+1

**Comment by jamesabbottsmith** [comment]
I still think Robomongo is a great product and wish this issue was resolved. 

Mongo has recently released Compass which seems to do a similar job though (with a few extra features). I haven't used it extensively but it may be worth checking out. 

https://www.mongodb.com/products/compass

**Comment by BenC-** [comment]
+1

**Comment by bdiegel** [comment]
+1

**Comment by baldiri** [comment]
+1

**Comment by bdipak** [comment]
+1

**Comment by tomchomiak** [comment]
+1

**Comment by thirdy** [comment]
+1

**Comment by lianyi** [comment]
+1

**Comment by anorsich** [comment]
@lianyi @thirdy @tomchomiak I have awesome news for all of you. Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) supports SCAM-SHA-1/MONGODB-CR authentications. You can select proper authentication from dropdown when creating connection to the mongodb. Let us know if work for you. Feel free to reopen this ticket if it does not.

**Comment by TobyMaxham** [comment]
+1

**Comment by manikandants** [comment]
Thanks :+1: working great!!! Back to Robomongo..

**Comment by anorsich** [comment]
@manikandants Awesome! (dancing)

**Comment by tomchomiak** [comment]
woo-hoo!

**Comment by dharshanr** [comment]
Will this work in a sharded cluster since db.system.version is not writable?
