### ISSUE TITLE
Right Mouse Button Annoyance

### ISSUE THREAD

**Issue by sheavner** [paralect/robomongo#768]
You'll probably tell me this is a QT issue, but ...

I'm trying to view or edit a document from the query results window.   When I use the trackpad, I right click on the row I want to view, move the mouse, and release the button when I've selected the appropriate menu item.  [r-mouse-down, move, r-mouse-up].    This doesn't register an event which activates the selected menu item.   I need to do [r-mouse-down, r-mouse-up. move. r-mouse-down, r-mouse-up]  the second mouse event chain can actually be l-mouse-down, l-mouse-up.

Anyhow, the need for a second mouse down event is annoying.

Robomongo 0.8.4 on OSX Yosemite

**Comment by malyavkin** [comment]
It's looks like OSX-only issue because it works fine in Win version (RMB press - move - RMB release)

**Comment by stennie** [comment]
@sheavner Possibly a Qt issue, although I can't reproduce with 0.8.4.

Can you try with 0.8.5 release which has updated Qt: https://www.dropbox.com/s/8lawkd1ka7sgia9/Robomongo-0.8.5-x86_64.dmg?dl=0

Thanks!

**Comment by sheavner** [comment]
I no longer see the issue in the 0.8.5 binary you provided.   It looks good to me.

p.s. the about box in 0.8.5 shows (c) 2013.   maybe it should read 2015?

**Comment by stennie** [comment]
> I no longer see the issue in the 0.8.5 binary you provided. It looks good to me.

@sheavner: Great, thanks for confirming.

> p.s. the about box in 0.8.5 shows (c) 2013. maybe it should read 2015?

Already had a note to check on the copyright front .. wasn't sure what the proper requirements are (year of initial creation, range of years with contribution, current year). Opinions seem mixed there with the various IANAL disclaimers.
