### ISSUE TITLE
Crash every time the stop button is clicked.

### ISSUE THREAD

**Issue by medmr1** [paralect/robomongo#770]
any time I run a long-running query in robomongo, and am presented with a clickable "stop" button, presumably to stop the query, clicking the button causes the app to crash. Doing anything else while the query is running is impossible, so usually I have to force quit the application and restart from nothing.

on OSX, latest stable release - was a problem with the previous release, too.

**Comment by stennie** [comment]
@medmr1 Thanks for reporting. There's a similar issue already: #454. Can you comment there with an example of the query that causes Robomongo to crash?

I can't reproduce the problem trivially (i.e. stop appears to work for me) so any extra details or steps to reproduce would be helpful. I have seen occasional issues with multiple tabs open (execution of simultaneous queries blocks as per #661).

Thanks!
