### ISSUE TITLE
Can't Connect to Mongo 3.0 DB server

### ISSUE THREAD

**Issue by jmategk0** [paralect/robomongo#771]
Hello,

I just upgraded a few of my MongoDB instances to version 3.0 and I can not connect to any of them from robomongo. My older instances are version 2.6 and I have no issues connecting with the following syntax "serverName.local:port", this syntax does not seem to work with the version 3 shell. 

In the terminal I can only connect to my local servers using the following: syntax "mongo serverName --port 27017" and robomongo's UI always seems to store addresses in the format "serverName:port" and this does not work in the terminal. I'm using Ubuntu 14.04 on client and server operating systems, mongo was installed from the .deb packages from MongoDB inc. 

Is their a way around this issue i'm unaware of? Does this have anything to do with the robomongo shell being 2.4?

Thanks

**Comment by iiwaasnet** [comment]
I can connect, although, Collections, Functions, etc in the left tree are not displayed. Nevertheless, it's functioning somehow, i.e. can execute commands and get results.

**Comment by stennie** [comment]
If you are using new 3.0 features, these are not supported in Robomongo yet.

Specifically:
 - Will not be able to list collections & indexes if using WiredTiger storage engine (as per @iiwaasnet)
 - Will not be able to authenticate against users with the new SCRAM-SHA-1 auth method

Compatible features are being tracked against a 0.9.0 development milestone: https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0

**Comment by iiwaasnet** [comment]
**@stennie**: thanks!

**Comment by jlpedrosa** [comment]
Hi All,

there's a workaround that can be done at server side: 
https://jira.mongodb.org/browse/SERVER-17459

**Comment by nathanhornby** [comment]
Any timeline on getting 3.0 support in? I'm struggling to find a GUI that actually works atm…

**Comment by stennie** [comment]
@nathanhornby Working on 3.0 support at the moment for Robomongo [0.9.0 milestone](https://github.com/paralect/robomongo/milestones/Robomongo%200.9.0). No ETA yet as this is not a commercial project or anyone's day job ;-).

There are some other admin UIs listed at [mongodb-tools](http://mongodb-tools.com/) if you're looking for alternatives. Some of those have been updated with 3.0 support. MongoChef has been mentioned a few times as being similar to Robomongo and the latest version does have support for MongoDB 3.0.

**Comment by nathanhornby** [comment]
Of course, totally appreciated, just wondered if there were any target dates. I'll keep my eyes peeled.

**Comment by danielHalan** [comment]
Is there any backlog somewhere on parts that need's updating?, if one would find some extra time to pitch in...

**Comment by bgSosh** [comment]
There seems to be quite a lot of stuff in the 0.9.0.  Might it not be possible to move mongo3 support into some 0.8.x release?  It's so fundamental that I think lots of people are going to have to move to different tools if it takes months.  It's a pity because I was very happy with robomongo (the first time I can say that about a mongodb management ui).

**Comment by iiwaasnet** [comment]
@bgSosh: Absolutely support!!!

**Comment by 4lifedev** [comment]
Any news on 0.9.0?
Please support this project.  I tried all kind of tools for MongoDB, Robomongo is by far the best one.

**Comment by brifordwylie** [comment]
+1 on this... love Robomongo... but need to use it on a Mongo 3 DB Server

**Comment by qtisan** [comment]
222222
needs 3.0 support 
please my powerful godlike
I love you so much correctly 
I cannot fight myself out from your warm arm

**Comment by Grievoushead** [comment]
+1

**Comment by throrin19** [comment]
+1000
We migrate all of our servers on mongo 3.0 and the most powerfull editor is robomongo. 
We can't migrate in other editor

**Comment by lealife** [comment]
+1

**Comment by nonameolsson** [comment]
+1

**Comment by vladgaus** [comment]
+1 Robomongo very nice tool

**Comment by ssreekanth** [comment]
:+1:

**Comment by samosfator** [comment]
+1

**Comment by fuzaro** [comment]
+1

**Comment by fitz123** [comment]
+1

**Comment by jonathankeebler** [comment]
+1

**Comment by michalzwolinski** [comment]
+1 :)

**Comment by Crokus** [comment]
MongoLab just upgraded their sandboxes to 3.0.6 - huge +1.

**Comment by flexmotion** [comment]
+1

**Comment by Mura-Mi** [comment]
++;

**Comment by thelfensdrfer** [comment]
Instead of "+1"s it is probably a good idead to donate (http://robomongo.org/backlog) I'm not sure if robomongo is still actively maintained. If not, maybe it is a good idea to switch to an alternative like http://3t.io/mongochef which is free for non commercial use, but not open source i think.

**Comment by leonstel** [comment]
+10

**Comment by metaColin** [comment]
+1 and I donated $5

**Comment by kanpinar** [comment]
+1

**Comment by divmgl** [comment]
1 it's been like seven months man...

**Comment by r-vishnevsky-parc** [comment]
+1

**Comment by gyahalom** [comment]
+3.0

**Comment by tomitrescak** [comment]
MongoHub by then maybe ? ;)

**Comment by alemik** [comment]
1+

**Comment by ApfelUser** [comment]
I am not sure, but I have the slight feeling that @stennie doesn't work at Paralect anymore.

**Comment by ikb42** [comment]
Looks like this branch is progressing on the version 3 change:
https://github.com/alexbevi/robomongo

Anyone using this version yet?

**Comment by fielding34** [comment]
+1

**Comment by PavelPolyakov** [comment]
+1

**Comment by xiongsongsong** [comment]
+1

**Comment by Nexum** [comment]
+1

**Comment by JesusIslam** [comment]
+1

**Comment by berus97** [comment]
+1

**Comment by microlv** [comment]
+1

**Comment by IlyaMokin** [comment]
+1

**Comment by mathieukempe** [comment]
+1

**Comment by CreepyGnome** [comment]
What is the status of this 8 month old issue on RoboMongo supporting 3.0.x? Our cloud provider has moved to 3.0.x and we can no longer use RoboMongo and have had to switch to other solutions to keep up with them.

**Comment by augmenter** [comment]
+1

**Comment by monday-ch** [comment]
+1

**Comment by CihanAksoy** [comment]
+1

**Comment by willzeng** [comment]
+1

**Comment by tanaydin** [comment]
+1 * 1000

**Comment by GabrielchenCN** [comment]
＋10086

**Comment by b1wan** [comment]
+1

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.

Thank you all for patience!

**Comment by nathanhornby** [comment]
Woop! Thanks for the effort from all the contributors.
