### ISSUE TITLE
Aggregation option { explain: true } doesn't  bring information about pipeline execution

### ISSUE THREAD

**Issue by wagnerjs** [paralect/robomongo#773]
When i run:

``` db.collection.aggregation( [ ...my pipeline...], { explain: true } ) ```

result is the same of

``` db.collection.aggregation( [ ...my pipeline...] ) ```

Mongo shell shown the correct result. 

Regards

**Comment by stennie** [comment]
@wagnerjs Duplicate of #495. There's an example there of alternate `runCommand()` syntax that will work for passing options to aggregation until #520 is resolved.

Thanks!

**Comment by wagnerjs** [comment]
I did not find this issue in my search.
Thanks for your time!

Regards

**Comment by anorsich** [comment]
@wagnerjs  Latest [0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/) is based on Mongodb shell 3.2 and support aggregate arguments. Let us know if it worked for you.
