### ISSUE TITLE
Ubuntu build failed

### ISSUE THREAD

**Issue by malyavkin** [paralect/robomongo#774]
I believe I forgot to do something stupid but it fails to compile with following errors:

...
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for C++ include type_traits.h
-- Looking for C++ include type_traits.h - not found
-- Looking for C++ include bits/type_traits.h
-- Looking for C++ include bits/type_traits.h - not found
...
-- Looking for _strtoi64
-- Looking for _strtoi64 - not found
...

CMakeError.log : http://pastebin.com/Kvqut0AQ
CMakeOutput.log : http://pastebin.com/AF3vvaWP  

qmake, scons and openssl are installed and in PATH

edit: Ubuntu 14.04 x64

**Comment by stennie** [comment]
@malyavkin It looks like you're missing some basic libs (eg. pthreads). Can you try: `sudo apt-get install build-essential`?

I suspect you'll get further but still be caught by #733, which I'm looking into at the moment.

**Comment by stennie** [comment]
I've fixed all of the (known) build issues for Ubuntu 14.04. It would be helpful if you can help test the 0.8.5 .deb release package and provide feedback (via a new issue) if you have any problems: https://github.com/paralect/robomongo/issues/782.

If you're still stuck building from source, feel free to reopen this issue.

Thanks!
