### ISSUE TITLE
Add "What's new in Robomongo 0.8.5" page

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#777]

**Comment by yuomtheara** [comment]
how to upgrade?

**Comment by stennie** [comment]
@yuomtheara Working on testing & uploading packages so robomongo.org can be updated. You can download a preview (if available) via the appropriate issue on the [0.8.5 milestone](https://github.com/paralect/robomongo/issues?q=milestone%3A%22Robomongo+0.8.5%22+sort%3Aupdated-desc).

**Comment by yuomtheara** [comment]
so uninstall the old, and then install new.
should be have update option on old.

**Comment by stennie** [comment]
@yuomtheara There is currently no auto-update feature built-in, but it has been suggested: #77, #283.

In general there is nothing to update/uninstall, so should just need an install of the updated version (or replacement of the binary, depending on the install package you are using).

**Comment by stennie** [comment]
Drafted based on https://github.com/paralect/robomongo/releases/tag/v0.8.5; will work with @schetnikovich to push to robomongo.org.
