### ISSUE TITLE
Create OS X 0.8.5 .dmg release

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#778]

**Comment by stennie** [comment]
Preview: https://www.dropbox.com/s/8lawkd1ka7sgia9/Robomongo-0.8.5-x86_64.dmg?dl=0

If you test this out and find any problems, please start a new issue with details. Thanks!

**Comment by stennie** [comment]
+1 OS X 10.10.2

**Comment by petek** [comment]
+1 OSX 10.10.2
