### ISSUE TITLE
Create 0.8.5 64-bit Deb package

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#782]

**Comment by stennie** [comment]
Preview: https://www.dropbox.com/s/sts6zndo0c5eqoi/robomongo-0.8.5-x86_64.deb?dl=0

If you test this out and find any problems, please start a new issue with details. Thanks!

**Comment by stennie** [comment]
NB: updated with fix for #787

**Comment by stennie** [comment]
+1 Ubuntu 14.04.2 (64-bit)
+1 Xubuntu 14.04 (64-bit)
+1 Linux Mint 17 (64-bit)

**Comment by fanxu** [comment]
+1 Kubuntu 14.04.2 (64-bit)

**Comment by sapna1402** [comment]
which one to download for Ubuntu 64bit 
64 bit .deb package for Debian/Ubuntu
64 bit .rpm package for CentOS/RHEL

**Comment by sapna1402** [comment]
Error:
unable to connect to localhost:27017
authorization failed
