### ISSUE TITLE
Create 0.8.5 64-bit RPM package

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#783]
Preview: https://www.dropbox.com/s/8b72f2obzoeirlw/robomongo-0.8.5-x86_64.rpm?dl=0

If you test this out and:
 - find any problems, please [start a new issue with details](https://github.com/paralect/robomongo/issues/new).
 - find all is good, please +1 below with your specific O/S version tested (if it hasn't already been mentioned)

Thanks!

**Comment by stennie** [comment]
+1 CentOS 6.6 (64-bit) - minimal install

**Comment by gavruk** [comment]
Works on Fedora 21

But description looks bad
![image](https://cloud.githubusercontent.com/assets/507195/6650981/e2a696f4-ca3f-11e4-9f06-6186aebf3883.png)

**Comment by stennie** [comment]
Thanks @gavruk! Fixed the description with #796 and updated the RPM.
