### ISSUE TITLE
Create 0.8.5 64-bit Linux .tar.gz archive

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#784]
This seems impractical to use given the dependencies that would have to be manually resolved.

A better alternative would be to build from source.

**Comment by thankjura** [comment]
why wontfix?

**Comment by stennie** [comment]
@thankjura Having just gone through testing & fixing the deps for .deb and .rpm packages .. I don't think it makes sense to put together a tarball release.

Your chances of a successful install are greatly increased by either using a packaged version or building from source.

What Linux distro are you using, and why would you prefer the tarball?

**Comment by thankjura** [comment]
I use gentoo. 
Of course under gentoo ebuild better to write but I have problems building robomongo with qt5.4

P.S. sorry for bad english

**Comment by stennie** [comment]
@thankjura I've been compiling the releases with Qt 5.3.2 .. is that an option for you?

Is there a package for gentoo already? I didn't find in http://packages.gentoo.org/.

**Comment by stennie** [comment]
@thankjura Also, do you happen to have a previous version of Robomongo installed on Gentoo? I'm curious whether the tar.gz download worked for this, and any extra steps involved to get that running properly.

**Comment by thankjura** [comment]
Current version of qt in gentoo == 5.4.1.
I get an error #479. I successful build robomongo with qt5.4 and patch from #479, but romonogo have non native style http://i.imgur.com/ornbgoT.png

**Comment by stennie** [comment]
@thankjura So it looks like you have a version of 0.8.5 built on Gentoo? Issue #479 still needs someone to look into a proper fix so non-native style is expected.

**Comment by thankjura** [comment]
@stennie Yes, I built robomongo-0.8.5 on gentoo from git

**Comment by stennie** [comment]
@thankjura Great! I'm going to close this again. FYI, I've added #790 (Create Gentoo package for Robomongo) to see if there are others who might be interested in this.
