### ISSUE TITLE
Windows packages missing OpenSSL libs: ssleay32.dll, libeay32.dll

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#786]
Apparently Windows users without OpenSSL installed are getting error on missing `ssleay32.dll ` (although this wasn't included in 0.8.4 package).

Related to: #779 #781

**Comment by stennie** [comment]
Adding `ssleay32.dll` and `libeay32.dll` to the Windows downloads should fix this issue (thanks @gavruk!).

**Comment by gavruk** [comment]
You should add this 2 files:
https://dl.dropboxusercontent.com/u/14053604/ssleay32.dll
https://dl.dropboxusercontent.com/u/14053604/libeay32.dll
to `C:\Program Files (x86)\Robomongo`
But we need to bundle them to Windows installation package

**Comment by stennie** [comment]
Yes, I have the correct versions from the OpenSSL-win32 .. which appears to be in cmake search path (from `FindOpenSSL.cmake`). Not sure why this wasn't needed before (newer SSL?) but will fix.

Thanks for catching!

**Comment by azarzycki** [comment]
Since this issue is the #1 Google result for "openssl libeay32.dll" and "openssl ssleay32.dll" it should be noted that only OpenSSL < 1.1 ships with these files. Many windows projects (not just robomongo) depend on the these 1.0.x series files, and if you just go for the highest version number available you won't find them.

**Comment by aedwards15** [comment]
If I may ask @azarzycki : what happened to them, then? What do we use instead?

**Comment by azarzycki** [comment]
I don't have personal knowledge regarding the motivation for the OpenSSL team to switch to different libraries. There is probably a public discussion about this. 

I just wanted to point out that 1.1.x OpenSSL does not include these libraries for the benefit of everyone who might find this page when searching for libeay32.dll and ssleay32.dll, even if they are not using Robomongo. There are plenty of other projects that integrate OpenSSL in a similar manner.

According to the [OpenSSL site](https://www.openssl.org/source/) 1.0.x is OpenSSL's LTS release and will be maintained until 2019, so you can still **download the latest 1.0.x release** for quite some time.

**Comment by willkydd** [comment]
Managed to fix it! Went to https://slproweb.com/products/Win32OpenSSL.html and downloaded Win32 OpenSSL v1.0.2p (no other version worked). Now it all works. I think this library needs to be bundled with the launcher because it doesn't come installed with versions of OpenSSL beyond 1.1.
