### ISSUE TITLE
Publish 0.8.5 to website

### ISSUE THREAD

**Issue by ankitjaininfo** [paralect/robomongo#789]
I just found that 0.8.5 is release 2 days ago. Appreciate if anyone can build the installer for linux.

**Comment by stennie** [comment]
@ankitjaininfo We're testing the Linux packages at the moment (you'll notice the robomongo.org homepage hasn't been updated yet :).

What Linux distro & version are you using ? Would appreciate any help testing.

You can try a .deb from: #782. RPM will be added to #783.

**Comment by ankitjaininfo** [comment]
Thanks! I will install and use right away this new version. Will report any issue, if any.
I am using Ubuntu 12

**Comment by stennie** [comment]
@ankitjaininfo Also FYI, I saw some bot tweets about 0.8.5 being released but I'm not sure where those came from. I'd consider "released" when we finish testing the packages and update the robomongo.org site to announce properly :)
