### ISSUE TITLE
When editing a document double values get converted to Int32 

### ISSUE THREAD

**Issue by juanjdlt** [paralect/robomongo#791]
I'm using OS X Yosemite 10.10.2
Robomongo v.0.8.4
MacBook Pro (13-inch, Mid 2012)

Here's a small example where this situation happens. Please look at the price_money_value.2.value, is a  DOUBLE type and the in the edit window it get parsed/converted to INT..
reference: http://cl.ly/0l1L3R2c332i

**Comment by stennie** [comment]
@juanjdlt I believe this is a dupe of #622. Can you test with the 0.8.5 release, which should have this fixed: https://github.com/paralect/robomongo/issues/778?

Thanks!

**Comment by juanjdlt** [comment]
Hi @stennie, just download the new release and its working perfect.  Thanks
