### ISSUE TITLE
properly displaying CJK characters

### ISSUE THREAD

**Issue by yoki** [paralect/robomongo#795]
CJK characters are not displayed at all in all views. Probably we have to change fonts. Is there any workarounds, like changing system default fonts? I am using Robomongo 0.8.4 with Mac OS X 10.10.2.

Robomongo:
![screen shot 2015-03-14 at 4 15 23 pm](https://cloud.githubusercontent.com/assets/159776/6650739/589dbad4-ca65-11e4-945f-0cb13fbe9b7a.png)

Bash:
![screen shot 2015-03-14 at 4 17 06 pm](https://cloud.githubusercontent.com/assets/159776/6650742/9bd6e726-ca65-11e4-9491-a684eaadbdbb.png)

**Comment by stennie** [comment]
@yoki This should be fixed in the Robomongo 0.8.5 which we're testing at the moment.

Can you try the DMG on #778 and confirm?

Thanks!

**Comment by yoki** [comment]
Now CJK are displayed properly! Thanks a lot!
