### ISSUE TITLE
Refactor SSH support

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#798]
SSH support is currently hacked directly into the DBClient classes from the upstream MongoDB repo. This adds complexity for merging updates, and the current implementation is less secure & robust than setting up ssh forwarding outside of Robomongo (eg #445, #484, #681, #686).

**Comment by anorsich** [comment]
@stennie SSH/SSL support was disabled in latest release, let's keep track implementation progress in this ticket #1002.

**Comment by stennie** [comment]
@anorsich SSH and SSL support should be separate issues. SSL is a requirement for connecting to many deployments; integrating SSH support is a convenience (tunnels and forwarding can always be set up independent of Robomongo).

**Comment by anorsich** [comment]
@stennie For the windows users ssh tunel is something they never used, so I think we still gonna have ssh support within Robomongo, but I do agree with you that it should be separate issues. I think we have one for ssl for sure, I am planning to do further issues clean up and gonna separate them out. Thank you!
