### ISSUE TITLE
release binary for 0.8.5

### ISSUE THREAD

**Issue by dblado** [paralect/robomongo#799]
Can you put a new binary up for the different platforms?

**Comment by stennie** [comment]
@dblado You can find binaries attached to the relevant issues in the [0.8.5 milestone](https://github.com/paralect/robomongo/issues?q=milestone:%22Robomongo+0.8.5%22+%22create+0.8.5%22+label:task).

The robomongo.org site will be updated soon with these.

What specific O/S & package are you looking for ?

**Comment by dblado** [comment]
OSX -- Thanks! I see the updates on .org
