### ISSUE TITLE
Consider removing Qt4 support

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#800]
Qt4 support was [re-added](https://github.com/paralect/robomongo/commit/e3219f389257da65306fcc433ceb579cdb3b8c66) to work around a Qt5 bug on Linux (#443 =>  [QTBUG-32254](https://bugreports.qt.io/browse/QTBUG-32254)).

The upstream bug claims to be resolved as Qt 5.4.0, so I think we should confirm if that is the case and consider removing Qt4 support from the build.

This will simplify the number of tests cases for packaging and avoid conditional code when addressing Qt5-specific issues such as #479.

**Comment by oz123** [comment]
QT4 support is actually not existing after this commit 9d4957a9686d7dc7e6131cda910b626822ba2b7e.

**Comment by anorsich** [comment]
@stennie We use QT 5.5 now, closing this one.
