### ISSUE TITLE
Test upgrade to Qt 5.4.1

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#801]
Robomongo 0.8.5 release packages were built with Qt 5.3.2 for consistency.

Qt 5.4.0 claims to fix one of the more annoying bugs for Linux users: #443.

Should test builds with latest Qt 5.4.x (currently Qt 5.4.1) as part of the 0.9.0 dev cycle.

**Comment by anorsich** [comment]
@stennie Latest release [0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/) built based on QT 5.5, so I think we can close this ticket now.
