### ISSUE TITLE
Cannot install 0.8.5 on Windows

### ISSUE THREAD

**Issue by mausch** [paralect/robomongo#802]
Download http://robomongo.org/files/windows/Robomongo-0.8.5-i386.exe from the homepage. When I run it, I get the following integrity check error:

![Imgur](http://i.imgur.com/dYJyhhW.jpg)

**Comment by gavruk** [comment]
I just downloaded and successfully installed this file on Windows 8.1 x64

**Comment by mausch** [comment]
Must have been some transient issue, it's working now for me too.
For the record, I got the same message on two machines: my local machine (Windows 8.1 x64) and a EC2 instance (Windows 2012 x64)
