### ISSUE TITLE
Copy Collection to Database feature

### ISSUE THREAD

**Issue by ShadowZ0** [paralect/robomongo#807]
This is missing in 0.8.5 (and 0.8.4 is working fine) (under OS-X)

**Comment by stennie** [comment]
@ShadowZ0 The implementation was unfortunately buggy & particularly problematic with auth enabled (see #398, #444, #552, #582, #644, #711, ...). It was removed in 0.8.5 and will be re-added when it works reliably.

In the interim there are a few functions you can use in the shell for copying collections/databases:

 * [`db.cloneCollection(from, collection, query)`](http://docs.mongodb.org/v2.4/reference/method/db.cloneCollection/)

 * [`db.collection.copyTo(newCollection)`](http://docs.mongodb.org/v2.4/reference/method/db.collection.copyTo/). As per the documentation note, this uses `eval()` and will block other operations on your `mongod` instance. This command is also deprecated as at MongoDB 3.0.

 * [`db.copyDatabase(fromdb, todb, fromhost, username, password)`](http://docs.mongodb.org/manual/reference/method/db.copyDatabase/#db.copyDatabase).

**Comment by shamruk** [comment]
Please add this feature back

**Comment by rodrigopolo** [comment]
I was looking for this option on the menu like crazy until I decided to look on github if there is something going on, I was right :-/
