### ISSUE TITLE
Pin and unpin causes taskbar icon to change and right-clicking it to stop working

### ISSUE THREAD

**Issue by eli-b** [paralect/robomongo#811]
On Windows 8.1 64-bit, after upgrading from 0.8.4 to 0.8.5.
The icon I get when opening Robomongo is the old one. After pinning the program to the taskbar and unpinning it the icon changes to the new robot icon, and right-clicking on the program in the taskbar doesn't work anymore.

**Comment by stennie** [comment]
@eli-b Thanks for reporting. If you had a previous version of Robomongo I gather the icon may be cached on Win8.

Will have to test the pinning behaviour; not doing anything special there as far as I'm aware.

**Comment by eli-b** [comment]
Restarting my computer fixed the problem. Now I get the new robot icon as
soon as I open the program,
and pinning works correctly.
Maybe you should just advise people to restart their computer after
installing the new version.

**Comment by stennie** [comment]
@eli-b Sounds like this is just a caching problem; hopefully there is a better way to fix than requiring a reboot.

It looks like there are some tools for doing so, eg: [How to change a pinned app’s shortcut icon on the Taskbar and refresh Explorer icon cache](http://winaero.com/blog/how-to-change-a-pinned-apps-shortcut-icon-on-the-taskbar-and-refresh-explorer-icon-cache/).

**Comment by juliashibalko** [comment]
Hi @eli-b! Could you please try to reproduce the issue using the latest [Robomongo version](http://blog.robomongo.org/robomongo-rc9/)? I didn't manage to replicate it, so seems that issue can be closed

**Comment by eli-b** [comment]
It doesn't reproduce for me either. I guess the issue is fixed!

‫בתאריך יום ב׳, 13 ביוני 2016 ב-11:56 מאת ‪Julia Shibalko‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by juliashibalko** [comment]
@eli-b Thank you! Glad to hear that!
