### ISSUE TITLE
Support settings for font family and size configuration

### ISSUE THREAD

**Issue by greenlaw110** [paralect/robomongo#813]
When I open robomongo on my mint (17.1 Cinnamon) it display very big font. I hope I could change the settings for the font size and also font family coz I want to use a monospace font for content area

![image](https://cloud.githubusercontent.com/assets/216930/6768961/030b69a6-d0da-11e4-99a6-b1810bb60fe7.png)

**Comment by stennie** [comment]
@greenlaw110 Thanks for the feedback! There's already an open issue to add UI to allow changing fonts (see #645).

FYI, there's also an open PR from @craigkelly which might help (if you want to build from source). It's part of the work needed for #645 and will be merged for the Robomongo 0.8.6 release; allows you to set a font preference directly in the `robomongo.ini` file.
