### ISSUE TITLE
UI: Add support for options when creating a collection

### ISSUE THREAD

**Issue by stennie** [paralect/robomongo#818]
The [db.createCollection()](http://docs.mongodb.org/manual/reference/method/db.createCollection/) method has the following prototype form:

``` javascript
db.createCollection(<name>, { capped: <boolean>,
                              autoIndexId: <boolean>,
                              size: <number>,
                              max: <number>,
                              storageEngine: <document> } )
```

**Comment by PeterNotenboom** [comment]
+1 for creating a capped collection.

**Comment by juliashibalko** [comment]
As this feature was already implemented in Robomongo version RC9. I'm closing this ticket as "fixed".
You may see Robomongo blog for an overview: 
http://blog.robomongo.org/robomongo-rc9/
