### ISSUE TITLE
Problem in adding documents

### ISSUE THREAD

**Issue by pierpaolocira** [paralect/robomongo#820]
Hi,
using Robomongo 0.8.4 on MacOSX 10.10 there is a small problem importing document/s into a collection (rigth click -> insert document...).

If there is a new line character after the last closing curly bracket, it gives the error "Unable to parse JSON: Expecting '{', at (1, 1).".

I know the new line character is not part of the document itself, but this is an usability issue: it appens if a user just open the interface, select all and directly paste over its document/s content (a fast ctrl+a/ctrl+v operation, due to an incorrect copy from its source file).

Example:
--
{
  "test" : 1  
}

--

For a better user experience, I think Robomongo should trim external spaces and newlines, or at least should provide an error message more useful (because the problem isn't due to an unexpected "{" at (1,1) position).

Thank you.

**Comment by stennie** [comment]
@pierpaolocira Can you update to Robomongo 0.8.5 and retest? I believe this is a duplicate of #544, which was fixed in 0.8.5.

Thanks!

**Comment by pierpaolocira** [comment]
@stennie Thank you for supporting.
You're right, apologies!
Bye
