### ISSUE TITLE
Paste to command widget when clipboard is empty

### ISSUE THREAD

**Issue by gavruk** [paralect/robomongo#825]
If you open collection and click `CTRL+A, CTRL+V` when command widget is in focus and clipboard is empty, Robomongo freezes. The only think I can do is to kill process.

I am using Robomongo 0.8.5 on Windows 8.1 x64

**Comment by stennie** [comment]
@gavruk Is this easily reproducible? Are you only experiencing this issue on Windows, or have you tried OS X as well?

**Comment by gavruk** [comment]
I don't know why, but right now I cannot reproduce. But 2 days ago I reproduced this multiple times.

**Comment by gavruk** [comment]
Cannot reproduce this
