### ISSUE TITLE
Mac version - Connections not saved

### ISSUE THREAD

**Issue by jossi** [paralect/robomongo#830]
After creating a new connection and quitting, the connection is not saved. I have to enter connection information on each run.

**Comment by stennie** [comment]
@jossi Can you check if there's a `~/.config/robomongo` directory created, and what the permissions are? The preferences are saved to a `robomongo.json` file in that directory.

Also, can you confirm the version of Robomongo you are using? This sounds like the same issue as #636, but if you're using Robomongo 0.8.5 there should be an error logged if preferences cannot be saved.

**Comment by jossi** [comment]
I am using version  0.8.4
There is no ~/.config/robomongo

I will upgrade to 0.8.5

**Comment by jossi** [comment]
Installed 0.8.5 same issue, and also after connecting nothing happens (I get a blank screen)

**Comment by stennie** [comment]
@jossi Is there anything relevant in the Robomongo log ? (click on "Logs" button at bottom left of window)

Can you create the directory: `mkdir -p ~/.config/robomongo` ?

**Comment by jossi** [comment]
Created directory and now log is clean:
2015-03-31 15:23:54: Connecting to localhost:27017...
2015-03-31 15:23:56: Settings saved to: /Volumes/Main/Users/jossif/.config/robomongo/robomongo.json

but in this version, I get a blank screen after connecting :(

**Comment by jossi** [comment]
It is working after a restart.

**Comment by vitorspencer** [comment]
Strange: I just reinstalled my MacOS with Sierra and had the same issue. Needed to create the ~/.config/robomongo and assign read/write permissions to make it work.
