### ISSUE TITLE
Text mode number values

### ISSUE THREAD

**Issue by dominikbulaj** [paralect/robomongo#831]
Hi,

In latest version (0.8.5) I found that in Text mode all number values are changed to once used "e". 
So for example ```db.currentOp()``` returns ``"opid" : 1.00189e+009,`` and adding indexes ```"progress" : {
                "done" : 4.5809e+006,
                "total" : 6.71846e+006
            }```

Sadly such a ``opid`` won't work with e.g. ``db.killOp()``. Could it be possible to return those values not changed? (Actually they're not changed in Tree mode).

**Comment by stennie** [comment]
@dominikbulaj Thanks for reporting! Don't believe there was any intentional change there; perhaps your opids have overflowed (not sure what they are being interpreted as). What are the original values?

**Comment by stennie** [comment]
@dominikbulaj It would also be helpful if you can confirm this wasn't a problem with Robomongo 0.8.4. Thanks!

**Comment by dominikbulaj** [comment]
OK so opid maybe is big number - 1001889785
but progress have something that should fit into Int32 (4376874 & 6718459).

Please find attached 2 screenshots from 0.8.4 & 0.8.5 
![screenshot_1](https://cloud.githubusercontent.com/assets/1233407/6932554/62d637e2-d81b-11e4-8d47-9ec6901fc1ab.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/1233407/6932555/62d85158-d81b-11e4-8915-5db58a8a84a6.png)

**Comment by dominikbulaj** [comment]
OK, opid maybe is big number - 1001889785
but progress have something that should fit into Int32 (4376874 & 6718459).

Please find attached 2 screenshots from 0.8.4 & 0.8.5 

![screenshot_2](https://cloud.githubusercontent.com/assets/1233407/6932581/aba2d0ac-d81b-11e4-82f1-8189ab2c3fee.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/1233407/6932583/ade53ff8-d81b-11e4-842c-9b1ecf6937ad.png)

**Comment by stennie** [comment]
@dominikbulaj Excellent, thanks for the screenshots from both 0.8.4 and 0.8.5 :)

**Comment by muzuiget** [comment]
I can't read the Unix timestamp because this bug, it is annoying, could you release a small bugfix version?

**Comment by stennie** [comment]
@muzuiget Still have to investigate how to fix, but this issue been tagged to look into as part of 0.8.6 bugfix release. It was only reported 6 hours ago ;-)

**Comment by zygis** [comment]
I think same problem exists with float numbers
inserting document {test: 1.1} but I see {"test":1.1000000000000001}

**Comment by alexbevi** [comment]
Could we get a build (0.8.5.1 or 0.8.6) with this fix? The issue is really annoying ...

**Comment by stennie** [comment]
@alexbevi Yes, will add links to preview builds in the relevant [placeholders in the 0.8.6 milestone](https://github.com/paralect/robomongo/issues?utf8=%E2%9C%93&q=milestone%3A%22Robomongo+0.8.6%22+label%3Atask+%22create+0.8.6%22) this weekend. What O/S are you using?

**Comment by alexbevi** [comment]
@stennie Windows 7.

**Comment by HeathNaylor** [comment]
Is this is still a problem in 0.8.5? I am getting this issue.

**Comment by Type1J** [comment]
Still a problem in 0.8.5

**Comment by alexbevi** [comment]
@Type1J there was never a build of 0.8.5 that contained the necessary fix

**Comment by schetnikovich** [comment]
@dominikbulaj @muzuiget @alexbevi @HeathNaylor @Type1J 

This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released).
