### ISSUE TITLE
App form floating when in fullscreen mode

### ISSUE THREAD

**Issue by EugeneButusov** [paralect/robomongo#833]
When app is in fullscreen mode, user can change form positions, but all OSX apps locks position changing when fullscreen mode is enabled.
![743a7eee-d852-11e4-8120-d68b72a607cb](https://cloud.githubusercontent.com/assets/3152460/8148539/a3998b52-12aa-11e5-87f9-eaf9164d2338.png)
![74785f52-d852-11e4-9bab-04003fe830f4](https://cloud.githubusercontent.com/assets/3152460/8148540/a3a06404-12aa-11e5-8862-d2e9e42902b3.png)

**Comment by stennie** [comment]
@EugeneButusov Interesting find! The full screen mode is provided by Qt so not sure if that's a Qt bug or a missing window flag. Will look into it.

**Comment by EugeneButusov** [comment]
@stennie, ok, thanks.

**Comment by EugeneButusov** [comment]
@stennie, sorry for the late feedback, just checked some time ago - all works fine (possibly Robomongo or QT changed that behaviour). Please feel free to close this issue :)

**Comment by juliashibalko** [comment]
@EugeneButusov thanks a lot for the answer! Glad to hear it works. Close ticket as fixed.
