### ISSUE TITLE
Collections not available

### ISSUE THREAD

**Issue by dmcna005** [paralect/robomongo#838]
I am running 3.0 and using the wiredTiger storage engine. However, I am unable to see the collection on any database and show collections returns an empty object. 

Please advise.

**Comment by stennie** [comment]
Robomongo 0.8.x doesn't have support for new features in MongoDB 3.0 (WiredTiger storage engine and new SCRAM-SHA-1 authentication). This is being worked on for the 0.9.0 release.

Thanks!

**Comment by dmcna005** [comment]
understood. I am not using SCRAM-SHA-1 I am still running MONGODB-CR. My issue is not authentication. I can authenticate just fine. My issue is just browsing the collections on the left pane or just simply running "show collections". Is there a work around for this?

**Comment by stennie** [comment]
@dmcna005 There's no workaround for listing collections in WiredTiger in the UI. MongoDB 3.0 uses a new cursor-based `listCollections` command for pluggable storage engines that older code does not support. The default mmap storage engine will still work fine if you are not using the new auth.

You could list the data in the shell with: `db.runCommand('listCollections')` but the output needs to be cleaned up a bit to be friendly.

If it's useful I could create a `show collections` function that will work if added to your `.robomongorc.js` file, but in general you would be better using a `mongo` 3.0 shell for the other updated helpers (auth, roles, etc).

**Comment by dmcna005** [comment]
yea I can create that. And thanks for the quick response. This was very helpful.
