### ISSUE TITLE
Failed connection over SSH tunnel reveals password

### ISSUE THREAD

**Issue by pkaske** [paralect/robomongo#839]
I was connected to a MongoDB instance using a SSH tunnel while I lost my internet connection.
The resulting error messages in the log don't hide the password used for SSH. I would suggest to filter this.
![robomongo 0 8 5-1](https://cloud.githubusercontent.com/assets/11567985/7062347/9b0f3820-de9c-11e4-9193-2b3e6713c197.jpg)

**Comment by akostadinov** [comment]
It looks like also key `passphrase` would need filtering out. This is a security issue actually. Also needs to be checked if the password store of the app is read protected to the current OS user only.

**Comment by stennie** [comment]
@pkaske Thanks for the bug report; definitely undesirable to log this info. Looks like the code is just dumping the contents of the connection object.

FYI, if you are concerned about this .. a more secure option at the moment would be setting up an SSH tunnel outside of Robomongo and then connecting to the forwarded port.

**Comment by pkaske** [comment]
@stennie You're welcome. turned my desk around, so nobody can look into my screen, but setting a outside tunnel would have works also, I gess ;-)

**Comment by anorsich** [comment]
@pkaske @akostadinov In the latest Robomongo RC8 release we reworked our ssh tunnel implementation and it's now up to 4 times faster. We also do not log password to the logs anymore and have the option to type in ssh passphrase every time when a new connection is established and do not store a password in currently unencrypted robomongo.json config. There are a bunch of other nice improvements and you can read more in our [blog post](http://blog.robomongo.org/robomongo-rc8/). 

Closing this issue, let us know if it worked for you!
