### ISSUE TITLE
No way to specify slaveOk for a connection

### ISSUE THREAD

**Issue by jasennett** [paralect/robomongo#84]
Currently there's no way to specify slaveOk=true when connecting to a server through the Connections dialog.  As a result, when I connect to a mongo server that's a slave in the replica set, I'm unable to browse the collections in the left sidebar.  Would be nice to have a way to set slaveOk to true for a given connection in the MongoDB Collections dialog (maybe under the "Advanced" tab of the Connection Settings).

**Comment by seththetech** [comment]
+1

**Comment by sallgeud** [comment]
Given that most of us would like to limit ANY developer access to production primary machines, but are ok with occasional access to secondaries, this is fairly critical.  Robomongo is nearly useless when connecting to a secondary.

**Comment by jschrein** [comment]
+1

**Comment by brianfroelund** [comment]
+1

**Comment by burdandrei** [comment]
+1

**Comment by epbarger** [comment]
This would be great to have! :+1:

**Comment by Nimrod007** [comment]
+1

**Comment by d0x** [comment]
+1  :+1:

**Comment by panshul007** [comment]
+1

**Comment by stennie** [comment]
Thanks to everyone to has supported Robomongo via the magic backlog so far!

I'm going to lock discussion on this issue to project collaborators since (a) it's definitely being worked on for the 0.9.0 release milestone and (b) +1s are spamming a lot of watchers ;-).

**Comment by anorsich** [comment]
Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) supports connections to the replica sets (including slaves). Happy to close this ticket! If you find any issues - please create a new one.
