### ISSUE TITLE
RoboMongo 0.8.5 fails to start with mac os 10.7.5

### ISSUE THREAD

**Issue by kartikpatel11** [paralect/robomongo#840]
Hi 
I am getting error while starting robomongo 0.8.5 on my mac .

Stack Trace:
Process:         launchd [6362]
Path:            /Applications/Robomongo.app/Contents/MacOS/Robomongo
Identifier:      Robomongo
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [126]

Date/Time:       2015-04-11 21:49:42.345 +0530
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Interval Since Last Report:          -257675 sec
Crashes Since Last Report:           16
Per-App Crashes Since Last Report:   7
Anonymous UUID:                      409891C3-3D0E-4900-A5D6-D50A23ABEC6F

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 11843
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro8,2, BootROM MBP81.0047.B27, 4 processors, Intel Core i7, 2 GHz, 4 GB, SMC 1.69f3
Graphics: AMD Radeon HD 6490M, AMD Radeon HD 6490M, PCIe, 256 MB
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 384 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 11 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: TOSHIBA MK5065GSXF, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x8509, 0xfa200000 / 3
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfa100000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 5
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821a, 0xfa113000 / 6
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0252, 0xfa120000 / 4
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfd100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd110000 / 3

**Comment by stennie** [comment]
@kartikpatel11 The latest version of XCode only comes with SDKs for OS X 10.9.x and 10.10.x, so it looks like the current Robomongo 0.8.5 package probably wants a newer OS X. This is the first report from anyone still using 10.7 ;-).

I don't have an OS X 10.7.x system to test with, but if you're willing to help test a package I'll work out how to build with the missing SDKs and post a test version for you. Can you let me know?

A temporary workaround would be to install [Robomongo 0.8.4](http://robomongo.org/download.html) from the download archives (or build from source, if you want to install the prerequisites).

**Comment by kartikpatel11** [comment]
HI Stennie, 
Thanks for response. I can start with temporary workaround of installing 0.8.4 so it doesn't hamper my work but I am happy to work with you on 10.7.x compatible version. 
let me know steps and I will follow accordingly

**Comment by stennie** [comment]
@kartikpatel11 I was able to build with the OS X 10.7 SDK, but I'm not certain if the binary will work on 10.7 as I don't have an environment to test with.

Can you please try this Robomongo 0.8.5 version and let me know if it works for you: https://www.dropbox.com/s/fus3l4ahgcfetep/Robomongo-0.8.5-x86_64-10.7.dmg?dl=0?

Thanks!

**Comment by kartikpatel11** [comment]
Didn't work..

Process:         launchd [7417]
Path:            /Users/USER/Desktop/Robomongo.app/Contents/MacOS/Robomongo
Identifier:      Robomongo
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [126]

Date/Time:       2015-04-16 00:55:42.867 +0530
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Interval Since Last Report:          -239817 sec
Crashes Since Last Report:           17
Per-App Crashes Since Last Report:   8
Anonymous UUID:                      409891C3-3D0E-4900-A5D6-D50A23ABEC6F

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 15734
    thread_create: 0
    thread_set_state: 0

**Comment by anorsich** [comment]
@kartikpatel11 
In the latest 0.9.0 RC8 release we did the first chunk of work to make Robomongo more stable and crash less. We  do not have OS X 10.7.5 to test on, but we believe that latest version should work. Could try it out and let us know if it worked for you? If does not work, could you post error log in a new ticket? My fingers are crossed...

You can read more information about the most recent release in the following [blog post](http://blog.robomongo.org/robomongo-rc8/).
