### ISSUE TITLE
MONGODB-CR: AuthenticationFailed

### ISSUE THREAD

**Issue by digitalextremist** [paralect/robomongo#841]
I'm seeing this error on the server side, when I try to authenticate:

```
 Failed to authenticate x@y with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
```

This is with MongoDB `3.0.1` and Robomongo `0.8.5`

**Comment by ucc862** [comment]
Same Problem.It seems that 0.8.5 does not support 3.0.1.I tried a lot of times to connect.But failed.

**Comment by stennie** [comment]
@digitalextremist @ucc862 Robomongo 0.8.x does not support the new SCRAM-SHA-1 auth which is the default authentication method in MongoDB 3.0.x (see #766). There's a possible workaround noted on that issue to enable using the older MONGODB-CR authentication.

Full MongoDB 3.0 support (including WiredTiger) is being worked on for the Robomongo 0.9.0 milestone.

Thanks!
