### ISSUE TITLE
Option to prevent insert of documents with duplicate fields

### ISSUE THREAD

**Issue by pkaske** [paralect/robomongo#846]
I was badly scratched my head when I suddenly had this document in my collection:

```json
{
	"_id" : ObjectId("552fc90fc41ef454fc3bf293"),
	"Field1" : "",
	"Field2" : "some stuff",
	"Field1" : "my value"
}
```

Now I know that bson documents support duplicate keys, but I expect most dev's don't like to have that. So I suggest to add a options that checks for duplicate fields before insert and shows an error. I also suggest to enable this option by default.

**Comment by stennie** [comment]
@pkaske Thanks for reporting; there's actually an existing report as #719. Duplicate fields are allowed by BSON (but definitely unexpected).
