### ISSUE TITLE
Unable to authorize to mongodb 3.0.0

### ISSUE THREAD

**Issue by lidaling** [paralect/robomongo#848]
Unable to authorize to mongodb 3.0.0 server ,but version 2.6.9 is OK.

**Comment by thinklinux** [comment]
MongoDB 3.0 compatibility is up for Robomongo 0.9.0 release.

**Comment by stennie** [comment]
@lidaling More specifically, check out #766 (SCRAM-SHA-1 support). There's a comment there with a workaround if you only need backward auth compatibility for MongoDB 3.0. If you're also using the optional WiredTiger storage engine or want MongoDB 3.0 shell helpers, you'll need to wait for the Robomongo 0.9.0 release.
