### ISSUE TITLE
display font for chinese/japanese?

### ISSUE THREAD

**Issue by dcsan** [paralect/robomongo#852]
I'm using robomongo, and data is stored correctly in the DB.
however it doesn't display
oddly, korean is ok but not japanese or chinese:

![image](https://cloud.githubusercontent.com/assets/514002/7243960/5161cc2e-e789-11e4-917e-91d1111b6ab1.png)

**Comment by dcsan** [comment]
![image](https://cloud.githubusercontent.com/assets/514002/7243968/7ab0b108-e789-11e4-8be1-3a5b80bf93ad.png)

**Comment by stennie** [comment]
@dcsan What version of Robomongo and OS X are you using? If you are using OS X 10.10.x you will need Robomongo 0.8.5 (or build from source with Qt 5.3 or newer).

If you're already using Robomongo 0.8.5, it would be helpful if you can upload a sample document to test with.

Thanks!

**Comment by dcsan** [comment]
awesome, works in 085!
