### ISSUE TITLE
No main screen in Windows - 0.8.5

### ISSUE THREAD

**Issue by Startouf** [paralect/robomongo#860]
I successfully setup a connection (test is ok, even if I try to authenticate with an user/pw), however the main screen remains totally blank (or rather grey :D), the only thing I can see is this `2015-04-27 16:20:06: Connecting to localhost:27017...` in the log, but nothing else happens.

I confirm that my database is accessible, I can connect using mongo.exe and through a local web app.

Windows 10 build 10061
MongoDB 2.6

**Comment by adampridmore** [comment]
I had the same problem with a new install of Robomongo 0.8.5 on Windows 10. I closed and restarted Robomongo and the problem went away.

**Comment by juliashibalko** [comment]
Hi @Startouf @adampridmore! Could you please try to reproduce the issue with the latest [Robomongo 0.9.0-RC8](https://robomongo.org/download) version? I didn't manage to replicate it on my Windows 10. Thank you!

**Comment by Startouf** [comment]
Hey, sorry for not following up. Actually I was using an old version of MongoDB on my computer, and after upgrading the MongoDB server it displayed fine again in the UI of Robomongo.
I suppose I was using a non-supported version of MongoDB. Unfortunately I cannot tell you which one since I'm no working with newer versions and I have totally lost track of the which version was faulty.

**Comment by juliashibalko** [comment]
@Startouf Thank you for the answer! Glad to hear that UI is looking good, so will close the ticket.
