### ISSUE TITLE
robomongo.org down

### ISSUE THREAD

**Issue by jdiamond** [paralect/robomongo#863]
Error messages is:

502 Bad Gateway

nginx/1.1.19

**Comment by stennie** [comment]
@jdiamond Thanks for reporting. FYI, if you want a workaround to download Robomongo 0.8.5, there are [links from Github](https://github.com/paralect/robomongo/issues?utf8=%E2%9C%93&q=create+is%3Aissue+is%3Aclosed+milestone%3A%22Robomongo+0.8.5%22+label%3Atask+).

@schetnikovich manages the hosting, so hopefully he'll be able to look into the issue in his morning.

**Comment by fabienbrooke** [comment]
happening again

**Comment by vladislav-karamfilov** [comment]
The site is down again: https://robomongo.org/
