### ISSUE TITLE
Close unexpectedly while display max date value

### ISSUE THREAD

**Issue by coolgeng** [paralect/robomongo#865]
If I have the date with max value, Robomongo always close unfriendly.  
{
     "Date": 1.7976931348623157081e+308,
}

**Comment by anorsich** [comment]
@coolgeng I can't reproduce this on the latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/). Could look if it work for you and get back to us?

**Comment by coolgeng** [comment]
@anorsich It works under latest version. I think we can close this now. Thanks.

**Comment by anorsich** [comment]
@coolgeng Awesome! Happy to hear that it worked for you.
