### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by extensionsapp** [paralect/robomongo#868]
Hello.

Please, what should be the configuration in MongoDB, to login?
Write how to add a user, make at least some manual.

1. Edit config /etc/mongod.conf
#bind_ip = 127.0.0.1
Now successfully connects to the server.

2. ... ??? ...
~# mongo
use admin
db.createUser(
  {
    user: "siteUserAdmin",
    pwd: "password",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)

Authorization failed.

**Comment by nerycabras** [comment]
i have same problem, i created a user for admin database with userAdminAnyDatabase role, and other for "blog" database, but even with two different users i can't connect.

fork = true 
bind_ip = 127.0.0.1
port = 27017 
dbpath = /Users/nerylopezhernandez/Documents/instalables/mongodb-osx-x86_64-3.0.2/configurations/databases 
logpath = /Users/nerylopezhernandez/Documents/instalables/mongodb-osx-x86_64-3.0.2/configurations/logs/mongod.log 
auth = true
 ----- user ---

{
	"_id" : "blog.root",
	"user" : "root",
	"db" : "blog",
	"roles" : [
		{
			"role" : "userAdmin",
			"db" : "blog"
		}
	]
}
---- user 2----
{
	"_id" : "admin.admin",
	"user" : "admin",
	"db" : "admin",
	"roles" : [
		{
			"role" : "userAdminAnyDatabase",
			"db" : "admin"
		}
	]
}



i use mongo 3.0.2  and OSx 10.10.1.

**Comment by anorsich** [comment]
@extensionsapp I do believe your issue was because of Robomongo was not properly supporting mongodb scram-sha-1/mongodb-cr authentications. With latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) you should be able to connect. Let me know if it works for you.

**Comment by ssnyder** [comment]
I just used 0.9.0 RC6 and this now works!  Thanks!

**Comment by anorsich** [comment]
@ssnyder I am glad to hear it worked for you! Closing and issue.
