### ISSUE TITLE
TypeError: db.collection.initializeOrderedBulkOp is not a function (shell):1

### ISSUE THREAD

**Issue by zrrtcs** [paralect/robomongo#869]
Unable to use db.collection.initializeOrderedBulkOp eventhough db.version() returns 3.0.1

edit:
updating mongodb to current latest 3.0.2 does not solve the problem

**Comment by Joqus** [comment]
It is still happening here.

**Comment by Nullpo** [comment]
+1

**Comment by eromoe** [comment]
+1

**Comment by mcpDESIGNS** [comment]
+1 
TypeError: collection.initializeOrderedBulkOp is not a function (shell):1
TypeError: bulkOp has no properties (shell):2

Same issues =/

**Comment by TrevorFrewinADP** [comment]
Related to the lack of support for bulk operations as described on StackOverflow?
http://stackoverflow.com/questions/27524037/mongodb-cannot-perform-bulk-operation

**Comment by mcpDESIGNS** [comment]
Well that explains it! I wonder if / when that would be upgraded.

**Comment by anorsich** [comment]
@mcpDESIGNS @TrevorFrewinADP @eromoe Latest Robomongo release [0.9.0 RC4] (http://blog.robomongo.org/robomongo-rc4/) integrates mongodb 3.2 shell and therefore supports`initializeOrderedBulkOp`.
