### ISSUE TITLE
Hope to see v0.9 recently

### ISSUE THREAD

**Issue by toboto** [paralect/robomongo#876]
My server is 3.0.3,  Come on!

**Comment by parvanov** [comment]
Really need support for Mongo 3.
Please just update the drivers even with no other changes.

**Comment by tarvitz** [comment]
:+1:

**Comment by joshlopes** [comment]
spaming does not help :)

**Comment by ChALkeR** [comment]
Isn't this a dupe of #520?

**Comment by schetnikovich** [comment]
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine.
