### ISSUE TITLE
Robomongo 0.8.5 closes down automatically 

### ISSUE THREAD

**Issue by prathviraj080** [paralect/robomongo#878]
I get this error on terminal 
usr/bin/robomongo: line 16: 10159 Segmentation fault      (core dumped) "$ROBO_DIR/robomongo"

**Comment by Brightergy-SamarAcharya** [comment]
I can confirm that I hit this frequently. I am using Ubuntu 15.04 64 bit. I'll post more details of segfault as soon as I can dig deeper. Thanks!

**Comment by techgaun** [comment]
I can confirm that I hit this frequently. I am using Ubuntu 15.04 64 bit. I'll post more details of segfault as soon as I can dig deeper. Thanks!

**Comment by techgaun** [comment]
@prathviraj080 the temporary workaround is to run: /opt/robomongo/bin/robomongo . Looks like some variable injection in the wrapper shell script is causing the segfault.

**Comment by anorsich** [comment]
@prathviraj080 @techgaun Could you check it it still the case with latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) release?

**Comment by techgaun** [comment]
@anorsich tested with 2.6.x and 3.0.x and its working fine for me. Looks the issue does not exist anymore. ldd shows the shared library deps are on `../lib/`. FYI, I am on Ubuntu 15.04 64 bit.
LGTM :+1:

**Comment by anorsich** [comment]
@techgaun Thank you for your help! Happy to heaer that issue has been fixed in a new version.

**Comment by prathviraj080** [comment]
+1 @techgaun
