### ISSUE TITLE
OS X Yosemite 10.10.3 Automatic Close Robomongo 0.8.5（trigger: lock the screen and unlock） 

### ISSUE THREAD

**Issue by zivfun** [paralect/robomongo#879]
lock the screen and unlock > then the robomongo Automatic Close

**Comment by anorsich** [comment]
@zivfun I seems can't reproduce this one with latest [0.9.0 RC](http://blog.robomongo.org/robomongo-rc4/) (I use el capitan tho). Could you check if it work for you?

**Comment by juliashibalko** [comment]
Hi @zivfun! Could you please try to reproduce the issue using the latest Robomongo version 0.9.0-RC8? I didn't manage to replicate it, so seems that issue can be closed.

**Comment by juliashibalko** [comment]
Close ticket as fixed. Don't hesitate to reopen it if issue is reproducible for you.
