### ISSUE TITLE
Robomonogo returns no results for collections on Mongo 3 with WiredTiger

### ISSUE THREAD

**Issue by mikeckennedy** [paralect/robomongo#883]
I just switched to Wired Tiger. After doing so, my robomongo seemed to think there are no collections in any of the DBs. See the screenshot here.

![missing-data-notated](https://cloud.githubusercontent.com/assets/2035561/7870945/79db751c-0541-11e5-8218-5cbbde11a559.png)

**Comment by mikeckennedy** [comment]
Here's the configuration settings I'm using.

dbpath = E:\mongodb\wiredtired_db\
directoryperdb = true
rest = false
logpath = E:\mongodb\Logs\mongodb_wt.log
logappend = true
service = true
storageEngine = wiredTiger

**Comment by sallgeud** [comment]
+1 to this and all the other half a dozen duplicate requests for mongo 3.0 compatibility

**Comment by PhilHannent** [comment]
This is a duplicate: https://github.com/paralect/robomongo/issues/707

WiredTiger is not yet supported.

**Comment by mikeckennedy** [comment]
Ok, thanks for letting me know.
