### ISSUE TITLE
"Authorization failed" when connecting via SSH

### ISSUE THREAD

**Issue by peter-na** [paralect/robomongo#884]
Hi, I have MongoDB running on a remote server I try to connect to via SSH tunneling. When I connect via shell, I run the following commands.

connecting to the server: ssh username@serveradress -> entering my password afterwards
connecting to the mongodb: mongo localhost:19005/ABIRS

I'm not sure if robomongo just does not work for this approach to connect or if I used the wrong config for the connection (when testing the connection, I get: 
![image](https://cloud.githubusercontent.com/assets/5823248/7955697/958dddd4-09da-11e5-840f-013953e937d7.png)

In the SSH tab, I entered the serveradress, username, and password. In the Authentication tab I tried multiple combinations, however when I uncheck 'Perform authentication' I receive a different error ('Authorization skipped by you') instead the one shown above.

Any hints, on what I'm doing wrong here? Thank you

**Comment by reilg** [comment]
Same problem here. Any word on this?

**Comment by EddieOne** [comment]
Yes same problem too. I think it tries to connect without ssh even when selected.

**Comment by gabrielbauman** [comment]
This is an issue with 0.8.5 on Linux as well.

**Comment by biko8** [comment]
I have same problem too.

**Comment by insaneinc01** [comment]
Anybody figured this out?

**Comment by slam310** [comment]
same here ...Anyone support for this kind of  "main features" ?

**Comment by jeremyml** [comment]
I think this is a bug.  The ssh tunnel feature in robomongo will work for me when I disable `auth` in the mongodb server.  But I cannot get auth to work.

**Comment by anorsich** [comment]
@peter-na @reilg @jeremyml @slam310 @insaneinc01 

This bug was fixed in the newest RC8 release. You can find more information in our [blog post](http://blog.robomongo.org/robomongo-rc8/). 

Feel free to reopen this ticket if it still does not work for you!
