### ISSUE TITLE
Text mode displays int32 using scientific notation

### ISSUE THREAD

**Issue by stevensheehy** [paralect/robomongo#885]
```javascript
db.test.insert([{timestamp: Number(1433363467)}, {timestamp: NumberInt(1433363467)}, {timestamp: NumberLong(1433363467)}]);
db.test.find({});

/* 1 */
{
    "_id" : ObjectId("556f66563ae4846a727390ee"),
    "timestamp" : 1433363467.0000000000000000
}

/* 2 */
{
    "_id" : ObjectId("556f66563ae4846a727390ef"),
    "timestamp" : 1.43336e+09
}

/* 3 */
{
    "_id" : ObjectId("556f66563ae4846a727390f0"),
    "timestamp" : NumberLong(1433363467)
}
```
Only the NumberInt (e.g. 1.43336e+09 above) is displayed as scientific notation in text mode. Floating point and longs are printed properly. Also, the table and tree views display the number properly without scientific notation. In mongo shell it prints properly:

```javascript
> db.test.find({}).pretty();
{ "_id" : ObjectId("556f66c0c9c3393fba66d34c"), "timestamp" : 1433363467.0000000000000000 }
{ "_id" : ObjectId("556f66c0c9c3393fba66d34d"), "timestamp" : 1433363467 }
{
	"_id" : ObjectId("556f66c0c9c3393fba66d34e"),
	"timestamp" : NumberLong(1433363467)
}
```

This makes it impossible to determine the actual number of the returned timestamp in this view since it causes the number to lose information by removing the least significant digits. It also makes it impossible to copy and paste a document from text mode as a template for inserting a document. I expected that the integers would always be displayed without scientific notation in all views (e.g. 1433363467).

Using Robomongo 0.8.5 on OS X Yosemite

**Comment by tomchambers2** [comment]
I'm experiencing this problem as well. It's also causing problems updating documents if the _id is stored as an int, since it gets displayed in scientific notation in the JSON editor:

```
{
    "_id" : 2.10098e+07,
    "property": "won't be saved to the correct document"
}

**Comment by carlozamagni** [comment]
I confirm that this isn't only a visualization problem, but can lead to data corruption: 
if an update is performed on a document containing an integer field (displayed with scientific notation), this value gets altered to a wrong value in the final document

e.g. a document containing the integer field:  "Date": 20150325 is visualized as follows:
```
{
  "Date" : 2.01503e+007  // should be 20150325
}
```

after an "edit" operation on the document the results gets corrupted:
```
{
  "Date" : 20150300.0000000000000000
}
```

**Comment by stevensheehy** [comment]
My mistake, already fixed and will be in next release. Closing as duplicate of https://github.com/paralect/robomongo/issues/885
