### ISSUE TITLE
Double-clicking to open a new shell can crash or make UI state incorrect

### ISSUE THREAD

**Issue by RoosterDragon** [paralect/robomongo#886]
If you double click in the blank region to open a new shell, but you're clicking in the region where the new tab appears you can cause several issues.

- The second click is interpreted as single clicking on the open tab to close it. Your double click to open a tab opens and immediately closes a tab which is a bit silly.
- When the tab immediately closes it can sometimes leave the UI in the wrong state - the stop execution button is enabled and the execute button is disabled, which is the opposite of the usual.
- If this close happens at an inopportune moment during this following dialog may appear (I have highlighted in red the area to click - if you just spam clicks in this region you'll likely be able to recreate the problem):
![Imgur](http://i.imgur.com/nD1gsRX.png)
- After you dismiss the dialog, robomongo might keep working or it might crash outright. I'm on Windows so I get the "X has stopped working" dialog if it dies.

**Comment by anorsich** [comment]
@RoosterDragon 
In the latest 0.9.0 RC8 release we did the first chunk of work to make Robomongo more stable and crash less. We can't reproduce that issue on our side. Please, let us know if it worked for you and if it doesn't -- please, create a new ticket. 

You can read more information in the following [blog post](http://blog.robomongo.org/robomongo-rc8/).
