### ISSUE TITLE
Install of 0.8.5 on Ubuntu 13.10 64bit fails with dependency error: libharfbuzz0b

### ISSUE THREAD

**Issue by dflock** [paralect/robomongo#888]
The .deb package install fails with the error "Dependency is not satisfiable: libharfbuzz0b (>=0.9.11)"

I can't find this package for saucy.

**Comment by jgauna** [comment]
I'm having this issue too.

**Comment by dflock** [comment]
I already have 0.8.4 installed; I was hoping to upgrade to 0.8.5.

**Comment by anorsich** [comment]
@dflock / @jgauna Can you help us to test if latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) work on ubuntu 13.10?

**Comment by jgauna** [comment]
@anorsich glad to help but i'm with ubuntu 14.04 now

**Comment by dflock** [comment]
Yep - I'll try it tomorrow.

**Comment by anorsich** [comment]
@jgauna Thank you for the reply! We know for sure that Robomongo does not work on 12.04 (#982) and do work on 14.04 as it the system we use to build / test Robomongo. 

@dflock Awesome! Looking forward to hear back from you!

**Comment by anorsich** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;M3dx5UoO&#x2F;1-the-card"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> The card</a>

**Comment by dflock** [comment]
I downloaded [this tarball](http://download.robomongo.org/0.9.0-rc4/linux/robomongo-0.9.0-rc4-linux-x86_64-8c830b6.tar.gz), extracted it and ran the `robomongo` binary - and it worked! I've just moved machines, so I don't have a mongo instance up and running right now, so I haven't tested any functionality, but it runs and presents the connection dialog.

**Comment by anorsich** [comment]
@dflock Awesome, happy to hear that. I am closing this ticket for now. If you'll have any issues feel free to just open new ticket.
