### ISSUE TITLE
Scientific notation for very large or very small numbers

### ISSUE THREAD

**Issue by PedroMDuarte** [paralect/robomongo#894]
My document has a value on the order of 1E-9.   In table mode I see a value of 0.000000.  Desirable behavior would be to show such a small value in scientific notation,  keeping a fixed width for the string output to the table.

**Comment by schetnikovich** [comment]
@PedroMDuarte This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
