### ISSUE TITLE
Open explorer by default (mac)

### ISSUE THREAD

**Issue by alfonsodev** [paralect/robomongo#897]
First time you download the app, you create a new connection, and connect.
a) there is no feedback saying , connection success, could be a green light somwhere.
b) The explorer is not shown.
So as a user I'm not sure if the connection worked and how I can access the collections, 
then navigating to View menu , I saw the explorer option, I think it should be enabled by default. 
I think it was in previous versions. 
Mac OS 10.10.2 
thanks for this great software !

**Comment by schetnikovich** [comment]
@alfonsodev Starting from Robomongo 0.9.0, explorer is shown by default. It was always shown by default, but in 0.8.4 and 0.8.5 it was false by mistake.
