### ISSUE TITLE
Mac OSX SSH doesn't work

### ISSUE THREAD

**Issue by freynolds** [paralect/robomongo#900]
The last version of Robomongo doesn't even connect using ssh and identity provider, I had to downgrade so that works.

**Comment by Splat** [comment]
Which version did you have to roll back to?

**Comment by freynolds** [comment]
0.8.4

**Comment by brainstorm** [comment]
I'm running `0.8.4` and does not work for me either :-/

**Comment by anorsich** [comment]
@freynolds @Splat @freynolds @brainstorm 

Happy to announce, that Robomongo RC8, which was released just a few minutes ago now supports SSH connections and now works much faster than before. That functionality was re-worked from scratch and now much more stable and user-friendly. Read more details on our [blog post](http://blog.robomongo.org/robomongo-rc8/).

If you still have difficulties connecting using SSH - feel free to reopen this ticket!
