### ISSUE TITLE
Text Size Persistence

### ISSUE THREAD

**Issue by sabrehagen** [paralect/robomongo#901]
In text view mode when inspecting documents in my mongodb the text size is very large. I use Ctrl+- to decrease the text size, but it doesn't persist across restarts. Is there a way to configure this in robomongo.json? I'm on Ubuntu 14.04.

**Comment by CraigKelly** [comment]
@sabrehagen I don't think there's a way to store the zoom settings (with ctrl +/- shortcuts), but the unreleased 0.8.6 milestone includes a way to specify font name and point size in robomongo.json. I also have a pull-request open to add menu options for these two settings. However, at this point you'll need to build Robomongo to get either one of these.

**Comment by sabrehagen** [comment]
@CraigKelly thanks craig, i'll try building from source now
