### ISSUE TITLE
Won't connect to a sharded cluster

### ISSUE THREAD

**Issue by Russ93** [paralect/robomongo#902]
I am trying to connect to mongos which is on a sharded cluster. No authentication nothing really out of the ordinary

I am using Mongo version mongodb-2.8.0-rc5
and i have tried the same with mongodb-3.0.4

```shell
# mongos.conf

#################################################################################

# Listening Options.

bind_ip = localhost

port = 27017

fork = true

configdb = localhost:27011,localhost:27012,localhost:27013

#################################################################################


#################################################################################

# Where to store the data.

#where to log
logpath = /Users/russellbenton/Desktop/Testing/Dev_Docs/mongodb-3.0.4/bin/log/server/server.log

logappend = true

# Turn on/off security.  Off is currently the default
# noauth = true
# auth = false

#################################################################################
```

**Comment by Russ93** [comment]
I can connect using mongo just fine
and MongoChef is working also

**Comment by juliashibalko** [comment]
Hi @Russ93, sorry for long delay!
If it's still actual and possible, could you please try to check your issue with the latest release? All versions could be found here https://robomongo.org/download.
If connection still fails, any details about this connection (error, screenshots) are appreciated. Thanks in advance!

**Comment by Russ93** [comment]
I think it's working now lol thank you :)
