### ISSUE TITLE
Failed to authenticate user , MONGODB-CR credentials missing in the user document

### ISSUE THREAD

**Issue by EliNok** [paralect/robomongo#903]
robomongo : 0.8.5 ( on windows)
mongoDB :  3.0.3 (Ubuntu 15.04)

Getting access error when trying connect mongoDB
"2015-06-28T14:29:51.908+0300 I ACCESS   [conn5] Failed to authenticate siteUserAdmin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document"

configuration : /etc/mongod.conf
bind_ip = 0.0.0.0
port = 27017

on robomongo configured ubuntu server external IP , username , password
on robimango UI getting V on Connection , but autorization failed 

Can connect to MongoDB from Windows with another tool , for example umaongo

**Comment by matteocontrini** [comment]
Read this https://jira.mongodb.org/browse/SERVER-17459
MongoDB support in RoboMongo is not completely there yet...

**Comment by anorsich** [comment]
@EliNok Latest release of Robomongo [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) properly supports MONGODB-CR authentication and integrates shell from mongodb 3.2. I do beleive that should work now. If it won't - feel free to reopen this ticket.
