### ISSUE TITLE
Edit document interface doesn't like NumberInt()

### ISSUE THREAD

**Issue by xig3** [paralect/robomongo#905]
robomongo 0.8.5

right click collection name and select 'insert document...'.
just add 'number' : NumberInt(2) into {}.

When you click save, we got error message
Parsing error
Unable to parse JSON: Bad charactors in value, ...

If I change NumberInt to NumberLong, the save will succeed.

**Comment by schetnikovich** [comment]
This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). 

When you save field as `NumberInt(N)`, it will be shown in UI and JSON as `N`. This behavior is consistent with MongoDB shell. Let us know how it works for you.
