### ISSUE TITLE
Editing a document with a selection of fields will remove other fields from db.

### ISSUE THREAD

**Issue by bgSosh** [paralect/robomongo#909]
Recently I queried for a document, and selected only a small set of fields.  I then edited the document, and was surprised when the save operation destroyed all fields which were not part of the original query.

I think the save function should generate a safe query (using $set).  If not, then at least the save function should be disabled for documents that have not had all their fields retrieved.

**Comment by malyavkin** [comment]
Small update: 
It doesn't remove filtered fields now, just spits assertion error: 

    assertion c:\users\ank\robomongo\robomongo-core\src\third-party\mongodb\src\mongo\db\../bson/bsonobjbuilder.h:85

**Comment by anorsich** [comment]
This one looks like a duplicate of #881
