### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by hitesh1818** [paralect/robomongo#916]
Hello Team,

  There is an issue with mongodb version 3.0.4. Can you please take a look into this issue and launch newer version with bug fixes. or show me alternative to connect database with v3.0

**Comment by Demurgos** [comment]
I agree, since version 3.0 I get the following error:
````shell
2015-07-17T19:21:00.171Z I ACCESS   [conn11]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "root", key: "xxx" }
2015-07-17T19:21:00.172Z I ACCESS   [conn11] Failed to authenticate root@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
````

It would be really cool if it was solved :)

**Comment by hitesh1818** [comment]
Yes issue has been resolve. i just changes authentication schema for current database v3.0. and it's working fine, hurrayyyyy!!!

**Comment by Demurgos** [comment]
Did you configured Robomongo or changed the way you start your database ?

**Comment by hitesh1818** [comment]
just logged in via command prompt on server and try commands
use admin;
db.system.version.save({ "_id" : "authSchema", "currentVersion" : 3 }).

If you have admin password then please first execute command db.auth("admin_user","admin_pass") after "use admin" command.

**Comment by Demurgos** [comment]
Ok, thank you

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
