### ISSUE TITLE
0.84

### ISSUE THREAD

**Issue by sangyoo91** [paralect/robomongo#918]
I need to use 0.84 because 0.85 does not support authentication on mongodb version I am using. Is there a way I can download 0.84?

**Comment by honomoa** [comment]
http://robomongo.org/download.html

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
