### ISSUE TITLE
RoboMongo Issues with list all databases

### ISSUE THREAD

**Issue by abhishekmit1982** [paralect/robomongo#919]
I’m trying to use RoboMongo to connect to databases. However, the one feature that is troubling is RoboMongo trying to pull a list of all databases on a given server.
Our group policies don’t allow connect permissions on all databases on a given database instance.

Is this something you can help me with.

Regards,
Abhishek

**Comment by schetnikovich** [comment]
@abhishekmit1982 Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
