### ISSUE TITLE
Is there any trouble occured on the way of 0.9 for supporting Mongodb v3.0+?

### ISSUE THREAD

**Issue by Honghe** [paralect/robomongo#920]
Robomongo is excellent.
Waiting for supporting Mongodb v3.0+.
What is the status of the blueprint of Robomongo v0.9 ^_^

**Comment by GuillermoBlanco** [comment]
+1 would be good to know

**Comment by optikalefx** [comment]
This is a huge disaster for me. I'm very surprised to see that 3.* is not supported. All of my databases show 0 collections.  I can't even turn back now. I'm just stuck without this.

**Comment by syemhusa** [comment]
I am evaluating MongoChef, it works very well with Mongo 3.0 Wired Tiger and it has a free version if you are using it for non-commercial purpose

**Comment by optikalefx** [comment]
It isn't pretty but it does work.  I already downgraded to the other engine and now have 150k records. I wonder if wired tiger is worth it

**Comment by syemhusa** [comment]
Well if you have large dataset i.e. In GBs then it's definitely worth it as the compression takes a lot less disk space and there are some other advantages too that you can read in the release notes like increased write performance and document level locking etc.

**Comment by carmbrester** [comment]
Robomongo still works with Wired Tiger (in my experience), it's just that the UI isn't quite as friendly. If you know the names of your collections, you can still right-click your database, choose "Open Shell," and then type what would normally be generated for you...

db.getCollection("collectionName").find({})

**Comment by optikalefx** [comment]
Is it really that hard to update this app then to change the method for listing collections? It seems like that would solve our issues?

**Comment by Zertz** [comment]
Looking at the milestone for 0.9, it's just trying to do way too much. The release should be focused on integrating a new version of the shell and adding support for the new authentication method. Everything else is gravy and should be pushed back.

The shell is currently at 2.4 and I'm honestly not sure what's involved in swapping it out for a new version. I'd be willing to put some time into it, but perhaps @stennie could point us in the right direction?

**Comment by root2000xyz** [comment]
mongochef , support MongoDB 3.X on WiredTiger .
https://cdn.3t.io/mongochef

**Comment by ChALkeR** [comment]
#520 — main issue.
There are already a lot of dupes for that ;-).

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket. Thank you all for patience!
