### ISSUE TITLE
Number precision is lost when displaying exponential format in Text Mode

### ISSUE THREAD

**Issue by povesteam** [paralect/robomongo#921]
When displaying numbers in Table Mode, the look is correct.

![table view](https://cloud.githubusercontent.com/assets/506532/8848583/17587bfc-3141-11e5-857d-949ff44c34d6.PNG)

But when switching to Text Mode, the **precision is lost** because of the exponential format.

![text view](https://cloud.githubusercontent.com/assets/506532/8848589/24d389fc-3141-11e5-914a-f48f97f90e81.PNG)

The problem also occurs when opening "Edit Document" from the Table Mode. If I edit a document and save it, I will **unintentionally change numeric values, destroying the precision**.

Thanks!

*I am using Robomongo 0.8.5 on Windows 7*

**Comment by darkin1** [comment]
Same here, Windows 8.0, Robomongo 0.8.5

**Comment by povesteam** [comment]
Just found this bug is a duplicate of #831, which was resolved, but not yet released.
Looking forward for the 0.8.6 release.
