### ISSUE TITLE
Always crashed. v 0.8.5

### ISSUE THREAD

**Issue by kirame09** [paralect/robomongo#922]
I don't know If I am the only person who is experiencing this but everytime I tried to list the collections. It always not responding. By the way I am connected from a remote server. Please advise and I hope this can be resolved soon.

**Comment by sclausen** [comment]
Maybe you're using mongodb 3 and maybe you missed the fact that v0.8.5 doesn't support mongodb 3.
This issue is already on the roadmap, but unfortunately, the maintainer didn't commited anything for 3 month, so…

**Comment by root2000xyz** [comment]
mongochef , support MongoDB 3.X on WiredTiger .
https://cdn.3t.io/mongochef/windows/2.0.10/mongochef-x64.msi.zip

**Comment by anavioc** [comment]
Same problem with mongo 2.*

**Comment by anorsich** [comment]
@kirame09, Could you try [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/)?

**Comment by anorsich** [comment]
@kirame09 @root2000xyz @anavioc Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) supports mongodb 3+, including different auth schemas and replica sets. I do beleive we can close this issue. If it won't work for you - feel free to reopen this issue.
