### ISSUE TITLE
CentOS7 x86_64: libstdc++.so.6 >= 6.0.13 is needed; libstdc++.so.6.0.19 installed

### ISSUE THREAD

**Issue by dhoffutt** [paralect/robomongo#923]
Attempting to install robomongo-0.8.5-x86_64.rpm onto a CentOS 7 x86_64 machine and getting a failed dependency error when it shouldn't be expected. Thank you!

`sudo rpm -vi ./robomongo-0.8.5-x86_64.rpm 
error: Failed dependencies:
	libstdc++.so.6 >= 6.0.13 is needed by robomongo-0.8.5-1.x86_64`

`ls -l /usr/lib64/libstdc++*
lrwxrwxrwx. 1 root root     30 Jul 28 08:49 /usr/lib64/libstdc++.so.6 -> /usr/lib64/libstdc++.so.6.0.19
-rwxr-xr-x. 1 root root 991744 Mar  5 13:17 /usr/lib64/libstdc++.so.6.0.19`

`cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)`

`uname -a
Linux orb 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by JoeyG1973** [comment]
I am having the same issue on CentOS 6.7.

rpm -Uvh robomongo-0.8.5-x86_64.rpm 
error: Failed dependencies:
	libstdc++.so.6 >= 6.0.13 is needed by robomongo-0.8.5-1.x86_64

ls -al /usr/lib64/libstdc++*
lrwxrwxrwx 1 root root     19 Aug 18 11:45 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.13
-rwxr-xr-x 1 root root 989840 Jul 22 21:03 /usr/lib64/libstdc++.so.6.0.13

**Comment by CamiloBernal** [comment]
I am having the same issue on CentOS 6.7

Has anyone been able to solve?

Thank you

**Comment by rightson** [comment]
same issue : (

CentOS 7:

$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

$ sudo rpm -ivh robomongo-0.8.5-x86_64.rpm
error: Failed dependencies:
	libc.so.6 >= 2.12 is needed by robomongo-0.8.5-1.x86_64
	libstdc++.so.6 >= 6.0.13 is needed by robomongo-0.8.5-1.x86_64

$ ls -al /usr/lib64/libstdc++*
lrwxrwxrwx. 1 root root     19 Mar 31  2015 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxr-xr-x. 1 root root 991744 Mar  6  2015 /usr/lib64/libstdc++.so.6.0.19

RHEL 6.7:

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

$ sudo rpm -ivh robomongo-0.8.5-x86_64.rpm
error: Failed dependencies:
	libc.so.6 >= 2.12 is needed by robomongo-0.8.5-1.x86_64
	libstdc++.so.6 >= 6.0.13 is needed by robomongo-0.8.5-1.x86_64

$ ls -al /usr/lib64/libstdc++*
lrwxrwxrwx. 1 root root     19 Mar 31  2015 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.13
-rwxr-xr-x. 1 root root 991744 Mar  6  2015 /usr/lib64/libstdc++.so.6.0.13

**Comment by anorsich** [comment]
@rightson Could you try new [0.9.0 RC3](http://download.robomongo.org/0.9.0-rc3/linux/robomongo-0.9.0-rc3-linux-x86_64-0476204.tar.gz) release and let us know if it works for you?

**Comment by anorsich** [comment]
@dhoffutt Latest Robomongo release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) works well at least on centos 7+. I think we can close this ticket for now. If it still does not work for you - feel free to reopen this ticket.
