### ISSUE TITLE
Collections not showing for mongo 3.0.4

### ISSUE THREAD

**Issue by btmdave** [paralect/robomongo#926]
I have a mongo instance on 3.0.4, I'm able to read/write with the same credentials using node client, but with the same credentials in robomongo, I'm able to auth and view the databases, but the collections are all `Collections (0)`, which isn't right.

Any ideas?

**Comment by rubensainiuc** [comment]
I have the same problem.

Although, when I run `db.users.find()` from the RoboMongo shell, results are ok.

The bug might be related to https://jira.mongodb.org/browse/SERVER-16361 which suggests upgrading the shell version. I guess this is something to be done inside RoboMongo.

**Comment by ChALkeR** [comment]
https://github.com/paralect/robomongo/issues/520 — main issue.
There are already a lot of dupes for that ;-).

**Comment by danielfaust** [comment]
Ouch, got bit by this as well. :( Is there an ETA?

**Comment by danielfaust** [comment]
Oh, I see, "Note: We are working on an update with MongoDB 3.0 compatibility for the upcoming Robomongo 0.9.x release series."

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
