### ISSUE TITLE
Unstable with Retina resolution

### ISSUE THREAD

**Issue by dmitrizzle** [paralect/robomongo#927]
After working with RM for a few minutes it began to crash. Would eventually crash after restart within 1 minute.

I went to the app icon and disabled Retina support (Get info > Open in low resolution). It stopped crashing.

MacBook Pro (Retina, 15-inch, Early 2013)

**Comment by anorsich** [comment]
@dmitrizzle Thank for submitting this issue. Robomongo 0.8.5 crashing a lot on OSX. I've been using latest Robomongo release [0.9.0 RC4] (http://blog.robomongo.org/robomongo-rc4/) for a few weeks now, and haven't seen any crashes on Macbook Pro Pro with retina. Could you try it out and let us know if it worked for you? If that won't work - feel free to reopen this ticket.
