### ISSUE TITLE
Empty menus in robomongo 0.8.5

### ISSUE THREAD

**Issue by oz123** [paralect/robomongo#928]
I Build robomongo on gentoo using Qt5.5 and Qt5.4.2 in both cases the menus of the main windows are not created properly:

![screenshot-2](https://cloud.githubusercontent.com/assets/1083045/9078847/d8a71cc6-3b43-11e5-9e29-15a85b45cf62.png)

**Comment by oz123** [comment]
Just another note. This happened when I built robomongo from source, with applying the patch here:
```
--- src/robomongo/gui/AppStyle.h	2015-03-14 04:22:55.000000000 +0100
+++ src/robomongo/gui/AppStyle.1	2015-08-02 22:55:55.320169592 +0200
@@ -12,8 +12,8 @@
         #include <QProxyStyle>
         typedef QProxyStyle OsStyle;
     #else
-        #include <QCleanlooksStyle>
-        typedef QCleanlooksStyle OsStyle;
+        #include <QCommonStyle>
+        typedef QCommonStyle OsStyle;
     #endif
 #endif
```
I did this because of: https://github.com/paralect/robomongo/issues/479

**Comment by schetnikovich** [comment]
@oz123 Please try new version ([Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/)), where this issue was fixed. For any new issues, please create new ticket.
