### ISSUE TITLE
Request: Mac way to "expand recursively"

### ISSUE THREAD

**Issue by kengruven** [paralect/robomongo#929]
In Robomongo on the Mac, to expand a subtree recursively, you have to right-click and choose "Expand Recursively" (and likewise for Collapse).

On the Mac, though, this is not the normal way to do this.  The option key is used instead.  You option-click a disclosure triangle, or press option-left-arrow or option-rightarrow.

It would be great if Robomongo supported this.

**Comment by schetnikovich** [comment]
`Option + Left/Right` on Mac or `Alt + Left/Right` on PC keyboard are now works as requested.

Credit goes to Anton Zering (@synthomat), who implemented this feature.
