### ISSUE TITLE
Robomongo.org is down

### ISSUE THREAD

**Issue by juancancela** [paralect/robomongo#930]
Hi,

Seems that theres an issue and site cant be accessed: http://robomongo.org/ is throwing a 502 Bad Gateway, showing an nginx error message. 
In the meantime, is there an alternative site where I can download client for Windows?

Thanks!

**Comment by letanure** [comment]
:+1:

**Comment by gavruk** [comment]
Its up now. Thanks for notice

**Comment by wadijm** [comment]
it's down again :(
