### ISSUE TITLE
If Explorer is not visible when a new connection is made, it should be made visible. 

### ISSUE THREAD

**Issue by jcollum** [paralect/robomongo#933]
Env: OSX 10.10.4, Robomongo 0.8.5

Got a db running on another server: xxx.yyyyy.zz.com:27017/exampleDb. When I put that address in and try to connect to it, I get: 

```
2015-08-24 08:16:41: Settings saved to: /Users/collumj/.config/robomongo/robomongo.json
2015-08-24 08:16:41: Connecting to xxx.yyyyy.zz.com:27017...
```

And that's it. 10 minutes later, no change. I assumed the URL was wrong, so I downloaded mongo and tried to connect via command line. Connected instantly. 

What is RoboMongo doing here? Is it timing out? Did it fail? Was there any error at all? Is it connected? I have no idea and the UI isn't helping me figure that out. 

So I looked around and opened the Explorer pane (which was not open). Turns out I'm connected to the db 3 times now. 

1. The logs should have told me the connection was made successfully. As it is, it just looks like it's waiting forever or something. 
1. The Explorer pane should be made visible after a new connection is made.

**Comment by schetnikovich** [comment]
This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Explorer is shown by default. Let us know how it works for you.
