### ISSUE TITLE
Robomongo not supporting wiredtiger storageengine

### ISSUE THREAD

**Issue by inuskmulla** [paralect/robomongo#939]
Robomongo not supporting wiredtiger storageengine, will you please give support for this. when connected to storage engine , it is not showing collections, and also data in collection.
Please reply ASAP.

**Comment by ApfelUser** [comment]
@inuskmulla This project is dead, just so you know. Nobody is answering since months. You should've looked through the existing issues before opening this.

**Comment by sleske** [comment]
Anyway, this is a dupe of #707 , so can be closed as a duplicate.
I don't have the rights to close it, so someone else will have to.

**Comment by schetnikovich** [comment]
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine. For any found issues, please create new ticket.
