### ISSUE TITLE
empty collection

### ISSUE THREAD

**Issue by mhf-ir** [paralect/robomongo#940]
I see empty collection :cry: . also when create collection. collection exist but seems no one shows.
Robomongo 0.8.5 Ubuntu 15.04 mongodb 3.1
![Empty collection](http://oi62.tinypic.com/2jilo6.jpg)

**Comment by Nalum** [comment]
I see this as well. It seems to be around version >=3

**Comment by mhf-ir** [comment]
yeah my mongodb is 3.1

**Comment by schetnikovich** [comment]
@mhf-ir @Nalum Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
