### ISSUE TITLE
Edit/No change/Save changes number values

### ISSUE THREAD

**Issue by doom-fr** [paralect/robomongo#945]
I use a field to store epoch timestamp as number.
When I edit the document, I see in this field 1.4427e+009 instead of the real value.
If I save, the value of timestamp is changed.

In previous version of Robomongo I do not have this problem (I have also change from w7 to W10).

Robomongo 0.8.5 / windows 10

**Comment by josephyanks** [comment]
Here is an example of the before and after I go in and select 'edit', don't make changes, hit 'save':

Before:
![before](https://cloud.githubusercontent.com/assets/2382554/10082412/7e32f2d2-62c7-11e5-8594-61ae36cb1357.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/2382554/10082413/7e379f12-62c7-11e5-87f6-68d65d6ad388.PNG)

**Comment by doom-fr** [comment]
Hi thanks for your test.
Seems to happen with value >= 1e6.
For me value 9945082 is changed to 9.94508e+006 and after
to 9945080.0000000000000000 which differs of two from initial value.
Difference is higher for higher values.

Here is my test :
[image: Images intégrées 2]

Doom.

2015-09-24 20:22 GMT+02:00 Joseph Yanks <notifications@github.com>:

**Comment by schetnikovich** [comment]
@doom-fr @josephyanks This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.

**Comment by doom-fr** [comment]
Hey !

Can't test the closed issue. Robomongo 0.9.0 RC3 does not want to connect
to my mongo db.
(I have to manually recreate my website as it has not been imported from
previous version).
And Robomongo 0.9.0 RC3 is not visible in windows 10 (typing robomongo just
show me Robomongo 0.8.5).

Good luck for your Indiegogo Campaign !

Doom !

2016-01-29 17:37 GMT+01:00 Dmitry Schetnikovich <notifications@github.com>:
