### ISSUE TITLE
should we know the news of 0.9.x?

### ISSUE THREAD

**Issue by qtisan** [paralect/robomongo#954]
we are so eager for it cause of mongo3..
stare at it for months and can not see any news of 0.9.x...
we want to know when it would come, or maybe it need help that we glad to do....
thumbs me up please guys...

**Comment by itsmejainh** [comment]
Yeah thumbs up !!! Eagerly waiting for this update.

**Comment by kartoch** [comment]
There is no new commits since April 2015. Does @stennie need help for this new release ?

**Comment by onion83** [comment]
thumbs up !!!

**Comment by hellboy81** [comment]
MongoDB & RoboMongo are dead. Long live Oracle & TOAD!

**Comment by eromoe** [comment]
there are a lot of bug not fixed....I think it is far

**Comment by Rewt0r** [comment]
There's a suitable alternative called MongoChef which is free for personal use.

**Comment by phw** [comment]
You might want to read the blog post http://blog.robomongo.org/robomongo-future/ by @schetnikovich and maybe consider [contributing](https://www.indiegogo.com/projects/save-robomongo#/)

It would be a shame to have this great piece of software rot due to lack of time.

**Comment by schetnikovich** [comment]
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine. For any found issues, please report to #520.
