### ISSUE TITLE
robomongo connect remote sever failed

### ISSUE THREAD

**Issue by TNT-Likely** [paralect/robomongo#955]
when i use command line connect remote sever with username and password,it work.
but when i use robomongo,it doesn't work,who can help me to reslove this problem?
thanks !
the following is my configuration:
![qq20151008-1 2x](https://cloud.githubusercontent.com/assets/9278923/10360991/b00a044c-6dd7-11e5-8ed2-1c7ab2e97bd4.png)
![qq20151008-2 2x](https://cloud.githubusercontent.com/assets/9278923/10360997/b6c47bb4-6dd7-11e5-9f58-82ef35fc52c0.png)

**Comment by shashah** [comment]
I am also facing the same issue. I am able to connect via command line.
But when trying by robomongo, it says authorization failed.

**Comment by TNT-Likely** [comment]
@shashah i reslove it .
http://stackoverflow.com/questions/29325011/mongodb-robomongo-cant-connect-authentication
robomongo 0.8.x don't support auth,0.9.x support.

the last,i use mongo management studio,it work.

hope i can help you.

**Comment by anorsich** [comment]
@TNT-Likely @shashah Latest version of the Robomongo [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) supports SCRAM-SHA-1 authentication. Feel free to reopen this ticket if it still does not work for you.

**Comment by kilabyte** [comment]
Just downloaded 0.9 and auth is still not working with either method. i can connect via shell terminal but not via robomongo

**Comment by anorsich** [comment]
@kilabyte thank you for reporting this! To help us repro the issue, could you post your mongodb details here? Which version of mongodb you use? What authentication you use?

**Comment by kilabyte** [comment]
Mongo 3.2 and SHA-1. But I've tried both authentication methods with no luck. I also used another app called MongoChef that does connect to my db
