### ISSUE TITLE
Remote Connection Fail

### ISSUE THREAD

**Issue by murvinlai** [paralect/robomongo#958]
Somehow it cannot connect to Mongolabs DB.  With the same connection url / user / password / db, I can connect using mongo shell or other Admin tools.  But Robomongo fails without details.  just authentication fail.

**Comment by mclion** [comment]
MongoDB 3?

**Comment by cicorias** [comment]
Yes that's correct. I'm assuming Robomongo needs updating.

**Comment by programming-kid** [comment]
Yes i think its due to MongoDB 3 as recently mongolab updated to mongo 3

**Comment by boustanihani** [comment]
same issue here

**Comment by OKNoah** [comment]
So Robomongo is no longer compatible with Mongolab?

**Comment by schetnikovich** [comment]
@murvinlai @boustanihani @OKNoah  Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
