### ISSUE TITLE
Issue with mongodb 3.2 rc0

### ISSUE THREAD

**Issue by rahbari** [paralect/robomongo#960]
robomongo doesn't fetch collections.

**Comment by WeKyle** [comment]
see issue #520

**Comment by Zeioth** [comment]
Last update was in march. What is the state of the project right now?

**Comment by psychok7** [comment]
the same happens with the final version of 3.2

**Comment by nickykln** [comment]
Same problem for me. Mongo version 3.2.0.
Let me know when it will be fixed.

**Comment by aunz** [comment]
watching this

**Comment by sfunaro** [comment]
+1

**Comment by crimcol** [comment]
The same issue.
mongodb-win32-x86_64-2008plus-ssl-3.2.0-signed.msi
Robomongo 0.8.5

Problems:
- Robomongo does not fetch collection list;
- "Create Database" does not work;

**Comment by MirkoMignini** [comment]
+1

**Comment by HonorLee-cn** [comment]
+1

**Comment by dpolonsky** [comment]
+1

**Comment by styopdev** [comment]
+1

**Comment by nguyenhuuhanhlam** [comment]
same problem

**Comment by Zeioth** [comment]
There's a new version but currently only for linux and mac:
http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.

**Comment by losmir** [comment]
yes, robomongo 0.9.0 fetches all collections properly. Thanks for the answer!
