### ISSUE TITLE
Record is deleted when editing an integer.

### ISSUE THREAD

**Issue by codazoda** [paralect/robomongo#961]
If you edit a number, which is not cast, the record is deleted.

Take the example record below. If I edit the makeYear field and change it to '2005' (without the quotes) the record will be deleted. If, however, the numbers look like longInt(2005) instead, then it works as expected. I have lots of records, however, that are just numbers.

Here's my original record:

{
    "_id" : ObjectId("56294bab26994999627b23c6"),
    "vin" : "3B7KF23631G777028",
    "status" : "Active",
    "modifyTime" : ISODate("2015-10-22T20:51:54.000Z"),
    "createTime" : ISODate("2015-10-22T20:48:43.000Z"),
    "displayTime" : ISODate("2015-10-22T20:53:43.000Z"),
    "expireTime" : ISODate("2015-11-21T20:48:43.000Z"),
    "id" : 2.49513e+06,
    "memberId" : 2.38524e+06,
    "photo" : [ 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547089-337655.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:31.317Z"),
            "extension" : "jpeg",
            "md5" : "3631eda10fc139ecb77369c3b19cf643",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408024893733.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547089-297640.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:31.315Z"),
            "extension" : "jpeg",
            "md5" : "2803a395e19200b6714d6a2ba0072438",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408014893734.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547089-307789.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:31.550Z"),
            "extension" : "jpeg",
            "md5" : "f5fc87163c4bd42251c2f7b2f9f764a7",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408021560400.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547092-392407.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:34.103Z"),
            "extension" : "jpeg",
            "md5" : "8a1c4e998151509c6cbcef52ab706eca",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408028227066.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547092-564726.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:34.162Z"),
            "extension" : "jpeg",
            "md5" : "796aed3dfdda3373a26b0d32c459db52",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408038227065.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547092-770751.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:34.283Z"),
            "extension" : "jpeg",
            "md5" : "25fe44764599cb33f099d4c0a355316e",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408031560399.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547094-125837.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:36.231Z"),
            "extension" : "jpeg",
            "md5" : "123de0f83e6ad3f6dbdcb57a7c25dfd1",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408054893730.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547094-729149.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:36.573Z"),
            "extension" : "jpeg",
            "md5" : "0b01f139eff6d1b3e0a6532cbdd0d726",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408044893731.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547095-244660.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:37.083Z"),
            "extension" : "jpeg",
            "md5" : "caef5215c4cdf8c652e5da5ce8c19089",
            "height" : 480,
            "width" : 640,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408058227063.jpeg"
        }, 
        {
            "id" : "http://img.ksl.com/mx/mplace-cars.ksl.com/2385235-1445547096-628214.jpeg",
            "upload_time" : ISODate("2015-10-22T20:51:38.351Z"),
            "extension" : "jpeg",
            "md5" : "3a3210921badc2f324bfeda257ea1588",
            "height" : 600,
            "width" : 450,
            "description" : "",
            "originalFilePath" : "",
            "originalFileName" : "received_1051408064893729.jpeg"
        }
    ],
    "newUsed" : "Used",
    "address1" : "313 S 500 W ",
    "body" : "Truck",
    "city" : "PROVO",
    "cylinders" : "6",
    "dealerLicense" : "036A",
    "dealerName" : "Prime Auto Connection LLC",
    "description" : "JUST IN, 2001 DODGE CUMMINS.5.9 L DIESEL.. . Clean Title.Very Clean Good Running. PRIME AUTO CONNECTION LLC Offers a Wide Variety of Cars for Sell. All Our Cars come with a 3 month Warranty! We offer a Very Large Selection and can find just about anything your looking for. We have Competitive Pricing, Call us for any questions or to Come Test Drive a Car Today. Trade-Ins are Welcome.\r\n\r\nCall James 801-472-7088 \r\nCall Oscar at 801-800-2474\r\n\r\nProvo Office: 801-960-9365\r\nLehi Office: 801-341-8720\r\n\r\n***call us today to do an over the phone application*** \r\nWe offer financing regardless of your credit situation. Bad credit, no credit, first time buyer, we will get you approved for a car. \r\n\r\nWe are very friendly and offer no pressure. We want you to be happy and make the right decision. \r\n\r\nThank you for viewing our ad, \r\n\r\nThe Prime Auto Connection Team.",
    "drive" : "4-Wheel Drive",
    "email" : "primeautoconnection@gmail.com",
    "exteriorColor" : "White",
    "exteriorCondition" : "Very Good",
    "firstName" : "Prime Auto",
    "fuel" : "Diesel",
    "interiorColor" : "Gray",
    "interiorCondition" : "Very Good",
    "lastName" : "Connection",
    "lat" : 40.2205000000000013,
    "latLon" : "40.2205,-111.6931",
    "lon" : -111.6931000000000012,
    "make" : "Dodge",
    "makeYear" : 2001,
    "mileage" : 200500,
    "mobilePhone" : " (877) 264-3892",
    "model" : "Ram 2500",
    "numberDoors" : 2,
    "postIp" : "50.160.57.114",
    "price" : 10990.0000000000000000,
    "primaryPhone" : " (877) 264-3892",
    "sellerType" : "Dealership",
    "state" : "UT",
    "titleType" : "Clean Title",
    "transmission" : "Automatic",
    "trim" : "SLT",
    "zip" : "84601",
    "stats" : {
        "ui" : {
            "srp" : {
                "view" : {
                    "20151022" : 1010,
                    "20151023" : 211
                }
            },
            "vdp" : {
                "view" : {
                    "20151022" : 26,
                    "20151023" : 5
                },
                "gallary" : {
                    "view" : {
                        "20151022" : 19,
                        "20151023" : 3
                    }
                }
            }
        }
    }
}

**Comment by codazoda** [comment]
Actually, the record is not deleted. The 'id' column changes to a different number when I submit the edit.

**Comment by anorsich** [comment]
@codazoda This annoying bug was just fixed in [0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/). Could you try it and let us know if it worked for you?

**Comment by codazoda** [comment]
0.9.0 seems to work for me. I can now update my values. It works by automatically adding in 'NumberLong(1996)' where it might have simply been '2005' previously. This prevents the rest of the record from blowing up. Thanks for the fix!

**Comment by anorsich** [comment]
@codazoda Awesome! Happy to hear that it worked for you.
