### ISSUE TITLE
Crash on connecting Ext display (MAC)

### ISSUE THREAD

**Issue by sergio-doman** [paralect/robomongo#966]
Hi, 

when I'm trying to connect/disconnect external display application crashes each time and I need to restart it.
OS X 10.9.5 (13F1134)

**Comment by spoonscen** [comment]
Same here.  Experiencing the same issue OSX 10.11 (15A284)

**Comment by will-weiss** [comment]
I too experience this issue daily - I'm running OSX Yosemite 10.10.5

**Comment by gavruk** [comment]
@sergio-doman @spoonscen @will-weiss I cannot reproduce this with Robomongo 0.9.0 RC3 on OS X 10.11.3
Can you still reproduce this with 0.9.0?

**Comment by anorsich** [comment]
@will-weiss @spoonscen I do beleive this issue has been fixed with latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/). I am closing this issue for now, if you still have issues, please reopen this issue.
