### ISSUE TITLE
collections are not showing up in mongochef and robomongo 

### ISSUE THREAD

**Issue by suprabhatm** [paralect/robomongo#967]
We could connect using mongochef but collections are not showing up in mongochef tool. I am not able to get any straight answer through any forum. Is it a bug, wip or something wrong which needs correction from user's side? Please suggest.

**Comment by tomasznaumowicz** [comment]
Can you actually list your collections when connected using the shell? Could it be an issue with your permissions on the database?
BTW: MongoChef has their support staff available at support@3t.io

**Comment by suprabhatm** [comment]
Yes, there could be, which I would like to know.

**Comment by schetnikovich** [comment]
@suprabhatm You probably use MongoDB 3.x. Only starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
