### ISSUE TITLE
collections are not showing on robomongo

### ISSUE THREAD

**Issue by nidhinz** [paralect/robomongo#969]
Dear Team,

In my mongodb i can able to view all the tables under my project. but in robomongo no collections are listed under the project. If I am searching with the name of the collection I can able to open the specific collection. please give me some solution for this issue

**Comment by SwenChan** [comment]
I have met this problem too.And I think it is because of the new engine WiredTiger in 3.0.
Now I use mongoChef instead.But I hope robomongo can support WiredTiger soon because I prefer to use Robomongo : )

**Comment by shuaqiu** [comment]
I have this problem too.

**Comment by amiashraf** [comment]
I am here also experiencing same problem and eagerly want to know the approx time, when we will be able to see the problem is fixed?

**Comment by anorsich** [comment]
@amiashraf Robomongo 0.8.5 does not support mongodb 3+, that's why collection does not showing. But there is [0.9 RC1](http://blog.robomongo.org/) for osx and linux which do support mongodb 3+

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.
