### ISSUE TITLE
Ability to adjust height of query editor

### ISSUE THREAD

**Issue by StealthyDev** [paralect/robomongo#970]
I have a pretty long screen and I am stuck with the default auto-growing height.

Ability to adjust height of the query editor will be awesome.

**Comment by StealthyDev** [comment]
![robo](https://cloud.githubusercontent.com/assets/2009963/10975763/78b99224-83b6-11e5-8d2d-e6464b553b5b.png)

**Comment by synthomat** [comment]
Possible duplicate of #657

**Comment by juliashibalko** [comment]
@StealthyDev Let me suggest you to track issue progress within #657 ticket. I will close this one as duplicate if you don't mind. Please feel free to reopen or submit new one. Thanks!

**Comment by simsekgokhan** [comment]
Hi guys, thanks a lot for your interest, sorry for the long delay. We have finished development of a new feature which will give you full screen query editor and dock-able output window (for each tab). 

Please see the screenshots here:
[New Feature: Full Screen Query Editor (Dockable Output Window)](1187) 

Feature is under internal testing, planing to release next week. 
Follow the latest releases and news here: 
https://twitter.com/Robomongo
