### ISSUE TITLE
Integer values (int32) converted to '6.1857e+06' format in edit mode for value 6185702

### ISSUE THREAD

**Issue by mcolynuck** [paralect/robomongo#974]
I have records with array of integers.  Viewing the record shows them as I expect them to be (see attached screenshot image).  They are shown as Int32 types.  When I try to edit the record, data in the popup window has changed the integer values to '6.1857e+06', for example.

My first thought was that it was too large for int32 but isn't that in the neighbourhood of 2 billion? 

I used another mongodb editor to edit the data and it did so without this problem (same record) so I suspect a bug but please correct me if this is 'user error' in some way.

(Note: selected line is not the one with the problem, it is any number > 1 million)
<img width="1013" alt="screen shot 2015-11-09 at 9 37 52 am" src="https://cloud.githubusercontent.com/assets/4674880/11041393/6d9f3796-86c6-11e5-81b5-77c5735a8289.png">

Here is the data as it is provided in the edit window:
{
    "_id" : ObjectId("54d313cf3431330003000000"),
    "activity_level" : 1.2000000000000000,
    "age" : 55,
    "allergies_dislikes_list" : [ 
        "none"
    ],
    "bmi" : 22,
    "height" : 172.7100000000000080,
    "height_ft" : 5,
    "height_inch" : 8,
    "menu" : [ 
        62927, 
        6.1857e+06, 
        2.0896e+06, 
        436183, 
        523, 
        33021, 
        189749, 
        332, 
        216769, 
        676, 
        674417, 
        7.15988e+06, 
        3.62953e+06, 
        20338, 
        604, 
        1.0403e+06, 
        7.66992e+06, 
        8.10832e+06, 
        7.17544e+06, 
        95626, 
        431836, 
        6.6717e+06, 
        7.13116e+06, 
        1.90479e+06, 
        62927, 
        6.1857e+06, 
        2.0896e+06, 
        436183, 
        523, 
        33021, 
        189749, 
        332, 
        216769, 
        676, 
        674417, 
        7.15988e+06, 
        3.62953e+06, 
        20338, 
        604, 
        1.0403e+06, 
        7.66992e+06, 
        8.10832e+06, 
        7.17544e+06, 
        95626, 
        431836, 
        6.6717e+06, 
        7.13116e+06, 
        1.90479e+06, 
        62927, 
        6.1857e+06, 
        2.0896e+06, 
        436183, 
        523, 
        33021, 
        189749, 
        332, 
        216769, 
        676, 
        674417, 
        7.15988e+06, 
        3.62953e+06, 
        20338, 
        604, 
        1.0403e+06, 
        7.66992e+06, 
        8.10832e+06, 
        7.17544e+06, 
        95626, 
        431836, 
        6.6717e+06, 
        7.13116e+06, 
        1.90479e+06
    ],
    "modified_height" : 0,
    "password_hash" : "$2a$10$RdAf2GCpYqDVox62VlI5r.ZyFxrKDZ6KsdILysg9QSPqWdSaOniCe",
    "requirements" : {
        "calories" : 1588.6800000000000637,
        "fat" : 357.4529999999999745,
        "protein" : 68.0000000000000000,
        "calcium" : 1150,
        "fiber" : 32.5000000000000000
    },
    "weight" : 68.0000000000000000,
    "weight_pounds" : 150
}

**Comment by brandonros** [comment]
I have this issue too and it corrupts upon saving I believe.

**Comment by david-benes** [comment]
I see this issue as well, this happens since 0.8.5, it was fine in 0.8.4.

**Comment by darkin1** [comment]
+1
0.8.5

**Comment by schetnikovich** [comment]
@mcolynuck @brandonros @david-benes @darkin1 This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.

**Comment by david-benes** [comment]
So far so good :) Thanks for all the fixes, 0.9.0 RC3 looks very promising.

2016-01-29 17:35 GMT+01:00 Dmitry Schetnikovich <notifications@github.com>:
