### ISSUE TITLE
(Double) Quotes in SSH Password

### ISSUE THREAD

**Issue by schwimmfuzzi** [paralect/robomongo#975]
I had some issues with double quotes in my ssh password i(n v.0.8.4 and .5). A brief look to the saved config file told me that it is escaped there when saving. But it seems, that the escaped character is not 'unescaped' when the saved file is getting parsed in again. ErrorMsg:

`code FailedToParse: FailedToParse: Expecting '}' or ',': offset:67`

**Comment by anorsich** [comment]
Hi @schwimmfuzzi, in next version of the Robomongo we will return ssh support back. We are re-working it from scratch to make it more and less error prone. To keep implementation progress, please use #1002. Going to close this ticket for now, feel free to reopen it if needed.
