### ISSUE TITLE
Mongodb3.x support?

### ISSUE THREAD

**Issue by kaito-kidd** [paralect/robomongo#976]
Probably when can support mongodb3.x?

**Comment by alexpts** [comment]
+

**Comment by bachner** [comment]
+1

**Comment by dartmedved** [comment]
last update 8 months ago. looks like project is frozen.

**Comment by alexpts** [comment]
((

**Comment by adrian-wang** [comment]
+1 , cannot connect to mongod with -auth enabled

**Comment by imManuelCordon** [comment]
This project still alive? Last code change was April 18, 2015!!!

**Comment by lockwobr** [comment]
+1

**Comment by Zeioth** [comment]
There's a new RC, but currently only for linux:
http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/

**Comment by adrian-wang** [comment]
Wow, thanks a lot!
