### ISSUE TITLE
Mongo 3.2 uses SpiderMonkey again

### ISSUE THREAD

**Issue by runxc1** [paralect/robomongo#977]
With the MongoShell switching back to using SpiderMonkey as opposed to V8 I am hoping that this project can get moving again.  The paid products out there really seem to be lacking

**Comment by elennaro** [comment]
Spider Monkey has much better support for ES6.

**Comment by schetnikovich** [comment]
@runxc1, @elennaro Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, and use the same SpiderMonkey engine, that is part of MongoDB. Let us know, how it works for you.
