### ISSUE TITLE
_id converted to double in doc

### ISSUE THREAD

**Issue by andidev** [paralect/robomongo#978]
When accessing a property in a doc the _id is converted from Int32 to Double

**without accessing property _id is an Int32**
![image](https://cloud.githubusercontent.com/assets/571389/11332947/3de44cda-91ca-11e5-9943-9bdfd4d74c83.png)

**when accessing property _id is converted to Double**
![image](https://cloud.githubusercontent.com/assets/571389/11332937/2753bd66-91ca-11e5-8747-a2f18030f182.png)

**Comment by schetnikovich** [comment]
@andidev This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
