### ISSUE TITLE
Cannot build (link) current version

### ISSUE THREAD

**Issue by shestero** [paralect/robomongo#979]
PS What the BOOST_ENABLED option means?
My errors:
[ 98%] Linking CXX executable build/robomongo
librobomongo_libd.a(MainWindow.cpp.o): In function `std::vector<Robomongo::ConnectionSettings*, std::allocator<Robomongo::ConnectionSettings*> >::_M_range_check(unsigned int) const':
/usr/local/include/c++/4.9.3/bits/stl_vector.h:803: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
librobomongo_libd.a(BsonUtils.cpp.o): In function `boost::gregorian::bad_day_of_month::~bad_day_of_month()':
/media/T1T/robomongo-master/src/third-party/mongodb/src/third_party/boost/boost/date_time/gregorian/greg_day.hpp:20: undefined reference to `std::out_of_range::~out_of_range()'
librobomongo_libd.a(BsonUtils.cpp.o): In function `boost::gregorian::bad_year::~bad_year()':
/media/T1T/robomongo-master/src/third-party/mongodb/src/third_party/boost/boost/date_time/gregorian/greg_year.hpp:20: undefined reference to `std::out_of_range::~out_of_range()'
librobomongo_libd.a(BsonUtils.cpp.o): In function `boost::gregorian::bad_month::~bad_month()':
/media/T1T/robomongo-master/src/third-party/mongodb/src/third_party/boost/boost/date_time/gregorian/greg_month.hpp:44: undefined reference to `std::out_of_range::~out_of_range()'
librobomongo_libd.a(engine.cpp.o): In function `std::list<mongo::Scope*, std::allocator<mongo::Scope*> >::_M_insert(std::_List_iterator<mongo::Scope*>, mongo::Scope* const&)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1681: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
librobomongo_libd.a(engine.cpp.o): In function `std::list<mongo::Scope*, std::allocator<mongo::Scope*> >::_M_erase(std::_List_iterator<mongo::Scope*>)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1697: undefined reference to `std::__detail::_List_node_base::_M_unhook()'
librobomongo_libd.a(ptimeutil.cpp.o): In function `boost::gregorian::bad_weekday::~bad_weekday()':
/media/T1T/robomongo-master/src/third-party/mongodb/src/third_party/boost/boost/date_time/gregorian/greg_weekday.hpp:32: undefined reference to `std::out_of_range::~out_of_range()'
librobomongo_libd.a(ScriptEngine.cpp.o): In function `std::vector<mongo::BSONElement, std::allocator<mongo::BSONElement> >::_M_range_check(unsigned int) const':
/usr/local/include/c++/4.9.3/bits/stl_vector.h:803: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
librobomongo_libd.a(engine_spidermonkey.cpp.o): In function `std::list<std::string, std::allocator<std::string> >::_M_insert(std::_List_iterator<std::string>, std::string const&)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1681: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
libmongoclient.a(initializer_dependency_graph.o): In function `std::vector<std::string, std::allocator<std::string> >::_M_range_check(unsigned int) const':
/usr/local/include/c++/4.9.3/bits/stl_vector.h:803: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
libmongoclient.a(dbclient.o): In function `std::list<mongo::HostAndPort, std::allocator<mongo::HostAndPort> >::_M_insert(std::_List_iterator<mongo::HostAndPort>, mongo::HostAndPort const&)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1681: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
libmongoclient.a(dbclient.o): In function `std::list<mongo::BSONObj, std::allocator<mongo::BSONObj> >::_M_insert(std::_List_iterator<mongo::BSONObj>, mongo::BSONObj const&)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1681: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
libmongoclient.a(connpool.o): In function `std::list<mongo::DBConnectionHook*, std::allocator<mongo::DBConnectionHook*> >::_M_insert(std::_List_iterator<mongo::DBConnectionHook*>, mongo::DBConnectionHook* const&)':
/usr/local/include/c++/4.9.3/bits/stl_list.h:1681: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/build/robomongo] Error 1

**Comment by schetnikovich** [comment]
@shestero We suggest to use the latest sources, that are part of Robomongo 0.9.0. Version 0.8.x is no longer supported. In new version all build scripts are fully rewritten. If you'll face with any problem, I will be happy to help, but this is probably will be a new ticket. 

Documentation:
https://github.com/paralect/robomongo/tree/master/docs
