### ISSUE TITLE
Can't work well in MongoDB v3.2

### ISSUE THREAD

**Issue by huydev** [paralect/robomongo#981]
Connected the db, but can't view collections.
system is Window7

**Comment by dsanchez31** [comment]
Me too !
Os : Windows10 x64

**Comment by stephane-ruhlmann** [comment]
Same thing here though typing db.collections prints expected result.
OSX 10.10.5

**Comment by stephane-ruhlmann** [comment]
Linked to #520

**Comment by gemron** [comment]
me too too!

**Comment by zeuselephant** [comment]
Can't connection to MongoDB 3.2 on Ubuntu 14.04

**Comment by Zeioth** [comment]
There's a new version but currently only for linux and mac:
http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/

**Comment by schetnikovich** [comment]
Robomongo 0.9.0 RC2 just [released for all platforms](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux). Support for MongoDB 3.x and WiredTiger engine is built-in. Let us know, how it works for you.
