### ISSUE TITLE
Compatibility with Modulus.io?

### ISSUE THREAD

**Issue by dhorner** [paralect/robomongo#983]
In a Modulus blog post (http://blog.modulus.io/robomongo-modulus-mongodb) back in 2014 said "Note that the current version of Robomongo (0.8.5) does not support authenticating against MongoDB 3.0.3 databases. This will be fixed in Robomongo 0.9, which is coming soon."

Will there be a 9.0?  Is there a branch that works with Modulus.io?

Thanks,

Dave

**Comment by ArdentKid** [comment]
+1

**Comment by anorsich** [comment]
@dhorner, @ArdentKid: We would love to continue work on Robomongo, but this is a bit difficult for us at the moment. Yesterday, we've started a campaign to get some funds and start development again. All details about the future of the robomongo and support of modulus.io (mongodb 3.0 - 3.2) are on (Robomongo website)[http://robomongo.org/].

**Comment by schetnikovich** [comment]
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. For any found issues, please create new ticket.
