### ISSUE TITLE
query-input: cursor blinks when input-field has no focus

### ISSUE THREAD

**Issue by Oppodelldog** [paralect/robomongo#984]
on linux:
please, please stop the cursors blinking when the input field has no focus.

**Comment by romankonz** [comment]
this would be great! 
it's really confusing after copying some infos in the json document view.
Everytime i switch back from the application i pasted it in, i need a couple of seconds to realize that i can't edit my query because it has not the focus.

**Comment by schetnikovich** [comment]
@Oppodelldog, @romankonz Do you can still reproduce this issue with Robomongo 0.9.0-RC7? I do not experience specified behaviour. Checked on three OSes: Linux, Mac and Windows.

**Comment by juliashibalko** [comment]
@Oppodelldog, @romankonz Could you please try to reproduce the issue with the latest [Robomongo 0.9.0-RC9](https://robomongo.org/download) version if you have some free minutes? I didn't manage to replicate it, so seems that issue can be closed. Thank you!
