### ISSUE TITLE
is it possible to export config from windows to mac robomongo?

### ISSUE THREAD

**Issue by lesterjanpearson** [paralect/robomongo#985]
is it possible to export config from windows to mac robomongo?

**Comment by schetnikovich** [comment]
Yes, just copy `robomongo.json` file from the following location on Windows:

    c:\Users\YourName\.config\robomongo.json

To the following location on Mac:

    ~/.config/robomongo.json

**Comment by lesterjanpearson** [comment]
Im new at mac, how do you go to ~/.config/ ?

**Comment by gavruk** [comment]
@lesterjanpearson on OS X, open `Terminal` and type 
If you used Robomongo 0.8.x
`cat .config/robomongo/robomongo.json`
If you used Robomongo 0.9.x
`cat .config/robomongo/0.9/robomongo.json`
Copy the `json` you'll see after running this command (it should be between curly braces `{...}`)

And then on Windows, paste this `json` into 
`c:\Users\<Your_Username>\.config\robomongo\robomongo.json` for Robomongo 0.8.x
`c:\Users\<Your_Username>\.config\robomongo\0.9\robomongo.json` for Robomongo 0.9.x

**Comment by simsekgokhan** [comment]
Latest information in the following wiki page: [Robomongo Config File Guide](https://github.com/Studio3T/robomongo/wiki/Robomongo-Config-File-Guide)
