### ISSUE TITLE
Linux .deb 64b installer removes xserver

### ISSUE THREAD

**Issue by jamming** [paralect/robomongo#987]
Installing the .deb for 64 bits Linux in Kubuntu 14.04 LTS removed xorg-server package... and that wasn't funny. I installed the package with the graphical KDE interface (double click over the .deb file).

The binary I used was: http://app.robomongo.org/files/linux/robomongo-0.8.5-x86_64.deb

My system information is:

    $ uname -a
    Linux jamhost 3.19.0-39-generic #44~14.04.1-Ubuntu SMP Wed Dec 2 10:00:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/os-release 
    NAME="Ubuntu"
    VERSION="14.04.3 LTS, Trusty Tahr"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 14.04.3 LTS"
    VERSION_ID="14.04"
    HOME_URL="http://www.ubuntu.com/"
    SUPPORT_URL="http://help.ubuntu.com/"
    BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by anorsich** [comment]
@jamming We are sorry to hear that. We've released [new version](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/) of robomongo just a couple of days ago and do not have .deb package yet. You can just download the archive and run robomongo using `./bin/robomongo`. It won't delete anything on your machine. We also planning to rework .deb and .rpm packaging and make sure that it won't remove xorg-server package.

**Comment by jamming** [comment]
Thanks for the update! If you release Robomongo as a tar.gz I would definitely use that.

**Comment by anorsich** [comment]
@jamming tar.gz is what we have already for linux, so you can start use it right away. Download links are at the bottom of the [blog post](http://blog.robomongo.org/robomongo-rc4/) about 0.9.0 RC4 release.

**Comment by anorsich** [comment]
@jamming Since new versions do not have .deb package, I am going to close this ticket. We are going to rework packaging for Linux in the near feature and will make sure it works correct and does not delete anything. Feel free to reopen the ticket if you think we still need it.
