### ISSUE TITLE
There are many collections in DB but not showing in Left panel collection tab 

### ISSUE THREAD

**Issue by asingh200** [paralect/robomongo#988]
![a](https://cloud.githubusercontent.com/assets/10336770/11838262/da8f852e-a40b-11e5-9ffc-f914ea18bdb8.png)

**Comment by malyavkin** [comment]
Which mongodb version do you use?
If it's 3.x there *might* be a possibility of Robomongo being simply incompatible with it.

**Comment by asingh200** [comment]
yes its 3.2 :(

**Comment by rowellx68** [comment]
Unfortunately, the current version of Robomongo does not support the storage architectures that came with MongoDB 3.x

>1. Support for MongoDB 3.x storages (WiredTiger and others)

One of the major features that is discussed [here](http://blog.robomongo.org/robomongo-future/).

**Comment by kbrekke** [comment]
Same issue here with Robomongo 0.8.5 and MongoDb 3.2.

**Comment by schetnikovich** [comment]
Only starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. For any found issues in new version, please create new ticket.
