### ISSUE TITLE
Test connect is passed but Connect is failed.

### ISSUE THREAD

**Issue by coresilver** [paralect/robomongo#989]
Hello,

I test connect is passed on Windows 7.
But after press Connect button then it's nothing !
Find attached for more detail.
![conn1](https://cloud.githubusercontent.com/assets/4004867/11862356/b8802248-a4bc-11e5-8bbd-237fbd4dee2f.PNG)
![conn2](https://cloud.githubusercontent.com/assets/4004867/11862360/bfeee636-a4bc-11e5-9fe8-779756dbe5dd.PNG)

**Comment by ManvendraSK** [comment]
Are you running `mongod.exe` before pressing connect button?

**Comment by coresilver** [comment]
Yes! suggest plz.

**Comment by ManvendraSK** [comment]
Hmm.. Could you please tell me why are you connecting on port `27018`? Moreover, could you please attach your `mongod.conf` file here? Usually found at `/etc/mongod.conf` in `Linux`. For `Windows` please follow this link http://www.mkyong.com/mongodb/how-to-install-mongodb-on-windows/.

**Comment by anorsich** [comment]
@coresilver Could you try connect to your mongodb instance using latest, [0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/) release? Let us know it will work.

**Comment by coresilver** [comment]
Thank you for update new version.
I will send you the result.

Good day.

**Comment by anorsich** [comment]
@coresilver Just wanted to follow to see if everything is working well for you now. Let me know your findings! Thank you.

**Comment by anorsich** [comment]
@coresilver Was you able to test this issue on the new version of Robomongo? I am closing this ticket, if Robomongo still does not work for you -- please, reopen.
