### ISSUE TITLE
Scientific notation when editing document with Unix timestamps may cause rounding upon save

### ISSUE THREAD

**Issue by Greblak** [paralect/robomongo#990]
When viewing a document in tree mode the number is displayed as normal.
When attempting to edit the document, all unix timestamps are displayed with a scientific notation:

"created" : 1.44836e+09,

The true value is 1448361815

If I was to do my edits and save the document. Would not these timestamps be rounded?

I have not tested this as this was a production database.

**Comment by schetnikovich** [comment]
@Greblak This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
