### ISSUE TITLE
./robomongo.sh - unable to open the application in UBUNTU 12.04

### ISSUE THREAD

**Issue by sonaskd** [paralect/robomongo#991]
I downloaded the robomongo*.deb from robomnogo.org
and trying to run the robomngo.sh file, it doesn't work

**Comment by anorsich** [comment]
@sonaskd Thank you for reporting this issue. We know for sure that latest release [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) does not work on Ubuntu 12.04. I'll close this ticket as duplicate of #982 , so you can keep tracking progress there.
