### ISSUE TITLE
query show collections cant get result

### ISSUE THREAD

**Issue by istamarr** [paralect/robomongo#992]
When I try to query show collections on latest db, then I cant get any result.

Can I get instruction or something ?

**Comment by lschans** [comment]
I have the same issue here, it shows all the collections but there are no results.
'Script executed successfully, but there are no results to show' 

What also happens is that robomongo crashes as soon as I try to edit the query. Just click in the query bar and there is a crash. Maybe somebody can confirm this.

I also only have this behaviour on mongodb 2.6.10 (on mongodb cloud manager and servers on aws).
I also run 2 clusters on 2.6.11 and I don't have this behaviour, so far this is all that I could find out about the bug..

**Comment by lschans** [comment]
A minor update, robomongo crashes as soon as I try to edit the query bar. So when I press . to add .count() or such then the app crashes.

There is no commandline output, don't know how to make it debug more, all the log says is

Tue Jan  5 10:01:36.605 [Robomongo] SettingsManager initialized in /Users/lschans/.config/robomongo/robomongo.json
Tue Jan  5 10:01:36.608 [Robomongo] Settings saved to: /Users/lschans/.config/robomongo/robomongo.json
Tue Jan  5 10:01:45.732 [Robomongo] Settings saved to: /Users/lschans/.config/robomongo/robomongo.json
Tue Jan  5 10:01:45.734 [Robomongo] Connecting to xxx.31.xxx.116:27017...
Tue Jan  5 10:01:45.759 ERROR: [Robomongo] connect failed
Tue Jan  5 10:01:54.816 [Robomongo] Connecting to xxx.31.xxx.116:27017...
Tue Jan  5 10:01:54.837 ERROR: [Robomongo] connect failed
Tue Jan  5 10:01:54.840 [Robomongo] Opening shell...
Tue Jan  5 10:01:54.840 [Robomongo] db.getCollection('users').find({})

This implies that the connection fails, but if so.. How come that robomongo is able to get all collections. And this also doesn't happen when I use the shell?

**Comment by schetnikovich** [comment]
You probably use MongoDB 3.x. Only starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. For any found issues, please create new ticket.
