### ISSUE TITLE
robo mongo con't showing the collection 

### ISSUE THREAD

**Issue by raokoti** [paralect/robomongo#993]
i am using node js and mongo db in my project,i am use to see my database through robomongo it doesn't showing the collections

**Comment by JTrotta** [comment]
RoboMongo does not work with MongoDb 3.2 http://blog.robomongo.org/robomongo-future/

**Comment by ovox** [comment]
Ahh, and I thought my mongo setup had a glitch. Makes sense now. Too bad I only read this now, I would've installed 3.0.7 if I knew Robomongo is incompatible with 3.2.0. Oh well, thanks for clearing that up.

**Comment by pktippa** [comment]
Facing the same issue with monogdb 3.2.x , robomongo 0.8.5 is not working.

**Comment by schetnikovich** [comment]
You probably use MongoDB 3.x. Only starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. For any found issues, please create new ticket.
