### ISSUE TITLE
robomomgo authentication failed meteor deployed database

### ISSUE THREAD

**Issue by aboobakkar** [paralect/robomongo#994]
meteor mongo --url  mimo-tf.meteor.com |clip          entered and then given url paste robomngo address..then will get error ??? how to get my database ??

**Comment by schetnikovich** [comment]
@aboobakkar, you probably use MongoDB 3.x. Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. For any found issues, please create new ticket.
