### ISSUE TITLE
Collections  are not being listed

### ISSUE THREAD

**Issue by cristian-vertiz-tierconnect-com** [paralect/robomongo#995]
Collections  are not being listed in robomongo 0.85 installed in Centos 7

**Comment by voz** [comment]
FYI, RoboMongo does not work with MongoDb 3.2 http://blog.robomongo.org/robomongo-future/

Maybe this is the reason if you are using a recent MongoDb

**Comment by schetnikovich** [comment]
@cristian-vertiz-tierconnect-com, you probably use MongoDB 3.x. Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x and WiredTiger engine. For any found issues, please create new ticket.

**Comment by cristian-vertiz-tierconnect-com** [comment]
Dmitry, Thank you very much, I will download and test new Robomongo 0.9.0

CRISTIAN VERTIZ | *Sr. Developer*
MOJIX | CODEROAD

Phone:  248.233.6016

Email  :  cristian.vertiz@mojix.com

Skype :  cristian.vertiz.coderoad.com <http://www.mojix.com/>
 Integrity • Teamwork • Innovation

This email and any attachments may contain private, confidential and
privileged material for the sole use of the intended recipient. If you are
not the intended recipient, please immediately delete this email and any
attachments.
