### ISSUE TITLE
IPv6 connection failed

### ISSUE THREAD

**Issue by acvetkov** [paralect/robomongo#997]
Hi!

I can't connect to my mongodb, that located on ipv6 host.
Does it support?

```
Robomongo 0.8.5
OSX 10.10.3
```

**Comment by mobilesfinks** [comment]
I confirm that problem also exist in 0.9.0 RC4. Cannot connect to host over IPv6. Connection over IPv4 work good. Another client (MongoChef) work good over IPv6

Robomongo 0.9.0 rc4
Linux Mint 17.3

**Comment by anorsich** [comment]
@acvetkov @mobilesfinks I have a great news for you guys! IPv6 support was implemented in latest [RC-6](http://blog.robomongo.org/ipv6-protocol/) release, if that still does not work for you -- feel free to reopen!
