### ISSUE TITLE
distinct() returns an object instead of an array

### ISSUE THREAD

**Issue by emilh91** [paralect/robomongo#998]
The returned object has keys that are numeric strings (e.g., "0", "1", "2", etc.). 
Here is a relevant unanswered question on StackOverflow:  https://stackoverflow.com/questions/29631746

**Comment by schetnikovich** [comment]
@emilh91, this issue is fixed now and will be part of Robomongo 0.9 RC3. Thank you for reporting this problem!

**Comment by schetnikovich** [comment]
@emilh91 This issue was fixed in just released [Robomongo 0.9.0 RC3](http://blog.robomongo.org/robomongo-0-9-0-rc3-released). Let us know how it works for you.
